import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
test('billing uses canonical production invoice tables',()=>{const s=read('src/pages/Billing.tsx');assert.match(s,/from\('invoices'\)/);assert.match(s,/from\('invoice_payments'\)/);assert.doesNotMatch(s,/client_invoices/);});
test('public auth routes are noindex and recovery uses the Vorlen recovery edge flow',()=>{const app=read('src/App.tsx'),recovery=read('src/pages/PasswordRecovery.tsx'),confirm=read('src/pages/AuthConfirm.tsx'),edge=read('supabase/functions/password-recovery/index.ts');assert.match(app,/forgot-password/);assert.match(app,/reset-password/);assert.match(app,/auth\/confirm/);assert.match(recovery,/functions\.invoke\('password-recovery'/);assert.doesNotMatch(recovery,/resetPasswordForEmail/);assert.match(recovery,/updateUser\(\{password\}\)/);assert.match(recovery,/robots:noIndex/);assert.match(confirm,/verifyOtp/);assert.match(edge,/https:\/\/www\.vorlen\.co\.uk\/auth\/confirm/);});
test('private workspace has a noindex SEO guard',()=>{const s=read('src/App.tsx');assert.match(s,/PrivateSeo/);assert.match(s,/robots:noIndex/);assert.match(s,/path="\/dashboard\/\*"/);});
test('careers uses canonical published job fields',()=>{const api=read('src/lib/api.ts'),home=read('src/pages/CareersHome.tsx');assert.match(api,/commission_text/);assert.doesNotMatch(api,/updated_at/);assert.match(home,/eq\('status','published'\)/);assert.match(home,/setSeo/);});
test('browser production env contains no obvious server secrets',()=>{const s=read('.env.production');for(const key of ['SERVICE_ROLE','STRIPE_SECRET','WEBHOOK_SECRET','AI_API_KEY','RESEND_API_KEY','TWILIO_AUTH'])assert.doesNotMatch(s,new RegExp(key));});
test('subscription features are gated in the application router',()=>{const app=read('src/App.tsx'),access=read('src/lib/access.ts');assert.match(app,/AccessGate kind="automations"/);assert.match(app,/AccessGate kind="billing"/);assert.match(app,/AccessGate kind="manage"/);assert.match(access,/features\.automations===true/);assert.match(access,/features\.ai_screening===true/);});
test('the application has a top-level render recovery boundary',()=>{const main=read('src/main.tsx'),boundary=read('src/components/ErrorBoundary.tsx');assert.match(main,/ErrorBoundary/);assert.match(boundary,/componentDidCatch/);assert.match(boundary,/Your data has not been changed/);});

test('candidate progress portal controls cannot regress out of recruiter workspace',()=>{const s=read('src/pages/RecruiterWorkspace.tsx'),portal=read('src/pages/CandidatePortal.tsx');assert.match(s,/Candidate portal/);assert.match(s,/create_candidate_portal_token/);assert.match(s,/get_candidate_portal_token/);assert.match(s,/revoke_candidate_portal_token/);assert.match(s,/Generate 30-day link/);assert.match(s,/Copy link/);assert.match(s,/Open portal/);assert.match(s,/Refresh link/);assert.match(s,/Revoke/);assert.match(portal,/Private application workspace/);assert.match(portal,/YOUR APPLICATIONS/);assert.match(portal,/Request my data/);assert.match(portal,/Request erasure/);});

test('dashboard native form controls use the global Vorlen control system',()=>{const s=read('src/dashboard-fixes.css');assert.match(s,/\.app-shell input:not/);assert.match(s,/\.app-shell select/);assert.match(s,/\.app-shell textarea/);assert.match(s,/workspace-portal>label input/);assert.match(s,/list-row \.button-row select/);});
test('automation E2E contract requires create activate and queue verification',()=>{const s=read('src/pages/Automations.tsx');assert.match(s,/New sequence/);assert.match(s,/Save sequence/);assert.match(s,/Activate/);assert.match(s,/Automation queue/);assert.match(s,/automation_enrollments_candidate_id_fkey/);assert.match(s,/automation_enrollments_sequence_id_fkey/);});

test('partner workspace keeps client calling CRM capabilities',()=>{const s=read('src/pages/PartnerClients.tsx');for(const x of ['No answer','Contacted','Busy','Call back','Send more info','Interested','Follow up','Meeting booked','Not interested','Do not contact','Send follow-up email','AI call preparation','Callback'])assert.match(s,new RegExp(x));assert.match(s,/partner_client_activity/);assert.match(s,/partner_client_notes/);assert.match(s,/client-ai-brief/);assert.match(s,/partner-client-email/);});
test('partner accounts are isolated to dedicated workspace navigation',()=>{const s=read('src/components/Layout.tsx'),a=read('src/App.tsx'),settings=read('src/pages/Settings.tsx');assert.match(s,/role==='partner'/);assert.match(s,/\/dashboard\/partner/);assert.match(a,/PartnerClients/);assert.match(settings,/value="partner"/);});

test('workspace invitation flow always returns invited users to Vorlen and routes partners correctly',()=>{const admin=read('supabase/functions/admin-user-management/index.ts'),reset=read('src/pages/PasswordRecovery.tsx'),login=read('src/pages/Login.tsx');assert.match(admin,/https:\/\/www\.vorlen\.co\.uk/);assert.doesNotMatch(admin,/talentflow-nu-neon\.vercel\.app|talentflow\.vercel\.app/);assert.match(admin,/\/reset-password/);assert.match(reset,/role==='partner'.*\/dashboard\/partner/);assert.match(login,/role==='partner'.*\/dashboard\/partner/);});

test('send more info outcome requires the company brochure attachment',()=>{const s=read('supabase/functions/partner-client-email/index.ts');assert.match(s,/send_more_info/);assert.match(s,/COMPANY_BROCHURE_BUCKET/);assert.match(s,/COMPANY_BROCHURE_PATH/);assert.match(s,/attachments/);assert.match(s,/Vorlen-Company-Brochure\.pdf/);assert.match(s,/PDFDocument/);});

test('landing page contains no legacy TalentFlow customer branding',()=>{const s=read('src/pages/Landing.tsx');assert.doesNotMatch(s,/TALENTFLOW/);});
test('partner sourcing UI blocks non-sourcing partner profiles',()=>{const s=read('src/pages/PartnerClients.tsx');assert.match(s,/candidate_sourcer/);assert.match(s,/hybrid/);assert.match(s,/Add candidate/);assert.match(s,/Candidate creation is only available/);});
test('post-call follow-up task errors are surfaced',()=>{const s=read('src/pages/PartnerClients.tsx');assert.match(s,/follow-up task could not be created/);});

test('invite-only access has no self-service workspace creation path',()=>{const app=read('src/App.tsx'),login=read('src/pages/Login.tsx'),seo=read('scripts/seo-build.mjs');assert.doesNotMatch(app,/pages\/Onboarding|path="\/onboarding"/);assert.doesNotMatch(login,/nav\('\/onboarding'\)/);assert.match(login,/does not have access to a Vorlen workspace/);assert.doesNotMatch(seo,/Disallow: \/signup|Disallow: \/onboarding/);});


test('role routing keeps client users and partners out of staff workspaces',()=>{const app=read('src/App.tsx'),layout=read('src/components/Layout.tsx');assert.match(app,/RoleGate roles=\{\['viewer'\]\}/);assert.match(app,/RoleGate roles=\{\['partner'\]\}/);assert.match(app,/roles=\{\['owner','manager','recruiter'\]\}/);assert.match(layout,/role==='viewer'.*\/client/);assert.match(layout,/recruiterRoutes/);});

test('recruiters have operational navigation without management surfaces',()=>{const layout=read('src/components/Layout.tsx'),jobs=read('src/pages/Jobs.tsx');for(const route of ['/dashboard/jobs','/dashboard/candidates','/dashboard/pipeline','/dashboard/applications','/dashboard/interviews'])assert.match(layout,new RegExp(route.replaceAll('/','\\/')));assert.match(jobs,/Recruiter access is read-only here/);assert.match(jobs,/canManage/);});

test('client candidate review does not expose raw LinkedIn or direct CV URLs',()=>{const portal=read('src/pages/ClientPortal.tsx'),safe=read('src/pages/ClientSafeCv.tsx'),edge=read('supabase/functions/client-candidate-cv/index.ts'),review=read('supabase/functions/client-submission-review/index.ts');assert.doesNotMatch(portal,/linkedin_url|View LinkedIn/);assert.match(portal,/Open client-safe CV/);assert.match(safe,/Direct email, phone, postal address and personal profile links/);assert.match(edge,/\[email withheld by Vorlen\]/);assert.match(edge,/\[phone withheld by Vorlen\]/);assert.doesNotMatch(edge,/createSignedUrl/);assert.doesNotMatch(review,/cv_url:cvUrl|createSignedUrl/);});


test('partner V3 exposes account CRM, unified timeline, deal pipeline and outreach sequencing',()=>{const app=read('src/App.tsx'),layout=read('src/components/Layout.tsx'),crm=read('src/pages/PartnerCRM.tsx'),migration=read('supabase/migrations/20260925063000_partner_platform_v3_foundation.sql'),sequence=read('supabase/migrations/20260925081000_complete_partner_outreach_sequence_lifecycle.sql');assert.match(app,/PartnerCRM/);assert.match(layout,/Account CRM/);assert.match(crm,/ACCOUNT CRM/);assert.match(crm,/Unified account timeline/);assert.match(crm,/Deals \/ opportunities/);assert.match(crm,/Outreach sequences/);assert.match(migration,/partner_communication_events/);assert.match(migration,/partner_opportunities/);assert.match(migration,/partner_outreach_templates/);assert.match(sequence,/outreach_channel/);assert.match(sequence,/status='completed'/);});

test('partner V3 talent tools cover matching parsing pools submissions assessments interviews and distribution',()=>{const app=read('src/App.tsx'),layout=read('src/components/Layout.tsx'),talent=read('src/pages/PartnerTalentTools.tsx');assert.match(app,/PartnerTalentTools/);assert.match(layout,/Talent tools/);for(const text of ['Talent Match','CV parse & enrichment','Talent pools / hotlists','Professional candidate submission','Structured screening','Interview scheduling','Sourcing integrations','Job distribution'])assert.ok(talent.includes(text),text);assert.match(talent,/AI rerank/);assert.match(talent,/Add to calendar/);});

test('candidate self-service portal keeps secure token out of URL and supports profile privacy preferences',()=>{const portal=read('src/pages/CandidatePortal.tsx'),edge=read('supabase/functions/candidate-portal/index.ts');assert.match(portal,/history\.replaceState/);assert.match(portal,/Save my details/);assert.match(portal,/Recruitment updates/);assert.match(portal,/Request correction/);assert.match(edge,/update_profile/);assert.match(edge,/marketing_preference/);assert.match(edge,/linkedin/);});

test('client portal uses granular roles, vacancy requests, candidate ratings and member management',()=>{const portal=read('src/pages/ClientPortal.tsx'),detail=read('src/pages/ClientDetail.tsx'),roles=read('supabase/migrations/20260925082000_granular_client_portal_roles.sql'),ratings=read('supabase/migrations/20260925083000_client_candidate_rating_collaboration.sql');assert.match(portal,/can_review_candidates/);assert.match(portal,/can_request_vacancies/);assert.match(portal,/can_manage_members/);assert.match(portal,/Client rating/);assert.match(detail,/Client portal access/);assert.match(roles,/read_only/);assert.match(roles,/hiring_manager/);assert.match(ratings,/client_rating/);});

test('outreach sequence email steps are assigned-only suppressed-aware and idempotent',()=>{const edge=read('supabase/functions/partner-sequence-email/index.ts');assert.match(edge,/partner_outreach_enrollments/);assert.match(edge,/outreach_channel/);assert.match(edge,/b2b_call_suppressions/);assert.match(edge,/outbound_deliveries/);assert.match(edge,/partner_log_communication/);assert.match(edge,/idempotencyKey/);});

test('external recruitment providers remain truthful until configured',()=>{const talent=read('src/pages/PartnerTalentTools.tsx');assert.match(talent,/visible to Vorlen management/);assert.match(talent,/External boards require their approved credentials/);});

test('partner integration requests have a complete manager review and configuration path',()=>{const talent=read('src/pages/PartnerTalentTools.tsx'),management=read('src/pages/PartnerManagement.tsx'),migration=read('supabase/migrations/20260925171200_partner_integration_request_management.sql');assert.match(talent,/partner_request_integration_access/);assert.match(talent,/Request access/);assert.match(management,/Integration requests & provider control/);assert.match(management,/manager_integration_requests/);assert.match(management,/manager_review_integration_request/);assert.match(management,/manager_save_integration_configuration/);assert.match(management,/manager_integration_configuration/);assert.match(migration,/partner_integration_requests/);assert.match(migration,/status='fulfilled'/);assert.match(migration,/job_distribution_requests set status='requested'/);});


test('AI governance approval matches the runtime gate',()=>{const ui=read('src/pages/AiGovernance.tsx'),migration=read('supabase/migrations/20260925172500_harden_ai_governance_runtime_gate.sql');assert.match(ui,/Approved · runtime blocked/);assert.match(ui,/Solely automated significant decisions enabled/);assert.match(migration,/solely_automated_significant_decisions=false/);assert.match(migration,/not human_review_required/);assert.match(migration,/solely_automated_significant_decisions/);});


test('job start dates never send empty strings to the date column',()=>{const jobs=read('src/pages/Jobs.tsx');assert.match(jobs,/start_date:String\(form\.start_date\|\|'\'\)\.trim\(\)\|\|null/);assert.match(jobs,/Start date: .*Not specified/);});


test('job saves use backend normalization so blank date strings cannot reach date columns',()=>{const jobs=read('src/pages/Jobs.tsx'),migration=read('supabase/migrations/20260925184500_manager_save_job_blank_date_normalization.sql');assert.match(jobs,/manager_save_job/);assert.doesNotMatch(jobs,/from\('jobs'\)\.insert\(payload\)/);assert.match(migration,/p_job->>'start_date'/);assert.match(migration,/::date/);assert.match(migration,/v_start_date/);});


test('workspace users shows partner T&C and onboarding state',()=>{const settings=read('src/pages/Settings.tsx');assert.match(settings,/T&C accepted/);assert.match(settings,/T&C pending/);assert.match(settings,/Onboarding complete/);assert.match(settings,/partner_onboarding/);assert.match(settings,/partner_agreements/);});


test('direct marketing compliance fails closed for unverified prospects',()=>{const clients=read('src/pages/Clients.tsx'),detail=read('src/pages/ClientDetail.tsx'),email=read('supabase/functions/partner-client-email/index.ts'),sequence=read('supabase/functions/partner-sequence-email/index.ts'),mcp=read('supabase/functions/talentflow-mcp/index.ts'),migration=read('supabase/migrations/20260925214500_direct_marketing_compliance_gates.sql');assert.match(clients,/PECR subscriber/);assert.match(detail,/TPS\/CTPS/);assert.match(email,/Email marketing compliance has not been verified/);assert.match(sequence,/Email marketing compliance has not been verified/);assert.match(mcp,/current TPS\/CTPS screening evidence/);assert.match(migration,/tps_ctps_screened_at/);assert.match(migration,/marketing_call_consent_at/);});

test('client portal entitlement is enforced beyond the UI',()=>{const invite=read('supabase/functions/partner-client-portal-invite/index.ts'),migration=read('supabase/migrations/20260925221500_enforce_client_portal_entitlements.sql');assert.match(invite,/workspace_feature_enabled/);assert.match(invite,/client_portal/);for(const fn of ['client_create_vacancy_request','client_portal_permissions','client_portal_members','client_rate_candidate','client_admin_update_portal_member','manager_update_client_portal_member'])assert.match(migration,new RegExp(fn));assert.match(migration,/active subscription that includes the client portal/);});

test('candidate privacy and marketing preference reflect live processing',()=>{const privacy=read('src/pages/Privacy.tsx'),submit=read('supabase/functions/submit-application/index.ts');assert.match(privacy,/VERSION 25 SEPTEMBER 2026/);assert.match(privacy,/contract steps/i);assert.match(privacy,/solely automated significant recruitment decisions/i);assert.match(submit,/privacy_notice_version:'2026-09-25'/);assert.match(submit,/marketing_opt_in_at/);assert.match(submit,/marketing_opt_out_at/);});

test('production legal identity and transport security are explicit',()=>{const landing=read('src/pages/Landing.tsx'),seo=read('src/pages/SeoLanding.tsx'),terms=read('supabase/functions/client-terms/index.ts'),vercel=read('vercel.json');for(const x of [landing,seo,terms]){assert.match(x,/17387520/);assert.match(x,/10 South Street/);assert.match(x,/England and Wales/);}assert.match(vercel,/Strict-Transport-Security/);assert.match(vercel,/max-age=31536000/);});

test('live call device gateway source remains version controlled',()=>{const gateway=read('supabase/functions/vorlen-call-device/index.ts');assert.match(gateway,/x-device-code/);assert.match(gateway,/claim_gateway_call|dispatch_next_ai_dialer_call/);});


test('candidate automations use the verified production sender and opt-out footer',()=>{const ui=read('src/pages/Automations.tsx'),worker=read('supabase/functions/process-automation-queue/index.ts');assert.match(ui,/contact@vorlen\.co\.uk/);assert.match(ui,/verified production sender/);assert.match(worker,/contact@vorlen\.co\.uk/);assert.match(worker,/reply “unsubscribe”/);assert.match(worker,/10 South Street/);assert.doesNotMatch(worker,/onboarding@resend\.dev/);});


test('provider configuration uses secure credential storage rather than status prompts',()=>{const management=read('src/pages/PartnerManagement.tsx'),migration=read('supabase/migrations/20260926030500_secure_provider_configuration.sql'),required=read('supabase/migrations/20260926031500_require_provider_credentials.sql');assert.match(management,/Save app credentials/);assert.match(management,/Supabase Vault/);assert.match(management,/manager_save_integration_configuration/);assert.match(management,/manager_disconnect_recruitment_integration/);assert.doesNotMatch(management,/Provider status: connected, configuration_required/);assert.match(migration,/vault\.create_secret/);assert.match(migration,/vault\.update_secret/);assert.match(required,/API key is required for this provider/);assert.match(required,/OAuth client secret is required for this provider/);});



test('provider OAuth uses one-time state, server-held tokens and provider-correct PKCE',()=>{const edge=read('supabase/functions/provider-oauth/index.ts'),management=read('src/pages/PartnerManagement.tsx'),migration=read('supabase/migrations/20260926032500_provider_oauth_state_and_tokens.sql');assert.match(edge,/microsoft_calendar:\{mode:'pkce'/);assert.match(edge,/google_calendar:\{mode:'authorization_code'/);assert.match(edge,/linkedin:\{mode:'authorization_code'/);assert.match(edge,/code_challenge_method/);assert.match(edge,/internal_provider_oauth_consume/);assert.match(edge,/internal_provider_oauth_store_tokens/);assert.match(edge,/internal_provider_oauth_disconnect/);assert.match(edge,/Access-Control-Allow-Origin/);assert.doesNotMatch(edge,/Access-Control-Allow-Origin':'\*'/);assert.match(management,/Register this callback URI with the provider/);assert.match(management,/Test connection/);assert.match(management,/Disconnect/);assert.match(migration,/expires_at timestamptz not null default \(now\(\)\+interval '10 minutes'\)/);assert.match(migration,/vault\.create_secret/);});


test('CEO user deletion terminates partner relationship and surfaces backend detail',()=>{const admin=read('supabase/functions/admin-user-management/index.ts'),settings=read('src/pages/Settings.tsx');assert.match(admin,/status:'terminated'/);assert.match(admin,/retained audit, financial or recruitment records/);assert.match(admin,/deleteUser\(target\.id\)/);assert.match(settings,/Partner relationships will be terminated automatically/);assert.match(settings,/error\?\.context instanceof Response/);});


test('mobile workspace navigation exposes every allowed route without hidden overflow traps',()=>{const layout=read('src/components/Layout.tsx'),css=read('src/v9.css');assert.match(layout,/mobile-nav-drawer/);assert.match(layout,/mobileLinks\.map/);assert.match(layout,/mobile-menu-trigger/);assert.match(layout,/aria-label="Open workspace menu"/);assert.match(layout,/Settings/);assert.match(layout,/Sign out/);assert.doesNotMatch(css,/\.sidebar nav a:nth-child\(n\+6\)\{display:none\}/);assert.match(css,/@media\(max-width:620px\)/);assert.match(css,/\.tabs\{overflow-x:auto/);assert.match(css,/\.table-wrap\{max-width:100%;overflow-x:auto/);assert.match(css,/\.list-row\{align-items:flex-start;flex-direction:column\}/);assert.match(css,/@media\(max-width:390px\)/);});


test('mobile bottom navigation mirrors all permitted sidebar destinations',()=>{const layout=read('src/components/Layout.tsx'),css=read('src/v9.css');assert.match(layout,/mobile-bottom-nav/);assert.match(layout,/mobileLinks\.map/);assert.match(layout,/bottom-/);assert.match(layout,/Open all workspace navigation/);assert.match(layout,/dashboard\/settings/);assert.match(css,/\.mobile-bottom-scroll\{display:flex/);assert.match(css,/overflow-x:auto/);assert.doesNotMatch(css,/nth-child\(n\+6\).*display:none/);});


test('partner commission is split into evidence-backed 15 percent client and candidate components',()=>{const migration=read('supabase/migrations/20260926190000_split_partner_commission_model.sql'),management=read('src/pages/PartnerManagement.tsx'),operations=read('src/pages/PartnerOperations.tsx'),profile=read('src/pages/PartnerProfile.tsx'),onboarding=read('src/pages/PartnerOnboarding.tsx'),agreement=read('docs/RECRUITMENT-PARTNER-AGREEMENT.md');for(const x of [migration,management,operations,profile,onboarding,agreement]){assert.match(x,/15%/);}assert.match(migration,/client_commission_owner/);assert.match(migration,/candidate_commission_owner/);assert.match(migration,/commission_component/);assert.match(migration,/partner_net_fee_received/);assert.match(migration,/coalesce\(i\.amount_paid,0\)\*coalesce\(i\.subtotal,0\)\/i\.total/);assert.match(migration,/Cannot reassign % commission after it has been approved or paid/);assert.match(migration,/partner_commissions_active_component_uq/);assert.match(migration,/where status<>'void'/);assert.match(migration,/for v_attr in/);assert.match(migration,/issue_partner_commission_terms[\s\S]*security invoker/i);assert.match(migration,/commission_model='split_15_15'/);assert.match(migration,/status='superseded'/);assert.match(management,/Client Development commission/);assert.match(management,/Candidate Delivery commission/);assert.match(operations,/15% Client Development \+ 15% Candidate Delivery/);assert.match(operations,/Updated commission terms need acceptance/);assert.match(profile,/pendingAgreement/);assert.match(onboarding,/Updated partner commission terms accepted/);});

test('split commission attribution remains inside existing workspace integrity guard',()=>{const migration=read('supabase/migrations/20260926190000_split_partner_commission_model.sql');assert.match(migration,/enforce_partner_attribution_scope/);assert.match(migration,/client_commission_owner/);assert.match(migration,/candidate_commission_owner/);assert.match(migration,/placement_id is not null/);assert.match(migration,/Partner attribution must belong to the same workspace/);});


test('partner split commission terms are production-complete and legally identified',()=>{const terms=read('docs/RECRUITMENT-PARTNER-AGREEMENT.md'),hardening=read('supabase/migrations/20260926191500_harden_split_partner_commission_terms.sql');for(const x of [terms,hardening]){assert.match(x,/Ivy and Pearls Ltd trading as Vorlen/);assert.match(x,/17387520/);assert.match(x,/10 South Street/);assert.match(x,/15% Client Development/);assert.match(x,/15% Candidate Delivery/);assert.match(x,/6 months after it ends/);assert.match(x,/7 days/);}assert.doesNotMatch(terms,/\[legal entity|\[6\]|\[7\]|insert schedule/i);assert.match(hardening,/partner-2026-09-26-split-v2/);});

test('partner agreement RPCs fail closed for terminated partners and use private privileged implementations',()=>{const hardening=read('supabase/migrations/20260926191500_harden_split_partner_commission_terms.sql');assert.match(hardening,/suspended or terminated partner/);assert.match(hardening,/A suspended or terminated partner cannot accept new agreement terms/);assert.match(hardening,/private\.accept_partner_agreement_impl/);assert.match(hardening,/private\.attribute_partner_entity_impl/);assert.match(hardening,/create or replace function public\.accept_partner_agreement[\s\S]*security invoker/i);assert.match(hardening,/create or replace function public\.attribute_partner_entity[\s\S]*security invoker/i);});

test('commission-side attribution is constrained by partner capability',()=>{const hardening=read('supabase/migrations/20260926191500_harden_split_partner_commission_terms.sql'),management=read('src/pages/PartnerManagement.tsx');assert.match(hardening,/Client Development commission requires a client-capable partner specialism/);assert.match(hardening,/Candidate Delivery commission requires a candidate-sourcing partner specialism/);assert.match(management,/clientCapable&&splitTermsAccepted&&<option value="client_commission_owner"/);assert.match(management,/candidateCapable&&splitTermsAccepted&&<option value="candidate_commission_owner"/);});

test('termination preserves pre-termination commission rights but blocks new activity',()=>{const migration=read('supabase/migrations/20260926193000_preserve_pretermination_commission_rights.sql'),terms=read('docs/RECRUITMENT-PARTNER-AGREEMENT.md');assert.match(migration,/terminated_at timestamptz/);assert.match(migration,/v_attributed_at<=o\.terminated_at/);assert.match(migration,/a\.status='terminated'/);assert.match(migration,/set status='terminated',terminated_at=now\(\)/);assert.match(terms,/later qualifying client receipts for that pre-termination placement remain eligible/);assert.match(terms,/No commission is earned for post-termination activity/);});

test('partner management and settings expose latest split T&C lifecycle truthfully',()=>{const management=read('src/pages/PartnerManagement.tsx'),settings=read('src/pages/Settings.tsx'),onboarding=read('src/pages/PartnerOnboarding.tsx');assert.match(management,/Partner T&C \/ commission terms/);assert.match(management,/Issue latest terms/);assert.match(management,/15% Client \+ 15% Candidate/);assert.match(settings,/Updated T&C pending/);assert.match(settings,/current accepted/);assert.match(settings,/T&C terminated/);assert.match(onboarding,/Print \/ save terms/);});


test('commission ownership requires accepted split-v2 terms',()=>{const migration=read('supabase/migrations/20260926194000_require_split_terms_for_commission_attribution.sql'),management=read('src/pages/PartnerManagement.tsx');assert.match(migration,/partner-2026-09-26-split-v2/);assert.match(migration,/accepted_terms_hash=a\.terms_hash/);assert.match(migration,/Partner must accept the latest split-commission terms before commission ownership can be assigned/);assert.match(management,/splitTermsAccepted/);assert.match(management,/Updated commission terms not yet accepted/);assert.match(management,/15% commission ownership cannot be assigned until this partner accepts split-v2/);});


test('partner candidate sourcing exposes secure CV upload where candidates are created',()=>{const page=read('src/pages/PartnerClients.tsx'),fn=read('supabase/functions/partner-candidate-cv/index.ts');assert.match(page,/Candidate CV \(optional\)/);assert.match(page,/Add candidate'\+\(sourceCvFile\?' \+ CV'/);assert.match(page,/Upload CV/);assert.match(page,/Replace CV/);assert.match(page,/PDF or DOCX · maximum 5 MB/);assert.match(page,/source_evidence/);assert.match(page,/partner-candidate-cv/);assert.match(page,/partner_candidate_pipeline/);assert.match(page,/Assigned vacancy \(optional\)/);assert.match(fn,/5\*1024\*1024/);assert.match(fn,/does not appear to be a valid/);assert.match(fn,/candidate_cv_previous_file_cleanup_failed/);assert.doesNotMatch(fn,/Access-Control-Allow-Origin':'\*'/);});

test('partner CV upload remains capability, assignment and processing gated',()=>{const fn=read('supabase/functions/partner-candidate-cv/index.ts');assert.match(fn,/profile\.role!=='partner'/);assert.match(fn,/candidate_sourcer','hybrid/);assert.match(fn,/Candidate processing is not active/);assert.match(fn,/Assigned candidate access required/);assert.match(fn,/Record how the candidate provided or authorised this CV/);assert.match(fn,/Only PDF or DOCX CV files are supported/);assert.match(fn,/partner_cv_uploaded/);assert.match(fn,/candidate_source_records/);});


test('partner applications are assignment-scoped and capability-gated',()=>{const app=read('src/App.tsx'),layout=read('src/components/Layout.tsx'),page=read('src/pages/PartnerApplications.tsx'),edge=read('supabase/functions/partner-applications-list/index.ts');assert.match(app,/partner\/applications/);assert.match(app,/PartnerCapabilityGate kind="candidate"/);assert.match(layout,/\/dashboard\/partner\/applications/);assert.match(page,/Other partners' recruitment records are not exposed/);assert.match(page,/candidateProcessingActive/);assert.match(edge,/partner_assignments/);assert.match(edge,/completed_at/);assert.match(edge,/candidate_sourcer/);assert.match(edge,/hybrid/);assert.doesNotMatch(edge,/cover_note|answers/);assert.match(edge,/candidate_and_vacancy/);});


test('candidate removal uses audited erasure rather than raw hard delete',()=>{const api=read('src/lib/api.ts'),page=read('src/pages/Candidates.tsx'),edge=read('supabase/functions/manager-candidate-erasure/index.ts');assert.match(api,/manager-candidate-erasure/);assert.doesNotMatch(api,/from\('candidates'\)\.delete/);assert.match(api,/is\('erased_at',null\)/);assert.match(page,/required audit, placement and attribution history is retained/);assert.match(edge,/privacy_requests/);assert.match(edge,/candidate_privacy_files/);assert.match(edge,/candidate_privacy_operation/);assert.match(edge,/statutory_retain_until/);assert.match(edge,/Manager access required/);});

test('partner candidate workspace covers delivery from sourcing through interview outcomes',()=>{const app=read('src/App.tsx'),list=read('src/pages/PartnerClients.tsx'),page=read('src/pages/PartnerCandidateWorkspace.tsx'),edge=read('supabase/functions/partner-candidate-workspace/index.ts');assert.match(app,/partner\/candidates\/:id/);assert.match(list,/Open candidate workspace/);for(const x of ['Applications & client submissions','Interviews','Candidate communication & updates','My candidate tasks','Candidate timeline'])assert.ok(page.includes(x),x);assert.match(edge,/partner_assignments/);assert.match(edge,/candidate_sourcer/);assert.match(edge,/manage_interview/);assert.match(edge,/log_event/);assert.match(edge,/candidate_submissions/);});
test('partner placement visibility supports split commission ownership',()=>{const migration=read('supabase/migrations/20260926212646_partner_placement_visibility_for_split_commission.sql');assert.match(migration,/client_commission_owner/);assert.match(migration,/candidate_commission_owner/);assert.match(migration,/placement_owner/);});

test('partner candidate portfolio excludes erased candidates',()=>{const s=read('src/pages/PartnerClients.tsx');assert.match(s,/from\('candidates'\).*is\('erased_at',null\)/);});

test('partner offer to placement bridge is explicit and manager controlled',()=>{const page=read('src/pages/PartnerCandidateWorkspace.tsx'),edge=read('supabase/functions/partner-candidate-workspace/index.ts'),manager=read('src/pages/PartnerManagement.tsx'),migration=read('supabase/migrations/20260926214107_partner_offer_and_placement_request_workflow.sql');assert.match(page,/Offer → placement/);assert.match(page,/Placement & aftercare/);assert.match(page,/Post-placement aftercare/);assert.match(edge,/upsert_offer/);assert.match(edge,/A client submission must exist before an offer can be recorded/);assert.match(edge,/placement_review_status/);assert.match(manager,/Offer & placement requests/);assert.match(manager,/Record the placement in Commercial first/);assert.match(migration,/partner_candidate_offers/);});

test('lead closer sees only official submitted candidates without candidate PII',()=>{const edge=read('supabase/functions/partner-applications-list/index.ts'),app=read('src/App.tsx'),layout=read('src/components/Layout.tsx'),page=read('src/pages/PartnerApplications.tsx');assert.match(edge,/lead_closer/);assert.match(edge,/candidate_submissions/);assert.match(edge,/client_submission/);assert.match(edge,/full_name:c\.full_name/);assert.match(app,/kind="delivery"/);assert.match(layout,/partnerCanCloseClients\|\|access\.partnerCanSourceCandidates/);assert.match(page,/Official submission on your vacancy/);});
test('placement finalisation carries verified commission ownership and aftercare',()=>{const a=read('supabase/migrations/20260926222700_finalise_partner_placement_workflow.sql'),b=read('supabase/migrations/20260926222746_tighten_partner_placement_finalisation.sql');const s=a+'\n'+b;assert.match(s,/client_commission_owner/);assert.match(s,/candidate_commission_owner/);assert.match(s,/partner_candidate_offers/);assert.match(s,/Candidate first-week aftercare/);assert.match(s,/Client first-week placement aftercare/);assert.match(b,/lead_closer','hybrid/);});

test('ambiguous client contribution is not auto-awarded and is surfaced for review',()=>{const migration=read('supabase/migrations/20260926223110_require_end_to_end_client_evidence_for_auto_commission.sql'),manager=read('src/pages/PartnerManagement.tsx');assert.match(migration,/co\.partner_id=vo\.partner_id/);assert.match(migration,/client_originator/);assert.match(migration,/vacancy_originator/);assert.match(manager,/Commission ownership review needed/);assert.match(manager,/missing Client Development 15%/);});

test('lead closer application view excludes internal submission drafts',()=>{const edge=read('supabase/functions/partner-applications-list/index.ts');assert.match(edge,/candidate_submissions/);assert.match(edge,/\['submitted','reviewing','approved','rejected','interview_requested'\]/);assert.doesNotMatch(edge,/\['draft','reserved'/);});
