import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
test('billing uses canonical production invoice tables',()=>{const s=read('src/pages/Billing.tsx');assert.match(s,/from\('invoices'\)/);assert.match(s,/from\('invoice_payments'\)/);assert.doesNotMatch(s,/client_invoices/);});
test('public auth routes are noindex and recovery uses the Vorlen recovery edge flow',()=>{const app=read('src/App.tsx'),recovery=read('src/pages/PasswordRecovery.tsx'),confirm=read('src/pages/AuthConfirm.tsx'),edge=read('supabase/functions/password-recovery/index.ts');assert.match(app,/forgot-password/);assert.match(app,/reset-password/);assert.match(app,/auth\/confirm/);assert.match(recovery,/functions\.invoke\('password-recovery'/);assert.doesNotMatch(recovery,/resetPasswordForEmail/);assert.match(recovery,/updateUser\(\{password\}\)/);assert.match(recovery,/robots:noIndex/);assert.match(confirm,/verifyOtp/);assert.match(edge,/https:\/\/www\.vorlen\.co\.uk\/auth\/confirm/);});
test('private workspace has a noindex SEO guard',()=>{const s=read('src/App.tsx');assert.match(s,/PrivateSeo/);assert.match(s,/robots:noIndex/);assert.match(s,/path="\/dashboard\/\*"/);});
test('careers uses canonical published job fields',()=>{const api=read('src/lib/api.ts'),home=read('src/pages/CareersHome.tsx');assert.match(api,/commission_text/);assert.doesNotMatch(api,/updated_at/);assert.match(home,/eq\('status','published'\)/);assert.match(home,/setSeo/);});
test('browser production env contains no obvious server secrets',()=>{const s=read('.env.production');for(const key of ['SERVICE_ROLE','STRIPE_SECRET','WEBHOOK_SECRET','AI_API_KEY','RESEND_API_KEY','TWILIO_AUTH'])assert.doesNotMatch(s,new RegExp(key));});
test('subscription features are gated in the application router',()=>{const app=read('src/App.tsx'),access=read('src/lib/access.ts');assert.match(app,/AccessGate kind="automations"/);assert.match(app,/AccessGate kind="billing"/);assert.match(app,/AccessGate kind="manage"/);assert.match(access,/features\.automations===true/);assert.match(access,/features\.ai_screening===true/);});
test('the application has a top-level render recovery boundary',()=>{const main=read('src/main.tsx'),boundary=read('src/components/ErrorBoundary.tsx');assert.match(main,/ErrorBoundary/);assert.match(boundary,/componentDidCatch/);assert.match(boundary,/Your data has not been changed/);});

test('candidate progress portal controls cannot regress out of recruiter workspace',()=>{const s=read('src/pages/RecruiterWorkspace.tsx'),portal=read('src/pages/CandidatePortal.tsx');assert.match(s,/Candidate portal/);assert.match(s,/create_candidate_portal_token/);assert.match(s,/get_candidate_portal_token/);assert.match(s,/revoke_candidate_portal_token/);assert.match(s,/Generate 30-day link/);assert.match(s,/Copy link/);assert.match(s,/Open portal/);assert.match(s,/Refresh link/);assert.match(s,/Revoke/);assert.match(portal,/Private application workspace/);assert.match(portal,/YOUR APPLICATIONS/);assert.match(portal,/Request my data/);assert.match(portal,/Request erasure/);});

test('dashboard native form controls use the global Vorlen control system',()=>{const s=read('src/dashboard-fixes.css');assert.match(s,/\.app-shell input:not/);assert.match(s,/\.app-shell select/);assert.match(s,/\.app-shell textarea/);assert.match(s,/workspace-portal>label input/);assert.match(s,/list-row \.button-row select/);});
test('automation E2E contract requires create activate and queue verification',()=>{const s=read('src/pages/Automations.tsx');assert.match(s,/New sequence/);assert.match(s,/Save sequence/);assert.match(s,/Activate/);assert.match(s,/Automation queue/);assert.match(s,/automation_enrollments_candidate_id_fkey/);assert.match(s,/automation_enrollments_sequence_id_fkey/);});

test('partner workspace keeps client calling CRM capabilities',()=>{const s=read('src/pages/PartnerClients.tsx');for(const x of ['No answer','Contacted','Busy','Call back','Send more info','Interested','Follow up','Meeting booked','Not interested','Do not contact','Send follow-up email','AI call preparation','Callback'])assert.match(s,new RegExp(x));assert.match(s,/partner_client_activity/);assert.match(s,/partner_client_notes/);assert.match(s,/client-ai-brief/);assert.match(s,/partner-client-email/);});
test('partner accounts are isolated to dedicated workspace navigation',()=>{const s=read('src/components/Layout.tsx'),a=read('src/App.tsx'),settings=read('src/pages/Settings.tsx');assert.match(s,/role==='partner'/);assert.match(s,/\/dashboard\/partner/);assert.match(a,/PartnerClients/);assert.match(settings,/value="partner"/);});

test('workspace invitation flow always returns invited users to Vorlen and routes partners correctly',()=>{const admin=read('supabase/functions/admin-user-management/index.ts'),reset=read('src/pages/PasswordRecovery.tsx'),login=read('src/pages/Login.tsx');assert.match(admin,/https:\/\/www\.vorlen\.co\.uk/);assert.doesNotMatch(admin,/talentflow-nu-neon\.vercel\.app|talentflow\.vercel\.app/);assert.match(admin,/\/reset-password/);assert.match(reset,/role==='partner'.*\/dashboard\/partner/);assert.match(login,/role==='partner'.*\/dashboard\/partner/);});

test('send more info outcome requires the company brochure attachment',()=>{const s=read('supabase/functions/partner-client-email/index.ts');assert.match(s,/send_more_info/);assert.match(s,/COMPANY_BROCHURE_BUCKET/);assert.match(s,/COMPANY_BROCHURE_PATH/);assert.match(s,/attachments/);assert.match(s,/Vorlen-Company-Brochure\.pdf/);assert.match(s,/PDFDocument/);});

test('landing page contains no legacy TalentFlow customer branding',()=>{const s=read('src/pages/Landing.tsx');assert.doesNotMatch(s,/TALENTFLOW/);});
test('partner sourcing UI blocks non-sourcing partner profiles',()=>{const s=read('src/pages/PartnerClients.tsx');assert.match(s,/candidate_sourcer/);assert.match(s,/hybrid/);assert.match(s,/Add candidate/);assert.match(s,/Candidate creation is only available/);});
test('post-call follow-up task errors are surfaced',()=>{const s=read('src/pages/PartnerClients.tsx');assert.match(s,/follow-up task could not be created/);});

test('invite-only access has no self-service workspace creation path',()=>{const app=read('src/App.tsx'),login=read('src/pages/Login.tsx'),seo=read('scripts/seo-build.mjs');assert.doesNotMatch(app,/pages\/Onboarding|path="\/onboarding"/);assert.doesNotMatch(login,/nav\('\/onboarding'\)/);assert.match(login,/does not have access to a Vorlen workspace/);assert.doesNotMatch(seo,/Disallow: \/signup|Disallow: \/onboarding/);});


test('role routing keeps client users and partners out of staff workspaces',()=>{const app=read('src/App.tsx'),layout=read('src/components/Layout.tsx');assert.match(app,/RoleGate roles=\{\['viewer'\]\}/);assert.match(app,/RoleGate roles=\{\['partner'\]\}/);assert.match(app,/roles=\{\['owner','manager','recruiter'\]\}/);assert.match(layout,/role==='viewer'.*\/client/);assert.match(layout,/recruiterRoutes/);});

test('recruiters have operational navigation without management surfaces',()=>{const layout=read('src/components/Layout.tsx'),jobs=read('src/pages/Jobs.tsx');for(const route of ['/dashboard/jobs','/dashboard/candidates','/dashboard/pipeline','/dashboard/applications','/dashboard/interviews'])assert.match(layout,new RegExp(route.replaceAll('/','\\/')));assert.match(jobs,/Recruiter access is read-only here/);assert.match(jobs,/canManage/);});

test('client candidate review does not expose raw LinkedIn or direct CV URLs',()=>{const portal=read('src/pages/ClientPortal.tsx'),safe=read('src/pages/ClientSafeCv.tsx'),edge=read('supabase/functions/client-candidate-cv/index.ts'),review=read('supabase/functions/client-submission-review/index.ts');assert.doesNotMatch(portal,/linkedin_url|View LinkedIn/);assert.match(portal,/Open client-safe CV/);assert.match(safe,/Direct email, phone, postal address and personal profile links/);assert.match(edge,/\[email withheld by Vorlen\]/);assert.match(edge,/\[phone withheld by Vorlen\]/);assert.doesNotMatch(edge,/createSignedUrl/);assert.doesNotMatch(review,/cv_url:cvUrl|createSignedUrl/);});


test('partner V3 exposes account CRM, unified timeline, deal pipeline and outreach sequencing',()=>{const app=read('src/App.tsx'),layout=read('src/components/Layout.tsx'),crm=read('src/pages/PartnerCRM.tsx'),migration=read('supabase/migrations/20260925063000_partner_platform_v3_foundation.sql'),sequence=read('supabase/migrations/20260925081000_complete_partner_outreach_sequence_lifecycle.sql');assert.match(app,/PartnerCRM/);assert.match(layout,/Account CRM/);assert.match(crm,/ACCOUNT CRM/);assert.match(crm,/Unified account timeline/);assert.match(crm,/Deals \/ opportunities/);assert.match(crm,/Outreach sequences/);assert.match(migration,/partner_communication_events/);assert.match(migration,/partner_opportunities/);assert.match(migration,/partner_outreach_templates/);assert.match(sequence,/outreach_channel/);assert.match(sequence,/status='completed'/);});

test('partner V3 talent tools cover matching parsing pools submissions assessments interviews and distribution',()=>{const app=read('src/App.tsx'),layout=read('src/components/Layout.tsx'),talent=read('src/pages/PartnerTalentTools.tsx');assert.match(app,/PartnerTalentTools/);assert.match(layout,/Talent tools/);for(const text of ['Talent Match','CV parse & enrichment','Talent pools / hotlists','Professional candidate submission','Structured screening','Interview scheduling','Sourcing integrations','Job distribution'])assert.ok(talent.includes(text),text);assert.match(talent,/AI rerank/);assert.match(talent,/Add to calendar/);});

test('candidate self-service portal keeps secure token out of URL and supports profile privacy preferences',()=>{const portal=read('src/pages/CandidatePortal.tsx'),edge=read('supabase/functions/candidate-portal/index.ts');assert.match(portal,/history\.replaceState/);assert.match(portal,/Save my details/);assert.match(portal,/Recruitment updates/);assert.match(portal,/Request correction/);assert.match(edge,/update_profile/);assert.match(edge,/marketing_preference/);assert.match(edge,/linkedin/);});

test('client portal uses granular roles, vacancy requests, candidate ratings and member management',()=>{const portal=read('src/pages/ClientPortal.tsx'),detail=read('src/pages/ClientDetail.tsx'),roles=read('supabase/migrations/20260925082000_granular_client_portal_roles.sql'),ratings=read('supabase/migrations/20260925083000_client_candidate_rating_collaboration.sql');assert.match(portal,/can_review_candidates/);assert.match(portal,/can_request_vacancies/);assert.match(portal,/can_manage_members/);assert.match(portal,/Client rating/);assert.match(detail,/Client portal access/);assert.match(roles,/read_only/);assert.match(roles,/hiring_manager/);assert.match(ratings,/client_rating/);});

test('outreach sequence email steps are assigned-only suppressed-aware and idempotent',()=>{const edge=read('supabase/functions/partner-sequence-email/index.ts');assert.match(edge,/partner_outreach_enrollments/);assert.match(edge,/outreach_channel/);assert.match(edge,/b2b_call_suppressions/);assert.match(edge,/outbound_deliveries/);assert.match(edge,/partner_log_communication/);assert.match(edge,/idempotencyKey/);});

test('external recruitment providers remain truthful until configured',()=>{const talent=read('src/pages/PartnerTalentTools.tsx');assert.match(talent,/visible to Vorlen management/);assert.match(talent,/External boards require their approved credentials/);});

test('partner integration requests have a complete manager review and configuration path',()=>{const talent=read('src/pages/PartnerTalentTools.tsx'),management=read('src/pages/PartnerManagement.tsx'),migration=read('supabase/migrations/20260925171200_partner_integration_request_management.sql');assert.match(talent,/partner_request_integration_access/);assert.match(talent,/Request access/);assert.match(management,/Integration requests & provider control/);assert.match(management,/manager_integration_requests/);assert.match(management,/manager_review_integration_request/);assert.match(management,/manager_update_recruitment_integration/);assert.match(migration,/partner_integration_requests/);assert.match(migration,/status='fulfilled'/);assert.match(migration,/job_distribution_requests set status='requested'/);});


test('AI governance approval matches the runtime gate',()=>{const ui=read('src/pages/AiGovernance.tsx'),migration=read('supabase/migrations/20260925172500_harden_ai_governance_runtime_gate.sql');assert.match(ui,/Approved · runtime blocked/);assert.match(ui,/Solely automated significant decisions enabled/);assert.match(migration,/solely_automated_significant_decisions=false/);assert.match(migration,/not human_review_required/);assert.match(migration,/solely_automated_significant_decisions/);});


test('job start dates never send empty strings to the date column',()=>{const jobs=read('src/pages/Jobs.tsx');assert.match(jobs,/start_date:String\(form\.start_date\|\|'\'\)\.trim\(\)\|\|null/);assert.match(jobs,/Start date: .*Not specified/);});


test('job saves use backend normalization so blank date strings cannot reach date columns',()=>{const jobs=read('src/pages/Jobs.tsx'),migration=read('supabase/migrations/20260925184500_manager_save_job_blank_date_normalization.sql');assert.match(jobs,/manager_save_job/);assert.doesNotMatch(jobs,/from\('jobs'\)\.insert\(payload\)/);assert.match(migration,/p_job->>'start_date'/);assert.match(migration,/::date/);assert.match(migration,/v_start_date/);});


test('workspace users shows partner T&C and onboarding state',()=>{const settings=read('src/pages/Settings.tsx');assert.match(settings,/T&C accepted/);assert.match(settings,/T&C pending/);assert.match(settings,/Onboarding complete/);assert.match(settings,/partner_onboarding/);assert.match(settings,/partner_agreements/);});
