import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
test('billing uses canonical production invoice tables',()=>{const s=read('src/pages/Billing.tsx');assert.match(s,/from\('invoices'\)/);assert.match(s,/from\('invoice_payments'\)/);assert.doesNotMatch(s,/client_invoices/);});
test('public auth routes are noindex and recovery is complete',()=>{const app=read('src/App.tsx'),recovery=read('src/pages/PasswordRecovery.tsx');assert.match(app,/forgot-password/);assert.match(app,/reset-password/);assert.match(recovery,/resetPasswordForEmail/);assert.match(recovery,/updateUser\(\{password\}\)/);assert.match(recovery,/robots:noIndex/);});
test('private workspace has a noindex SEO guard',()=>{const s=read('src/App.tsx');assert.match(s,/PrivateSeo/);assert.match(s,/robots:noIndex/);assert.match(s,/path="\/dashboard\/\*"/);});
test('careers uses canonical published job fields',()=>{const api=read('src/lib/api.ts'),home=read('src/pages/CareersHome.tsx');assert.match(api,/commission_text/);assert.doesNotMatch(api,/updated_at/);assert.match(home,/eq\('status','published'\)/);assert.match(home,/setSeo/);});
test('browser production env contains no obvious server secrets',()=>{const s=read('.env.production');for(const key of ['SERVICE_ROLE','STRIPE_SECRET','WEBHOOK_SECRET','AI_API_KEY','RESEND_API_KEY','TWILIO_AUTH'])assert.doesNotMatch(s,new RegExp(key));});
test('subscription features are gated in the application router',()=>{const app=read('src/App.tsx'),access=read('src/lib/access.ts');assert.match(app,/AccessGate kind="automations"/);assert.match(app,/AccessGate kind="billing"/);assert.match(app,/AccessGate kind="manage"/);assert.match(access,/features\.automations===true/);assert.match(access,/features\.ai_screening===true/);});
test('the application has a top-level render recovery boundary',()=>{const main=read('src/main.tsx'),boundary=read('src/components/ErrorBoundary.tsx');assert.match(main,/ErrorBoundary/);assert.match(boundary,/componentDidCatch/);assert.match(boundary,/Your data has not been changed/);});

test('candidate progress portal controls cannot regress out of recruiter workspace',()=>{const s=read('src/pages/RecruiterWorkspace.tsx'),portal=read('src/pages/CandidatePortal.tsx');assert.match(s,/Candidate portal/);assert.match(s,/create_candidate_portal_token/);assert.match(s,/get_candidate_portal_token/);assert.match(s,/revoke_candidate_portal_token/);assert.match(s,/Generate 30-day link/);assert.match(s,/Copy link/);assert.match(s,/Open portal/);assert.match(s,/Refresh link/);assert.match(s,/Revoke/);assert.match(portal,/Track your recruitment activity and upcoming interviews/);});

test('dashboard native form controls use the global TalentFlow control system',()=>{const s=read('src/dashboard-fixes.css');assert.match(s,/\.app-shell input:not/);assert.match(s,/\.app-shell select/);assert.match(s,/\.app-shell textarea/);assert.match(s,/workspace-portal>label input/);assert.match(s,/list-row \.button-row select/);});
test('automation E2E contract requires create activate and queue verification',()=>{const s=read('src/pages/Automations.tsx');assert.match(s,/New sequence/);assert.match(s,/Save sequence/);assert.match(s,/Activate/);assert.match(s,/Automation queue/);assert.match(s,/automation_enrollments_candidate_id_fkey/);assert.match(s,/automation_enrollments_sequence_id_fkey/);});

test('partner workspace keeps client calling CRM capabilities',()=>{const s=read('src/pages/PartnerClients.tsx');for(const x of ['No answer','Contacted','Busy','Call back','Interested','Follow up','Meeting booked','Not interested','Do not contact','Email client about this contact','AI company brief','Callback date & time'])assert.match(s,new RegExp(x));assert.match(s,/partner_client_activity/);assert.match(s,/partner_client_notes/);assert.match(s,/client-ai-brief/);assert.match(s,/partner-client-email/);});
test('partner accounts are isolated to dedicated workspace navigation',()=>{const s=read('src/components/Layout.tsx'),a=read('src/App.tsx'),settings=read('src/pages/Settings.tsx');assert.match(s,/role==='partner'/);assert.match(s,/\/dashboard\/partner/);assert.match(a,/PartnerClients/);assert.match(settings,/value="partner"/);});

test('workspace invitation flow always returns invited users to TalentFlow and routes partners correctly',()=>{const admin=read('supabase/functions/admin-user-management/index.ts'),reset=read('src/pages/PasswordRecovery.tsx'),login=read('src/pages/Login.tsx');assert.match(admin,/talentflow-nu-neon\\.vercel\\.app/);assert.match(admin,/\/reset-password/);assert.match(reset,/role==='partner'.*\/dashboard\/partner/);assert.match(login,/role==='partner'.*\/dashboard\/partner/);});
