import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
 const udb=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:{user}}=await udb.auth.getUser();if(!user)return json({error:'Authentication required'},401);
 const{data:p}=await udb.from('profiles').select('company_id,role').eq('id',user.id).single();if(!p||!['partner','owner','manager'].includes(p.role))return json({error:'Workspace access required'},403);
 const b=await req.json(),db=createClient(url,service);if(p.role==='partner'){const{data:active}=await udb.rpc('partner_is_active');if(active!==true)return json({error:'Partner activation required'},403);const{data:assignment}=await db.from('partner_assignments').select('id').eq('company_id',p.company_id).eq('partner_id',user.id).eq('client_id',b.client_id).is('completed_at',null).maybeSingle();if(!assignment)return json({error:'This client is not assigned to your partner portfolio'},403);}
 const[{data:c},{data:a},{data:n},{data:brief}]=await Promise.all([
  db.from('clients').select('id,company_name,contact_name,email,phone,website,status').eq('id',b.client_id).eq('company_id',p.company_id).single(),
  db.from('partner_client_activity').select('status,callback_at,last_contacted_at').eq('client_id',b.client_id).eq('company_id',p.company_id).eq('partner_id',user.id).maybeSingle(),
  db.from('partner_client_notes').select('note,created_at').eq('client_id',b.client_id).eq('company_id',p.company_id).order('created_at',{ascending:false}).limit(8),
  db.from('client_ai_briefs').select('sector,summary,talking_points,likely_needs,questions_to_ask').eq('client_id',b.client_id).eq('company_id',p.company_id).maybeSingle()
 ]);if(!c)return json({error:'Client not found'},404);if(b.viewed_company_name&&String(b.viewed_company_name)!==c.company_name)return json({error:'Client context changed. Reopen the client and try again.'},409);
 const key=Deno.env.get('AI_API_KEY')||Deno.env.get('OPENAI_API_KEY'),model=Deno.env.get('AI_MODEL')||Deno.env.get('OPENAI_MODEL'),base=(Deno.env.get('AI_BASE_URL')||'https://api.openai.com/v1').replace(/\/+$/,'');if(!key||!model)return json({error:'AI provider is not configured'},503);
 const context={active_company:{id:c.id,name:c.company_name,contact_name:c.contact_name,website:c.website},client:c,current_status:b.status||a?.status||'not_contacted',activity:a,notes:n||[],company_brief:brief,user_question:String(b.question||'').slice(0,2000)};
 const prompt='You are the in-call B2B recruitment sales copilot for Vorlen. You are currently assisting the partner specifically with '+c.company_name+'. Every answer must be about this active company and its contact/context unless the partner explicitly asks for general advice. Never mix context from another client.  Help the human partner have a useful, respectful business conversation. Never invent facts. Do not pretend the prospect said something not in context. Give concise language the partner can actually say aloud. If handling an objection, acknowledge it and ask a low-pressure discovery question. Partners may discuss hiring needs and gather commercial information, but they have no authority to quote, agree, accept or vary recruitment fees, payment terms, rebates, guarantees, exclusivity, candidate-ownership periods or any other binding client term. If a prospect asks for or proposes commercial terms, tell the partner to capture the request and escalate it to an authorised Vorlen manager; never script language that accepts or binds Vorlen. If the user supplies a post-call debrief, additionally infer only from that debrief: suggested_status (one of not_contacted,no_answer,contacted,busy,call_back,send_more_info,interested,follow_up,meeting_booked,not_interested,do_not_contact), crm_note, next_action, callback_at (ISO string only when clearly stated, otherwise empty), follow_up_email_subject, follow_up_email_body. Return strict JSON with recommended_action:string, suggested_words:string (max 80 words), follow_up_question:string, signals_to_capture:string[], suggested_status:string, crm_note:string, next_action:string, callback_at:string, follow_up_email_subject:string, follow_up_email_body:string. Context: '+JSON.stringify(context);
 const r=await fetch(base+'/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:'You are a factual B2B recruitment call copilot. Return strict JSON only.'},{role:'user',content:prompt}],response_format:{type:'json_object'},temperature:.25})});if(!r.ok)return json({error:'AI provider request failed'},502);
 const raw=await r.json(),x=JSON.parse(raw?.choices?.[0]?.message?.content||'{}');return json({recommended_action:String(x.recommended_action||'Clarify the client need.'),suggested_words:String(x.suggested_words||''),follow_up_question:String(x.follow_up_question||''),signals_to_capture:Array.isArray(x.signals_to_capture)?x.signals_to_capture.slice(0,8):[],suggested_status:['not_contacted','no_answer','contacted','busy','call_back','send_more_info','interested','follow_up','meeting_booked','not_interested','do_not_contact'].includes(String(x.suggested_status||''))?String(x.suggested_status):'',crm_note:String(x.crm_note||''),next_action:String(x.next_action||''),callback_at:String(x.callback_at||''),follow_up_email_subject:String(x.follow_up_email_subject||''),follow_up_email_body:String(x.follow_up_email_body||'')});
}catch(e){return json({error:e instanceof Error?e.message:'AI coach failed'},500)}});