import {useEffect,useState} from 'react';
import {BrainCircuit,Clock3,Mail,MessageSquare,Plus,Power,Send} from 'lucide-react';
import {Card,Badge,Button,Empty} from '../components/Ui';
import {supabase} from '../lib/supabase';
const channels=['email','sms','whatsapp'];
type Step={delay_hours:number;subject:string;body:string};
const blankStep=():Step=>({delay_hours:0,subject:'',body:''});
export default function Automations(){const [rows,setRows]=useState<any[]>([]),[show,setShow]=useState(false),[enrolments,setEnrolments]=useState<any[]>([]),[f,setF]=useState<any>({name:'',trigger_event:'application_received',channel:'email',provider:'Resend',active:false,from_name:'',from_address:'',template_id:'',steps:[{delay_hours:0,subject:'Thanks for applying',body:'Hi {{first_name}},\n\nThanks for applying for {{job_title}}. Our recruitment team will review your application and be in touch.'}]});
 const load=async()=>{const [s,e]=await Promise.all([supabase.from('automation_sequences').select('*').order('created_at',{ascending:false}),supabase.from('automation_enrollments').select('*, candidates(full_name,email), automation_sequences(name)').order('next_run_at').limit(30)]);setRows(s.data||[]);setEnrolments(e.data||[])};useEffect(()=>{load()},[]);
 async function save(e:any){e.preventDefault();const payload={...f,steps:f.steps.map((x:Step)=>({...x,delay_hours:Number(x.delay_hours||0)}))};const {error}=await supabase.from('automation_sequences').insert(payload);if(error)alert(error.message);else{setShow(false);load()}}
 async function toggle(x:any){await supabase.from('automation_sequences').update({active:!x.active,updated_at:new Date().toISOString()}).eq('id',x.id);load()}
 const Icon=({channel}:{channel:string})=>channel==='email'?<Mail size={20}/>:<MessageSquare size={20}/>;
 return <div className="page"><div className="page-actions"><div><h2>Automations</h2><p>Candidate nurture sequences. Active application sequences are automatically queued after new applications.</p></div><Button onClick={()=>setShow(true)}><Plus size={17}/> New sequence</Button></div>
 {show&&<Card className="form-card"><form onSubmit={save} className="form-grid"><label>Name<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Trigger<select value={f.trigger_event} onChange={e=>setF({...f,trigger_event:e.target.value})}><option value="application_received">Application received</option><option value="candidate_qualified">Candidate qualified</option><option value="interview_scheduled">Interview scheduled</option><option value="candidate_inactive">Candidate inactive</option><option value="placement_created">Placement created</option></select></label><label>Channel<select value={f.channel} onChange={e=>setF({...f,channel:e.target.value})}>{channels.map(x=><option key={x}>{x}</option>)}</select></label><label>Provider<input value={f.provider} onChange={e=>setF({...f,provider:e.target.value})}/></label><label>From name<input value={f.from_name} onChange={e=>setF({...f,from_name:e.target.value})}/></label><label>From address<input type="email" value={f.from_address} onChange={e=>setF({...f,from_address:e.target.value})}/></label><label>Provider template ID<input value={f.template_id} onChange={e=>setF({...f,template_id:e.target.value})}/></label><div className="full sequence-builder"><div className="card-head"><div><h3>Sequence steps</h3><p>Use <code>{'{{first_name}}'}</code> and <code>{'{{job_title}}'}</code> in messages.</p></div><Button variant="ghost" onClick={()=>setF({...f,steps:[...f.steps,blankStep()]})}><Plus size={15}/> Add step</Button></div>{f.steps.map((st:Step,i:number)=><div className="sequence-step" key={i}><div className="step-number">{i+1}</div><label>Delay (hours)<input type="number" min="0" value={st.delay_hours} onChange={e=>{const a=[...f.steps];a[i]={...a[i],delay_hours:e.target.value};setF({...f,steps:a})}}/></label><label>Subject / message title<input value={st.subject} onChange={e=>{const a=[...f.steps];a[i]={...a[i],subject:e.target.value};setF({...f,steps:a})}}/></label><label className="full">Message<textarea rows={4} value={st.body} onChange={e=>{const a=[...f.steps];a[i]={...a[i],body:e.target.value};setF({...f,steps:a})}}/></label>{f.steps.length>1&&<Button variant="ghost" onClick={()=>setF({...f,steps:f.steps.filter((_:Step,n:number)=>n!==i)})}>Remove</Button>}</div>)}</div><div className="form-actions"><Button type="submit">Save sequence</Button><Button variant="ghost" onClick={()=>setShow(false)}>Cancel</Button></div></form></Card>}
 {rows.length===0?<Empty title="No sequences configured" text="Create an application nurture sequence and activate it when your provider is ready."/>:<div className="grid two">{rows.map(x=><Card key={x.id}><div className="automation-icon"><Icon channel={x.channel}/></div><div className="card-head"><div><h3>{x.name}</h3><p>{x.trigger_event.replaceAll('_',' ')} · {x.channel} · {x.steps?.length||0} steps</p></div><Badge tone={x.active?'green':'neutral'}>{x.active?'Active':'Paused'}</Badge></div><p className="muted">{x.from_name||''} {x.from_address?`<${x.from_address}>`:''}</p><div className="button-row"><Button variant="ghost" onClick={()=>toggle(x)}><Power size={15}/>{x.active?'Pause':'Activate'}</Button>{x.active&&<Badge tone="green"><Send size={12}/> queued automatically</Badge>}</div></Card>)}</div>}
 <Card><div className="card-head"><div><h2>Automation queue</h2><p>Due messages are processed by the server-side queue worker. Configure a cron job to call the processor every few minutes.</p></div><Clock3 size={20}/></div>{enrolments.length===0?<Empty title="Queue is empty" text="New applications will appear here when an active application_received sequence has steps."/>:<div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Sequence</th><th>Step</th><th>Next run</th><th>Status</th></tr></thead><tbody>{enrolments.map(x=><tr key={x.id}><td><strong>{x.candidates?.full_name}</strong><span>{x.candidates?.email}</span></td><td>{x.automation_sequences?.name}</td><td>{Number(x.current_step)+1}</td><td>{new Date(x.next_run_at).toLocaleString('en-GB')}</td><td><Badge tone={x.status==='completed'?'green':x.status==='failed'?'red':'blue'}>{x.status}</Badge>{x.last_error&&<span>{x.last_error}</span>}</td></tr>)}</tbody></table></div>}</Card>
 <Card><div className="card-head"><div><h2>AI screening</h2><p>Run structured job-relevant screening through the server-side AI function. Human review remains required.</p></div><BrainCircuit size={20}/></div><Badge tone="neutral">Optional · requires OPENAI_API_KEY</Badge></Card></div>}
