import {useEffect,useMemo,useState} from 'react';
import {Badge,Button,Card,Empty,SkeletonCards} from '../components/Ui';
import {supabase} from '../lib/supabase';
const money=(v:any,c='GBP')=>new Intl.NumberFormat('en-GB',{style:'currency',currency:String(c||'GBP').trim()}).format(Number(v||0));
export default function Billing(){
 const[invoices,setInvoices]=useState<any[]>([]),[placements,setPlacements]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[subscription,setSubscription]=useState<any>(null),[plans,setPlans]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 async function load(){setLoading(true);const[i,pl,pa,s,p]=await Promise.all([supabase.from('invoices').select('*,clients(company_name,email)').order('created_at',{ascending:false}),supabase.from('placements').select('id,invoice_status,invoice_number,candidate_id,client_id,fee_amount,total_amount,currency,clients(company_name),candidates(full_name)').order('created_at',{ascending:false}),supabase.from('invoice_payments').select('*').order('paid_at',{ascending:false}),supabase.from('company_subscriptions').select('*,saas_plans(*)').maybeSingle(),supabase.from('saas_plans').select('*').eq('active',true).order('monthly_price_gbp')]);setInvoices(i.data||[]);setPlacements(pl.data||[]);setPayments(pa.data||[]);setSubscription(s.data);setPlans(p.data||[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 const invoicedPlacements=useMemo(()=>new Set(invoices.map(i=>i.placement_id)),[invoices]);
 async function payment(inv:any){const amount=prompt(`Payment amount (maximum currently due ${money(inv.amount_due,inv.currency)})`,String(inv.amount_due||''));if(!amount)return;const method=prompt('Payment method (bank transfer, card, cash, other)','bank transfer')||'manual';const reference=prompt('Payment reference (optional)')||null;const{error}=await supabase.rpc('record_invoice_payment',{p_invoice:inv.id,p_amount:Number(amount),p_method:method,p_reference:reference});if(error)return alert(error.message);await load()}
 async function adjust(inv:any,kind:'credit'|'write_off'|'debit'){const amount=prompt(`${kind.replace('_',' ')} amount`);if(!amount)return;const reason=prompt('Reason');if(!reason)return;const{error}=await supabase.rpc('record_invoice_adjustment',{p_invoice:inv.id,p_kind:kind,p_amount:Number(amount),p_reason:reason,p_reference:null});if(error)return alert(error.message);await load()}
 async function createInvoice(placementId:string){setBusy(`create:${placementId}`);const{error}=await supabase.rpc('create_placement_invoice',{p_placement:placementId,p_issue_date:new Date().toISOString().slice(0,10)});setBusy('');if(error)return alert(error.message);await load()}
 async function invoiceOp(inv:any,action:'generate'|'send'|'signed_url'){setBusy(`${action}:${inv.id}`);const body:any={invoice_id:inv.id,action};if(action==='send'){const to=prompt('Send invoice to',inv.sent_to||inv.clients?.email||'');if(!to){setBusy('');return}body.to=to}const{data,error}=await supabase.functions.invoke('invoice-operations',{body});setBusy('');if(error)return alert(error.message);if(data?.error)return alert(data.error);if(data?.pdf_url)window.open(data.pdf_url,'_blank','noopener,noreferrer');await load()}
 async function voidInvoice(inv:any){const reason=prompt('Reason for voiding this invoice');if(!reason)return;const{error}=await supabase.rpc('void_invoice',{p_invoice:inv.id,p_reason:reason});if(error)return alert(error.message);await load()}
 async function checkout(plan:string){setBusy(`plan:${plan}`);const{data,error}=await supabase.functions.invoke('subscription-billing',{body:{action:'checkout',plan}});setBusy('');if(error||data?.error)return alert(data?.error||error?.message);if(data?.url)location.href=data.url}
 async function portal(){setBusy('portal');const{data,error}=await supabase.functions.invoke('subscription-billing',{body:{action:'portal'}});setBusy('');if(error||data?.error)return alert(data?.error||error?.message);if(data?.url)location.href=data.url}
 if(loading)return <div className="page"><SkeletonCards count={4}/></div>;
 return <div className="page"><div className="page-actions"><div><h2>Billing & invoices</h2><p>Subscription billing, placement invoices, PDF delivery, payments, credits and write-offs.</p></div></div>
 <Card><div className="card-head"><div><h3>TalentFlow subscription</h3><p>{subscription?`${subscription.saas_plans?.name||subscription.plan_code} plan`:'No subscription record'}</p></div>{subscription&&<Badge tone={['active','trialing'].includes(subscription.status)?'green':subscription.status==='past_due'?'red':'amber'}>{subscription.status}</Badge>}</div>{subscription?.trial_ends_at&&<p>Trial ends {new Date(subscription.trial_ends_at).toLocaleDateString('en-GB')}.</p>}<div className="cards-list">{plans.map(p=><Card key={p.code}><div className="card-head"><div><strong>{p.name} — {money(p.monthly_price_gbp)}/month</strong><p>{p.recruiter_limit} recruiters · {p.active_job_limit} active jobs · {p.candidate_limit} candidates · {p.automation_limit} automations</p></div><Button disabled={busy===`plan:${p.code}`} onClick={()=>void checkout(p.code)}>{subscription?.plan_code===p.code?'Manage / renew':'Choose plan'}</Button></div></Card>)}</div>{subscription?.provider_customer_id&&<Button variant="ghost" disabled={busy==='portal'} onClick={()=>void portal()}>Open billing portal</Button>}<p className="muted">Card checkout and the customer portal activate when Stripe secrets and plan price IDs are configured. Trials and plan limits are enforced server-side.</p></Card>
 <Card><div className="card-head"><div><h3>Ready to invoice</h3><p>Successful placements that do not yet have a formal invoice.</p></div></div>{placements.filter(p=>!invoicedPlacements.has(p.id)).length===0?<Empty title="Nothing waiting" text="All recorded placements have invoices."/>:<div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Client</th><th>Fee</th><th></th></tr></thead><tbody>{placements.filter(p=>!invoicedPlacements.has(p.id)).map(p=><tr key={p.id}><td>{p.candidates?.full_name||'—'}</td><td>{p.clients?.company_name||'—'}</td><td>{money(p.total_amount||p.fee_amount,p.currency)}</td><td><Button disabled={busy===`create:${p.id}`} onClick={()=>void createInvoice(p.id)}>Create invoice</Button></td></tr>)}</tbody></table></div>}</Card>
 <Card><div className="card-head"><div><h3>Client invoice ledger</h3><p>Immutable financial history with separate payment and adjustment records.</p></div></div>{!invoices.length?<Empty title="No invoices" text="Create an invoice from a placement above."/>:<div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Client</th><th>Total</th><th>Paid / due</th><th>Status</th><th>Actions</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><strong>{i.number}</strong><span>{i.issue_date||'Draft'} · due {i.due_date||'—'}</span></td><td>{i.clients?.company_name||'—'}<span>{i.sent_to||i.clients?.email||''}</span></td><td>{money(i.total,i.currency)}</td><td><strong>{money(i.amount_paid,i.currency)} paid</strong><span>{money(i.amount_due,i.currency)} due</span></td><td><Badge tone={i.status==='paid'?'green':i.status==='overdue'?'red':i.status==='sent'||i.status==='partially_paid'?'blue':'amber'}>{String(i.status).replaceAll('_',' ')}</Badge></td><td><div className="button-row"><Button variant="ghost" onClick={()=>void invoiceOp(i,'generate')}>PDF</Button>{!['paid','void'].includes(i.status)&&<Button variant="ghost" onClick={()=>void invoiceOp(i,'send')}>Send</Button>}{!['paid','void'].includes(i.status)&&<Button variant="ghost" onClick={()=>void payment(i)}>Payment</Button>}{i.status!=='void'&&<Button variant="ghost" onClick={()=>void adjust(i,'credit')}>Credit</Button>}{!['paid','void'].includes(i.status)&&<Button variant="ghost" onClick={()=>void adjust(i,'write_off')}>Write off</Button>}{!['paid','void'].includes(i.status)&&<Button variant="ghost" onClick={()=>void voidInvoice(i)}>Void</Button>}</div></td></tr>)}</tbody></table></div>}</Card>
 <Card><div className="card-head"><div><h3>Payment history</h3><p>Separate ledger entries preserve when and how money was received.</p></div></div>{!payments.length?<Empty title="No payments recorded" text="Payments will appear here once recorded."/>:<div className="table-wrap"><table><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{new Date(p.paid_at).toLocaleDateString('en-GB')}</td><td>{p.method}</td><td>{p.reference||'—'}</td><td>{money(p.amount,p.currency)}</td><td><Badge tone={p.status==='succeeded'?'green':p.status==='failed'?'red':'amber'}>{p.status}</Badge></td></tr>)}</tbody></table></div>}</Card></div>}
