import {useEffect,useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {ArrowRight,BriefcaseBusiness,CheckCircle2} from 'lucide-react';
import {Badge,Button,Card,Empty} from '../components/Ui';
import {supabase} from '../lib/supabase';
import {trackCampaign} from '../lib/tracking';
export default function CampaignLanding(){
 const {slug}=useParams(); const [params]=useSearchParams(); const [c,setC]=useState<any>(null); const [selectedJob,setSelectedJob]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data}=await supabase.from('campaigns').select('*').eq('slug',slug).eq('status','active').single();setC(data);setLoading(false);if(data){trackCampaign(data.slug,'page_view',params.get('link')||undefined);if(data.job_id){const {data:job}=await supabase.from('jobs').select('*').eq('id',data.job_id).eq('status','published').single();setSelectedJob(job)}}})()},[slug]);
 if(loading)return <div className="public"><div className="loading">Loading opportunity…</div></div>;
 if(!c)return <div className="public"><Empty title="Campaign not found" text="This recruitment campaign is no longer active."/><Link to="/careers">Browse all opportunities</Link></div>;
 const destination=selectedJob?`/careers/${selectedJob.slug}?campaign_id=${encodeURIComponent(c.id)}&utm_source=${encodeURIComponent(params.get('utm_source')||'campaign')}&utm_medium=${encodeURIComponent(params.get('utm_medium')||'landing')}&utm_campaign=${encodeURIComponent(params.get('utm_campaign')||c.slug)}${params.get('utm_content')?`&utm_content=${encodeURIComponent(params.get('utm_content')!)}`:''}`:'/careers';
 return <div className="public"><header><div className="brand big"><div className="brand-mark">TF</div><div><strong>TalentFlow</strong><span>Opportunity campaign</span></div></div><span className="public-pill">Now recruiting</span></header><section className="hero campaign-hero"><Badge tone="green">Live opportunity</Badge><h1>{c.headline}</h1><p>{c.subheadline||'Explore the opportunity, see what is involved and apply in minutes.'}</p><div className="button-row"><Link to={destination} onClick={()=>trackCampaign(c.slug,'cta_click',params.get('link')||undefined)}><Button>{c.cta_text||'Apply now'} <ArrowRight size={17}/></Button></Link><Link className="text-link" to="/careers">Browse all roles</Link></div></section>{selectedJob&&<div className="grid two"><Card><div className="card-head"><div><h2>{selectedJob.title}</h2><p>{selectedJob.location} · {selectedJob.employment_type}</p></div><BriefcaseBusiness size={20}/></div><p className="prose">{selectedJob.description}</p></Card><Card><h2>What we're looking for</h2>{(selectedJob.requirements||[]).map((r:string)=><div className="list-row" key={r}><div><strong>{r}</strong></div><CheckCircle2 size={17}/></div>)}{selectedJob.commission_text&&<p className="small-text"><strong>Compensation:</strong> {selectedJob.commission_text}</p>}</Card></div>}{!selectedJob&&<Card><h2>Ready for your next move?</h2><p>Browse our current opportunities and choose the role that matches your experience.</p><Link to="/careers"><Button>View opportunities <ArrowRight size={17}/></Button></Link></Card>}</div>
}
