import {useEffect,useMemo,useState} from 'react';
import {BarChart3,Copy,ExternalLink,Link2,Plus,Target,Users} from 'lucide-react';
import {Badge,Button,Card,Empty} from '../components/Ui';
import {supabase} from '../lib/supabase';

const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const money=(v:any)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(v||0));
export default function Campaigns(){
 const [campaigns,setCampaigns]=useState<any[]>([]),[clients,setClients]=useState<any[]>([]),[jobs,setJobs]=useState<any[]>([]),[links,setLinks]=useState<any[]>([]),[perf,setPerf]=useState<any[]>([]),[show,setShow]=useState(false),[showLink,setShowLink]=useState(false),[selected,setSelected]=useState<any>(null);
 const [f,setF]=useState({client_id:'',job_id:'',name:'',slug:'',headline:'',subheadline:'',cta_text:'Apply now',budget:'0',status:'draft'});
 const [lf,setLf]=useState({campaign_id:'',label:'',slug:'',source:'referral',medium:'referral',campaign:'',content:''});
 const load=async()=>{const [c,cl,j,l,p]=await Promise.all([supabase.from('campaigns').select('*').order('created_at',{ascending:false}),supabase.from('clients').select('id,company_name').order('company_name'),supabase.from('jobs').select('id,title,client_id,status').order('title'),supabase.from('campaign_links').select('*').order('created_at',{ascending:false}),supabase.rpc('campaign_performance')]);setCampaigns(c.data||[]);setClients(cl.data||[]);setJobs(j.data||[]);setLinks(l.data||[]);setPerf(p.data||[])};
 useEffect(()=>{load()},[]);
 const total=useMemo(()=>perf.reduce((a,p)=>({views:a.views+Number(p.page_views||0),apps:a.apps+Number(p.applications||0),placements:a.placements+Number(p.placements||0),revenue:a.revenue+Number(p.revenue||0)}),{views:0,apps:0,placements:0,revenue:0}),[perf]);
 async function save(e:any){e.preventDefault();const payload={...f,slug:f.slug||slugify(f.name),budget:Number(f.budget||0),status:f.status};const {error}=await supabase.from('campaigns').insert(payload);if(error)alert(error.message);else{setShow(false);setF({client_id:'',job_id:'',name:'',slug:'',headline:'',subheadline:'',cta_text:'Apply now',budget:'0',status:'draft'});load()}}
 async function saveLink(e:any){e.preventDefault();const payload={...lf,slug:lf.slug||slugify(lf.label)};const {error}=await supabase.from('campaign_links').insert(payload);if(error)alert(error.message);else{setShowLink(false);setLf({campaign_id:'',label:'',slug:'',source:'referral',medium:'referral',campaign:'',content:''});load()}}
 const linkUrl=(l:any)=>`${window.location.origin}/campaign/${campaigns.find(c=>c.id===l.campaign_id)?.slug||''}?link=${encodeURIComponent(l.slug)}&utm_source=${encodeURIComponent(l.source)}&utm_medium=${encodeURIComponent(l.medium)}${l.campaign?`&utm_campaign=${encodeURIComponent(l.campaign)}`:''}${l.content?`&utm_content=${encodeURIComponent(l.content)}`:''}`;
 async function copy(v:string){await navigator.clipboard?.writeText(v);}
 return <div className="page"><div className="page-actions"><div><h2>Acquisition</h2><p>Build campaigns, referral links and measurable candidate funnels for any client.</p></div><div className="button-row"><Button variant="ghost" onClick={()=>setShowLink(true)}><Link2 size={17}/> Referral link</Button><Button onClick={()=>setShow(true)}><Plus size={17}/> New campaign</Button></div></div>
 <div className="metrics"><Card className="metric"><div className="metric-label">Campaign traffic</div><div className="metric-value">{total.views}</div><div className="metric-detail">Tracked landing-page views</div></Card><Card className="metric"><div className="metric-label">Applications</div><div className="metric-value">{total.apps}</div><div className="metric-detail">Attributed submissions</div></Card><Card className="metric"><div className="metric-label">Placements</div><div className="metric-value">{total.placements}</div><div className="metric-detail">Attributed placements</div></Card><Card className="metric"><div className="metric-label">Attributed revenue</div><div className="metric-value">{money(total.revenue)}</div><div className="metric-detail">Placement fees before VAT</div></Card></div>
 {show&&<Card className="form-card"><form className="form-grid" onSubmit={save}><label>Client<select required value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})}><option value="">Select client…</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><label>Job<select value={f.job_id} onChange={e=>setF({...f,job_id:e.target.value})}><option value="">Optional — campaign can cover multiple jobs</option>{jobs.filter(j=>!f.client_id||j.client_id===f.client_id).map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><label>Campaign name<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Slug<input value={f.slug} onChange={e=>setF({...f,slug:e.target.value})} placeholder="e.g. kes-agents"/></label><label>Headline<input required value={f.headline} onChange={e=>setF({...f,headline:e.target.value})}/></label><label>CTA text<input value={f.cta_text} onChange={e=>setF({...f,cta_text:e.target.value})}/></label><label className="full">Subheadline<textarea rows={3} value={f.subheadline} onChange={e=>setF({...f,subheadline:e.target.value})}/></label><label>Budget<input type="number" min="0" step="0.01" value={f.budget} onChange={e=>setF({...f,budget:e.target.value})}/></label><label>Status<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option></select></label><div className="form-actions"><Button type="submit">Create campaign</Button><Button variant="ghost" onClick={()=>setShow(false)}>Cancel</Button></div></form></Card>}
 {showLink&&<Card className="form-card"><form className="form-grid" onSubmit={saveLink}><label>Campaign<select required value={lf.campaign_id} onChange={e=>setLf({...lf,campaign_id:e.target.value})}><option value="">Select campaign…</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Link label<input required value={lf.label} onChange={e=>setLf({...lf,label:e.target.value})} placeholder="Indeed / Sarah referral / LinkedIn"/></label><label>Link slug<input value={lf.slug} onChange={e=>setLf({...lf,slug:e.target.value})}/></label><label>Source<input value={lf.source} onChange={e=>setLf({...lf,source:e.target.value})}/></label><label>Medium<input value={lf.medium} onChange={e=>setLf({...lf,medium:e.target.value})}/></label><label>Campaign<input value={lf.campaign} onChange={e=>setLf({...lf,campaign:e.target.value})}/></label><label>Content<input value={lf.content} onChange={e=>setLf({...lf,content:e.target.value})}/></label><div className="form-actions"><Button type="submit">Create referral link</Button><Button variant="ghost" onClick={()=>setShowLink(false)}>Cancel</Button></div></form></Card>}
 <div className="grid two"><Card><div className="card-head"><div><h2>Campaigns</h2><p>Traffic → application → placement → revenue.</p></div><Target size={20}/></div>{perf.length===0?<Empty title="No campaigns yet" text="Create a campaign for KES or another client."/>:perf.map(p=><div className="list-row" key={p.campaign_id}><div><strong>{p.campaign_name}</strong><span>{p.page_views} views · {p.applications} applications · {p.placements} placements · {money(p.revenue)}</span></div><div className="button-row"><Badge tone={p.status==='active'?'green':p.status==='paused'?'amber':'neutral'}>{p.status}</Badge><a className="text-link" href={`/campaign/${p.slug}`} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a></div></div>)}</Card>
 <Card><div className="card-head"><div><h2>Referral links</h2><p>Give each recruiter, partner or channel a unique attribution link.</p></div><Link2 size={20}/></div>{links.length===0?<Empty title="No referral links" text="Create one above to track a person or channel."/>:links.slice(0,8).map(l=><div className="list-row" key={l.id}><div><strong>{l.label}</strong><span>{l.source} / {l.medium} · {linkUrl(l)}</span></div><Button variant="ghost" onClick={()=>copy(linkUrl(l))}><Copy size={15}/> Copy</Button></div>)}</Card></div>
 <Card><div className="card-head"><div><h2>Acquisition economics</h2><p>Campaign performance is calculated from tracked events and attributed placement fees.</p></div><BarChart3 size={20}/></div><div className="table-wrap"><table><thead><tr><th>Campaign</th><th>Traffic</th><th>Apps</th><th>Placements</th><th>Cost / app</th><th>Cost / placement</th><th>ROI</th></tr></thead><tbody>{perf.map(p=><tr key={p.campaign_id}><td><strong>{p.campaign_name}</strong><span>{p.budget?money(p.budget)+' budget':'No paid budget'}</span></td><td>{p.page_views}</td><td>{p.applications}</td><td>{p.placements}</td><td>{p.cost_per_application==null?'—':money(p.cost_per_application)}</td><td>{p.cost_per_placement==null?'—':money(p.cost_per_placement)}</td><td>{p.roi==null?'—':`${p.roi}%`}</td></tr>)}</tbody></table></div></Card>
 <Card><div className="card-head"><div><h2>Recruiter growth loop</h2><p>Use the same infrastructure for paid ads, organic posts, recruiters, partners and referrals.</p></div><Users size={20}/></div><div className="funnel"><span>Campaign</span><i>→</i><span>Landing page</span><i>→</i><span>Application</span><i>→</i><span>Qualification</span><i>→</i><span>Placement</span><i>→</i><span>Revenue</span></div></Card>
 </div>
}
