import { useEffect,useState } from 'react';
import { Link,useSearchParams } from 'react-router-dom';
import { CheckCircle2, CalendarDays } from 'lucide-react';
import { Badge, Card, Empty } from '../components/Ui';
import { supabase } from '../lib/supabase';
export default function CandidatePortal(){const [params]=useSearchParams();const token=params.get('token');const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[slots,setSlots]=useState<any[]>([]),[booking,setBooking]=useState(''),[bookingBusy,setBookingBusy]=useState(false);
 useEffect(()=>{if(!token){setError('Missing candidate access link.');setLoading(false);return}(async()=>{try{const r=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/candidate-portal?token=${encodeURIComponent(token)}`,{headers:{apikey:import.meta.env.VITE_SUPABASE_ANON_KEY}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Link expired');setData(j);const {data:slotData,error:slotError}=await supabase.rpc('public_booking_slots',{p_token:token});if(!slotError)setSlots(slotData||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load application')}finally{setLoading(false)}})()},[token]);
 async function book(id:string){if(!token)return;setBookingBusy(true);setBooking('');const {data:result,error:e}=await supabase.rpc('book_candidate_slot',{p_token:token,p_slot_id:id});if(e){setBooking(e.message)}else{setBooking('Appointment booked successfully.');setSlots([]);setData((x:any)=>({...x,interviews:[...(x.interviews||[]),{id:result?.id,scheduled_at:result?.starts_at,duration_minutes:Math.round((new Date(result?.ends_at).getTime()-new Date(result?.starts_at).getTime())/60000),meeting_url:result?.meeting_url,status:'scheduled'}]}))}setBookingBusy(false)}
 if(loading)return <div className="public"><div className="loading">Loading your application…</div></div>;
 if(error)return <div className="public"><Card><h1>Application access</h1><p>{error}</p><Link to="/careers">← Browse opportunities</Link></Card></div>;
 return <div className="public portal"><header><div className="brand big"><div className="brand-mark">TF</div><div><strong>TalentFlow</strong><span>Candidate portal</span></div></div></header><section className="hero"><Badge tone="green">Application received</Badge><h1>Hi {data.candidate.full_name.split(' ')[0]}.</h1><p>Here is the current status of your application for <strong>{data.job.title}</strong>.</p></section>
 <Card><div className="status-track">{data.timeline.map((x:any)=><div className={`status-step ${x.done?'done':''}`} key={x.key}><div className="status-dot">{x.done?<CheckCircle2 size={17}/>:null}</div><div><strong>{x.label}</strong><span>{x.date?new Date(x.date).toLocaleDateString('en-GB'):'Not reached'}</span></div></div>)}</div></Card>
 {data.interviews?.length>0&&<Card><div className="card-head"><div><h2>Interview details</h2><p>Keep this information handy for your appointment.</p></div><CalendarDays size={20}/></div>{data.interviews.map((i:any)=><div className="interview-box" key={i.id}><strong>{new Date(i.scheduled_at).toLocaleString('en-GB')}</strong><span>{i.duration_minutes} minutes · {i.status}</span>{i.meeting_url&&<a className="text-link" href={i.meeting_url} target="_blank" rel="noreferrer">Join meeting ↗</a>}</div>)}</Card>}
 {slots.length>0&&<Card><div className="card-head"><div><h2>Book a screening call</h2><p>Choose an available time. The slot is reserved when you confirm.</p></div><CalendarDays size={20}/></div><div className="booking-slots">{slots.map((slot:any)=><button className="booking-slot" key={slot.id} disabled={bookingBusy} onClick={()=>void book(slot.id)}><strong>{new Date(slot.starts_at).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}</strong><span>{new Date(slot.starts_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}–{new Date(slot.ends_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</span></button>)}</div>{booking&&<div className="alert">{booking}</div>}</Card>}<Card><h2>What happens next?</h2><p>The recruitment team will contact you directly if there is an update, interview request or further information required.</p><p className="muted small-text">This portal shows recruitment status only and is not a hiring decision or offer.</p></Card></div>}
