import {useEffect, useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight, BriefcaseBusiness, MapPin, Search, Check, ArrowUpRight} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Opportunity = {id:string;slug:string;title:string;location:string;employment_type:string;description:string;commission_text:string|null};
export function CareersHeader(){return <header className="careers-nav"><Link to="/careers" className="careers-brand" aria-label="TalentFlow careers home"><span className="brand-mark">TF</span><strong>TalentFlow<span>YOUR NEXT CHAPTER</span></strong></Link><nav aria-label="Careers navigation"><Link to="/careers">Find a role</Link><Link to="/login" className="workspace-link">Team sign in <ArrowUpRight size={15}/></Link></nav></header>}
export function CareersFooter(){return <footer className="careers-footer"><div><strong>TalentFlow</strong><p>Your next chapter starts with a conversation.</p></div><nav aria-label="Legal information"><Link to="/privacy">Privacy</Link><Link to="/candidate-terms">Candidate terms</Link><Link to="/accessibility">Accessibility</Link></nav></footer>}

export default function CareersHome(){
 const [jobs,setJobs]=useState<Opportunity[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 const [query,setQuery]=useState(''),[place,setPlace]=useState(''),[type,setType]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError(false);
   (async()=>{try{const result=await supabase.from('jobs').select('id,slug,title,location,employment_type,description,commission_text').eq('status','published').order('created_at',{ascending:false});if(result.error)throw result.error;if(active)setJobs(result.data||[]);}catch{if(active)setError(true);}finally{if(active)setLoading(false);}})();
   return ()=>{active=false};
 },[retry]);
 const types=[...new Set(jobs.map(j=>j.employment_type))].sort();
 const filtered=jobs.filter(j=>(j.title+' '+j.description).toLowerCase().includes(query.trim().toLowerCase())&&j.location.toLowerCase().includes(place.trim().toLowerCase())&&(!type||j.employment_type===type));
 const clear=()=>{setQuery('');setPlace('');setType('')};
 return <div className="careers-site"><a className="skip-link" href="#opportunities">Skip to opportunities</a><CareersHeader/>
 <main><section className="careers-hero"><div className="careers-hero-copy"><span className="careers-kicker"><span/> MAKE YOUR NEXT MOVE</span><h1>Good opportunities.<br/><em>A fresh start.</em></h1><p>Find work that fits your experience and ambitions. Explore the details, ask yourself what matters, and take your next step.</p><a className="btn careers-primary" href="#opportunities">Explore opportunities <ArrowRight size={18}/></a><span className="hero-note">Across the UK · Employed and self-employed roles</span></div><aside className="journey-card" aria-label="Your application journey"><span className="journey-label">A CLEARER WAY FORWARD</span><h2>Your experience.<br/>Your next chapter.</h2>{[['01','Find your fit','Explore the role, requirements and terms.'],['02','Tell your story','Share the experience that makes you, you.'],['03','Take the next step','A recruiter reviews your application.']].map(([n,title,body])=><div className="journey-row" key={n}><span>{n}</span><div><h3>{title}</h3><p>{body}</p></div></div>)}<div className="journey-foot"><Check size={16}/> You can review your details before submitting.</div></aside></section>
 <section id="opportunities" className="opportunity-section" aria-labelledby="opportunity-heading"><div className="opportunity-heading"><div><span className="careers-kicker">FIND YOUR FIT</span><h2 id="opportunity-heading">Explore open opportunities</h2></div><p>No account needed to apply.</p></div>
 <form className="opportunity-search" onSubmit={e=>{e.preventDefault();document.getElementById('job-results')?.focus()}}><label><span>Role or keyword</span><div><Search size={18}/><input type="search" placeholder="Job title, skill or keyword" value={query} onChange={e=>setQuery(e.target.value)}/></div></label><label><span>Location</span><div><MapPin size={18}/><input type="search" placeholder="Town, city or remote" value={place} onChange={e=>setPlace(e.target.value)}/></div></label><label><span>Type of opportunity</span><select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{types.map(t=><option key={t}>{t}</option>)}</select></label><button type="submit" className="btn">Find opportunities <ArrowRight size={16}/></button></form>
 <div id="job-results" tabIndex={-1} className="job-results"><div className="results-summary"><p role="status">{loading?'Finding opportunities…':error?'Opportunities unavailable':`${filtered.length} ${filtered.length===1?'opportunity':'opportunities'}${query||place||type?' matching your search':' available'}`}</p>{(query||place||type)&&<button className="text-link clear-filters" onClick={clear}>Clear filters</button>}</div>
 {loading?<div className="careers-state" role="status">Loading the latest opportunities…</div>:error?<div className="careers-state" role="alert"><h3>We couldn’t load the opportunities.</h3><p>Please try again. Your search filters will be kept.</p><button className="btn" onClick={()=>setRetry(x=>x+1)}>Try again</button></div>:filtered.length===0?<div className="careers-state"><BriefcaseBusiness size={32}/><h3>{jobs.length?'Let’s broaden your search.':'Your next opportunity could be on its way.'}</h3><p>{jobs.length?'Try a different keyword or location, or see all open roles.':'There are no open roles at the moment. Please check back for new opportunities.'}</p>{jobs.length>0&&<button className="btn ghost" onClick={clear}>See all opportunities</button>}</div>:<div className="opportunity-grid">{filtered.map(j=><article className="opportunity-card" key={j.id}><div className="opportunity-card-top"><span className="job-mark"><BriefcaseBusiness size={21}/></span><span className="badge green">{j.employment_type}</span></div><h3><Link to={`/careers/${encodeURIComponent(j.slug)}`}>{j.title}</Link></h3><p className="job-location"><MapPin size={15}/>{j.location}</p><p className="job-excerpt">{j.description}</p><div className="job-terms"><span>PAY & TERMS</span><p>{j.commission_text||'See the full role details and discuss pay with the recruitment team.'}</p></div><Link className="job-details-link" to={`/careers/${encodeURIComponent(j.slug)}`}>View role & apply <ArrowRight size={17}/></Link></article>)}</div>}</div></section>
 <section className="careers-help"><div><span className="careers-kicker">BEFORE YOU APPLY</span><h2>A little clarity goes a long way.</h2><p>Know what to expect before you take the next step.</p></div><div className="careers-faq">{[['What happens after I apply?','Your application goes to the recruitment team for review. If there is a suitable next step, they will contact you using the details you provide.'],['Do I need a CV?','A CV can help explain your experience, but the application also gives you space to tell your story. PDF and Word files up to 5MB are accepted.'],['Are all opportunities employed roles?','No. Some opportunities are self-employed or commission-based. Read the role details carefully and clarify earnings, costs and contract terms before committing.'],['How is my information used?','Your information is used to assess your application. Read the candidate privacy notice for details about processing, sharing and your rights.']].map(([title,body])=><details key={title}><summary>{title}</summary><p>{body}</p></details>)}</div></section></main><CareersFooter/></div>
}
