import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {Badge,Card,Empty,SkeletonRows} from '../components/Ui';
import {supabase} from '../lib/supabase';
import {useWorkspaceAccess} from '../lib/access';

const scopeLabel=(scope:string)=>scope==='candidate_and_vacancy'?'Assigned candidate + vacancy':scope==='candidate'?'Assigned candidate':scope==='client_submission'?'Official submission on your vacancy':'Assigned vacancy';
const toneFor=(status:string)=>status==='placed'?'green':status==='rejected'||status==='withdrawn'?'red':status==='offer'||status==='interview'?'amber':'blue';

export default function PartnerApplications(){
 const access=useWorkspaceAccess();
 const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all');
 useEffect(()=>{if(access.loading)return;if(!access.candidateProcessingActive){setRows([]);setError('');setLoading(false);return}let active=true;(async()=>{setLoading(true);setError('');const{data,error}=await supabase.functions.invoke('partner-applications-list',{body:{}});if(!active)return;if(error){let detail=error.message||'Unable to load applications.';try{const context=(error as any).context;if(context instanceof Response){const body=await context.clone().json();if(body?.error)detail=body.error}}catch{}setError(detail);setRows([])}else setRows(data?.applications||[]);setLoading(false)})();return()=>{active=false}},[access.loading,access.candidateProcessingActive]);
 const statuses=useMemo(()=>Array.from(new Set(rows.map(x=>x.status).filter(Boolean))).sort(),[rows]);
 const filtered=useMemo(()=>rows.filter(a=>{const hay=`${a.candidate?.full_name||''} ${a.candidate?.email||''} ${a.job?.title||''} ${a.job?.client?.company_name||''}`.toLowerCase();return(!query||hay.includes(query.toLowerCase()))&&(status==='all'||a.status===status)}),[rows,query,status]);
 if(!access.loading&&!access.candidateProcessingActive)return <div className="page partner-page"><div className="page-actions"><div><div className="eyebrow">MY APPLICATIONS</div><h2>Applications</h2><p>Application handling is unavailable while candidate processing is disabled.</p></div></div><Card><h3>Candidate processing is disabled</h3><p>Vorlen will unlock assigned applications when the candidate-processing compliance checkpoint is active.</p></Card></div>;
 return <div className="page partner-page">
  <div className="page-actions"><div><div className="eyebrow">MY APPLICATIONS</div><h2>Applications</h2><p>{access.partnerCanSourceCandidates?'Applications are limited to candidates or vacancies actively assigned to you.':'See only official client submissions on vacancies assigned to you.'} Other partners&apos; unrelated recruitment records are not exposed.</p></div></div>
  <div className="notice"><strong>Controlled candidate access.</strong> {access.partnerCanSourceCandidates?'This page shows the minimum application context needed for your assigned recruitment work.':'As the client-side vacancy owner, you see only candidates who have reached an official client submission; candidate email, CV and screening data stay with the authorised candidate workflow.'}</div>
  <div className="toolbar"><input aria-label="Search partner applications" placeholder="Search candidate, email, vacancy or client…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter partner applications by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(s=><option key={s} value={s}>{String(s).replaceAll('_',' ')}</option>)}</select></div>
  {error&&<div className="alert error" role="alert">{error}</div>}
  {loading?<Card><SkeletonRows rows={5}/></Card>:error?null:rows.length===0?<Empty title="No assigned applications yet" text="Applications will appear here when they relate to a candidate or vacancy actively assigned to you."/>:filtered.length===0?<Empty title="No matching applications" text="Change the search or status filter."/>:<Card><div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Vacancy</th><th>Status</th><th>Why visible</th><th>Submitted</th><th></th></tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td><strong>{a.candidate?.full_name||'Candidate'}</strong>{a.candidate?.email&&<span>{a.candidate.email}</span>}</td><td><strong>{a.job?.title||'Vacancy'}</strong><span>{a.job?.client?.company_name||'Client'}{a.job?.status?' · '+String(a.job.status).replaceAll('_',' '):''}</span></td><td><Badge tone={toneFor(a.status) as any}>{String(a.status||'received').replaceAll('_',' ')}</Badge></td><td><span>{scopeLabel(a.scope)}</span></td><td>{a.submitted_at?new Date(a.submitted_at).toLocaleString('en-GB'):'—'}</td><td><div className="button-row">{access.partnerCanSourceCandidates?(a.scope!=='candidate'&&a.job?.id?<Link className="btn ghost" to={'/dashboard/partner/pipeline?job='+encodeURIComponent(a.job.id)}>Open pipeline</Link>:<Link className="btn ghost" to="/dashboard/partner/candidates">Open candidates</Link>):a.job?.id?<Link className="btn ghost" to="/dashboard/partner/vacancies">Open vacancy</Link>:null}</div></td></tr>)}</tbody></table></div></Card>}
 </div>;
}
