import {useEffect,useMemo,useState} from 'react';
import {BrainCircuit,FileSearch,Users,Send,CalendarDays,ClipboardCheck,Plug,Share2,RefreshCw} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {Badge,Button,Card,SkeletonRows,useToast} from '../components/Ui';

const fmt=(v:any)=>v?new Date(v).toLocaleString('en-GB'):'—';
export default function PartnerTalentTools(){
 const toast=useToast();
 const[data,setData]=useState<any>(null),[aiStatus,setAiStatus]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const[jobId,setJobId]=useState(''),[candidateId,setCandidateId]=useState(''),[cvFile,setCvFile]=useState<File|null>(null),[cvEvidence,setCvEvidence]=useState(''),[matches,setMatches]=useState<any[]>([]),[aiMatches,setAiMatches]=useState<any[]>([]),[parsePreview,setParsePreview]=useState<any>(null);
 const[pack,setPack]=useState({summary:'',headline:'',strengths:'',concerns:''});
 const[assessment,setAssessment]=useState({template_id:'',summary:'',recommendation:'',score:''}),[assessmentAnswers,setAssessmentAnswers]=useState<Record<string,string>>({});
 const[interview,setInterview]=useState({scheduled_at:'',duration:'45',meeting_url:'',notes:''});
 async function load(){setLoading(true);setError('');const[{data:d,error:e},{data:ais,error:aie}]=await Promise.all([supabase.rpc('partner_talent_snapshot'),supabase.rpc('partner_ai_capability_status')]);if(e||aie){setError(e?.message||aie?.message||'Unable to load talent tools');setData(null)}else{setData(d);setAiStatus(ais||null);setJobId((v:string)=>v||(d?.jobs?.[0]?.id||''));setCandidateId((v:string)=>v||(d?.candidates?.[0]?.id||''));setAssessment((v:any)=>({...v,template_id:v.template_id||(d?.assessment_templates?.[0]?.id||'')}))}setLoading(false)}
 useEffect(()=>{void load()},[]);
 const jobs=data?.jobs||[],candidates=data?.candidates||[],pools=data?.pools||[],packs=data?.submission_packs||[],submissions=data?.submissions||[],interviews=data?.interviews||[],templates=data?.assessment_templates||[],results=data?.assessment_results||[],integrations=data?.integrations||[],distributions=data?.distribution_requests||[];
 const job=jobs.find((j:any)=>j.id===jobId),candidate=candidates.find((c:any)=>c.id===candidateId);
 const submission=useMemo(()=>submissions.find((s:any)=>s.job_id===jobId&&s.candidate_id===candidateId),[submissions,jobId,candidateId]);
 async function lexicalMatch(){if(!jobId)return;setBusy('match');setError('');const{data:d,error:e}=await supabase.rpc('partner_candidate_match',{p_job:jobId,p_limit:30});setBusy('');if(e)return setError(e.message);setMatches(d||[]);setAiMatches([])}
 async function aiMatch(){if(!jobId)return;setBusy('ai-match');setError('');const{data:d,error:e}=await supabase.functions.invoke('partner-ai-tools',{body:{action:'match_candidates',job_id:jobId}});setBusy('');if(e||d?.error)return setError(d?.error||e?.message||'AI matching failed');setAiMatches(d?.matches||[])}
 async function requestAccess(m:any){setBusy('access');setError('');const reason='Candidate matched to '+(job?.title||'assigned vacancy')+' through Vorlen Talent Match.';const{error:e}=await supabase.rpc('partner_request_candidate_access',{p_candidate:m.candidate_id,p_job:jobId,p_reason:reason});setBusy('');if(e)return setError(e.message);toast('Candidate access request sent to Vorlen management.')}
 async function uploadCv(){if(!candidateId||!cvFile||cvEvidence.trim().length<10)return;const fd=new FormData();fd.append('candidate_id',candidateId);fd.append('file',cvFile);fd.append('source_evidence',cvEvidence.trim());setBusy('cv-upload');setError('');const{data:d,error:e}=await supabase.functions.invoke('partner-candidate-cv',{body:fd});setBusy('');if(e||d?.error)return setError(d?.detail?d.error+' '+d.detail:(d?.error||e?.message||'CV upload failed'));toast('Candidate CV uploaded securely.');setCvFile(null);setCvEvidence('');await load()}
 async function parseCv(){if(!candidateId)return;setBusy('parse');setError('');const{data:d,error:e}=await supabase.functions.invoke('partner-ai-tools',{body:{action:'parse_resume',candidate_id:candidateId}});setBusy('');if(e||d?.error)return setError(d?.error||e?.message||'CV parsing failed');setParsePreview(d?.proposed||null)}
 async function applyParse(){if(!candidateId||!parsePreview)return;setBusy('apply');const{error:e}=await supabase.rpc('partner_apply_candidate_enrichment',{p_candidate:candidateId,p_location:parsePreview.location||null,p_experience_summary:parsePreview.experience_summary||null,p_training_qualifications:parsePreview.training_qualifications||null,p_authorisations:parsePreview.authorisations||null});setBusy('');if(e)return setError(e.message);toast('Recruiter-reviewed CV enrichment applied.');setParsePreview(null);await load()}
 async function createPack(e:any){e.preventDefault();if(!jobId||!candidateId||!pack.summary.trim())return;setBusy('pack');const{error:er}=await supabase.rpc('partner_create_submission_pack',{p_job:jobId,p_candidate:candidateId,p_summary:pack.summary.trim(),p_headline:pack.headline||null,p_strengths:pack.strengths.split('\n').map(x=>x.trim()).filter(Boolean),p_concerns:pack.concerns.split('\n').map(x=>x.trim()).filter(Boolean)});setBusy('');if(er)return setError(er.message);toast('Candidate submission pack sent for Vorlen review.');setPack({summary:'',headline:'',strengths:'',concerns:''});await load()}
 async function recordAssessment(e:any){e.preventDefault();if(!candidateId)return;const template=templates.find((t:any)=>t.id===assessment.template_id),questions=Array.isArray(template?.questions)?template.questions:[];const missing=questions.filter((q:any)=>q.required&&!String(assessmentAnswers[q.key]||'').trim());if(missing.length)return setError('Complete required screening evidence: '+missing.map((q:any)=>q.label).join(', '));const answers=Object.fromEntries(Object.entries(assessmentAnswers).filter(([,v])=>String(v||'').trim()));setBusy('assessment');const{error:er}=await supabase.rpc('partner_record_assessment',{p_candidate:candidateId,p_job:jobId||null,p_template:assessment.template_id||null,p_answers:answers,p_score:assessment.score?Number(assessment.score):null,p_summary:assessment.summary||null,p_recommendation:assessment.recommendation||null});setBusy('');if(er)return setError(er.message);toast('Structured assessment recorded.');setAssessment(v=>({...v,summary:'',recommendation:'',score:''}));setAssessmentAnswers({});await load()}
 async function scheduleInterview(e:any){e.preventDefault();if(!candidateId||!jobId||!interview.scheduled_at)return;setBusy('interview');const{error:er}=await supabase.rpc('partner_schedule_interview',{p_candidate:candidateId,p_job:jobId,p_scheduled_at:new Date(interview.scheduled_at).toISOString(),p_duration_minutes:Number(interview.duration||45),p_meeting_url:interview.meeting_url||null,p_notes:interview.notes||null});setBusy('');if(er)return setError(er.message);toast('Interview scheduled.');setInterview({scheduled_at:'',duration:'45',meeting_url:'',notes:''});await load()}
 async function requestDistribution(provider:string){if(!jobId)return;setBusy('dist');const{error:e}=await supabase.rpc('partner_request_job_distribution',{p_job:jobId,p_provider:provider});setBusy('');if(e)return setError(e.message);toast(provider==='vorlen_careers'?'Vorlen Careers distribution request recorded.':'Distribution request recorded; provider configuration/manager processing may be required.');await load()}
 function downloadInterviewCalendar(i:any){const j=jobs.find((x:any)=>x.id===i.job_id),c=candidates.find((x:any)=>x.id===i.candidate_id);const start=new Date(i.scheduled_at),end=new Date(start.getTime()+Number(i.duration_minutes||45)*60000);const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const esc=(v:string)=>String(v||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Vorlen//Partner Interview//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT','UID:'+esc(i.id)+'@vorlen.co.uk','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(start),'DTEND:'+stamp(end),'SUMMARY:'+esc('Interview · '+(c?.full_name||'Candidate')+' · '+(j?.title||'Vacancy')),'DESCRIPTION:'+esc(i.recruiter_notes||'Vorlen recruitment interview'),i.meeting_url?'URL:'+esc(i.meeting_url):'','END:VEVENT','END:VCALENDAR'].filter(Boolean).join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='vorlen-interview.ics';a.click();URL.revokeObjectURL(url)}
 if(loading)return <div className="page"><SkeletonRows rows={7}/></div>;
 return <div className="page partner-page">
  {error&&<div className="notice error">{error}</div>}
  <div className="page-actions"><div><div className="eyebrow">TALENT TOOLS</div><h2>Find, qualify and present candidates</h2><p>AI-assisted matching, CV enrichment, talent pools, structured screening, client submissions, interviews and distribution — all scoped to your assigned work.</p></div><Button variant="ghost" onClick={load}><RefreshCw size={14}/>Refresh</Button></div>
  <Card><div className="form-grid"><label>Assigned vacancy<select value={jobId} onChange={e=>{setJobId(e.target.value);setMatches([]);setAiMatches([])}}><option value="">Select vacancy…</option>{jobs.map((j:any)=><option key={j.id} value={j.id}>{j.title} · {j.status}</option>)}</select></label><label>Assigned candidate<select value={candidateId} onChange={e=>{setCandidateId(e.target.value);setParsePreview(null)}}><option value="">Select candidate…</option>{candidates.map((c:any)=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label></div></Card>

  <div className="grid two">
   <Card><div className="card-head"><div><h3><BrainCircuit size={17}/> Talent Match</h3><p>Search existing Vorlen candidates for this vacancy before sourcing from scratch.</p></div></div>{aiStatus?.enabled===false&&<div className="notice">{aiStatus.reason}</div>}<div className="button-row"><Button disabled={!jobId||!!busy} onClick={lexicalMatch}><FileSearch size={14}/>Evidence match</Button><Button disabled={!jobId||!!busy||aiStatus?.enabled!==true} onClick={aiMatch}><BrainCircuit size={14}/>AI rerank</Button></div>
    {(aiMatches.length?aiMatches:matches).map((m:any)=><div className="list-row" key={m.candidate_id}><div><strong>{m.full_name||matches.find((x:any)=>x.candidate_id===m.candidate_id)?.full_name||m.candidate_id}</strong><span>Match {m.score??m.match_score??0}/100</span><span>{m.summary||((m.match_reasons||[]).join(', '))||'Evidence match'}</span>{Array.isArray(m.strengths)&&m.strengths.length>0&&<small>Strengths: {m.strengths.join(' · ')}</small>}{Array.isArray(m.gaps)&&m.gaps.length>0&&<small>Gaps: {m.gaps.join(' · ')}</small>}</div><Button variant="ghost" disabled={busy==='access'} onClick={()=>requestAccess(m)}>Request access</Button></div>)}
    {!matches.length&&!aiMatches.length&&<p className="muted">Choose a vacancy and run Talent Match.</p>}
   </Card>

   <Card><div className="card-head"><div><h3><FileSearch size={17}/> CV parse & enrichment</h3><p>Securely attach a candidate-provided CV, then extract structured evidence and review it before applying.</p></div></div>{candidate?<><strong>{candidate.full_name}</strong><p className="muted">{candidate.resume_path?'Stored CV available':'No stored CV available'}</p><div className="form-grid"><label className="full">Candidate-provided CV<input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>setCvFile(e.target.files?.[0]||null)}/></label><label className="full">Source / authorisation evidence<textarea rows={2} value={cvEvidence} onChange={e=>setCvEvidence(e.target.value)} placeholder="e.g. Candidate emailed this CV to me on 25 Sep and asked Vorlen to use it for this vacancy."/></label><Button variant="ghost" disabled={!cvFile||cvEvidence.trim().length<10||busy==='cv-upload'} onClick={uploadCv}>Upload CV securely</Button></div>{aiStatus?.enabled===false&&<div className="notice">{aiStatus.reason}</div>}<Button disabled={!candidate.resume_path||!!busy||aiStatus?.enabled!==true} onClick={parseCv}>Parse CV with AI</Button>{parsePreview&&<div className="review-box"><strong>Review proposed enrichment</strong><span>Location: {parsePreview.location||'—'}</span><span>Experience: {parsePreview.experience_summary||'—'}</span><span>Qualifications: {parsePreview.training_qualifications||'—'}</span><span>Authorisations: {parsePreview.authorisations||'—'}</span>{parsePreview.missing_or_uncertain?.length>0&&<span>Missing/uncertain: {parsePreview.missing_or_uncertain.join(' · ')}</span>}<div className="button-row"><Button disabled={busy==='apply'} onClick={applyParse}>Apply reviewed enrichment</Button><Button variant="ghost" onClick={()=>setParsePreview(null)}>Discard</Button></div></div>}</>:<p className="muted">Select an assigned candidate.</p>}</Card>
  </div>

  <div className="grid two">
   <Card><div className="card-head"><div><h3><Users size={17}/> Talent pools / hotlists</h3><p>Reusable candidate groups by skill, sector, role or location.</p></div></div>{pools.map((p:any)=><div className="list-row" key={p.id}><div><strong>{p.name}</strong><span>{(p.members||[]).length} candidates</span>{p.description&&<span>{p.description}</span>}</div></div>)}{!pools.length&&<p className="muted">No talent pools yet. Create and manage pools from Pipeline.</p>}</Card>
   <Card><div className="card-head"><div><h3><Send size={17}/> Professional candidate submission</h3><p>Prepare a client-ready evidence pack for Vorlen review. Partners never bypass human/compliance review.</p></div></div><form className="form-grid" onSubmit={createPack}><label className="full">Headline<input value={pack.headline} onChange={e=>setPack({...pack,headline:e.target.value})} placeholder="Concise candidate positioning"/></label><label className="full">Recruiter summary<textarea required rows={4} value={pack.summary} onChange={e=>setPack({...pack,summary:e.target.value})}/></label><label>Strengths (one per line)<textarea rows={4} value={pack.strengths} onChange={e=>setPack({...pack,strengths:e.target.value})}/></label><label>Concerns / evidence gaps<textarea rows={4} value={pack.concerns} onChange={e=>setPack({...pack,concerns:e.target.value})}/></label><Button type="submit" disabled={!jobId||!candidateId||!pack.summary.trim()||busy==='pack'}>Send for Vorlen review</Button></form>{packs.slice(0,8).map((p:any)=><div className="list-row" key={p.id}><div><strong>{candidates.find((c:any)=>c.id===p.candidate_id)?.full_name||'Candidate'}</strong><span>{jobs.find((j:any)=>j.id===p.job_id)?.title||'Vacancy'} · {p.status}</span>{p.manager_notes&&<span>Vorlen: {p.manager_notes}</span>}</div><Badge tone={p.status==='approved'||p.status==='submitted'?'green':p.status==='declined'?'red':'amber'}>{p.status}</Badge></div>)}</Card>
  </div>

  <Card><div className="card-head"><div><h3>Client collaboration</h3><p>See what the client has done with submitted candidates without impersonating or acting as the client.</p></div></div>{submissions.slice(0,12).map((x:any)=><div className="list-row" key={x.id}><div><strong>{candidates.find((c:any)=>c.id===x.candidate_id)?.full_name||'Candidate'} → {jobs.find((j:any)=>j.id===x.job_id)?.title||'Vacancy'}</strong><span>Submission: {String(x.status||'submitted').replaceAll('_',' ')}</span>{x.client_decision&&<span>Client decision: {String(x.client_decision).replaceAll('_',' ')}</span>}{x.client_rating&&<span>Client rating: {x.client_rating}/5</span>}{x.client_feedback&&<span>Client feedback: {x.client_feedback}</span>}{x.submitted_at&&<small>Submitted {fmt(x.submitted_at)}</small>}</div><Badge tone={x.client_decision==='approve'||x.status==='approved'?'green':x.client_decision==='reject'||x.status==='rejected'?'red':'amber'}>{x.client_decision?String(x.client_decision).replaceAll('_',' '):'awaiting client'}</Badge></div>)}{!submissions.length&&<p className="muted">No client-visible submissions yet. Approved partner packs still pass through Vorlen's human/statutory submission gate before reaching the client portal.</p>}</Card>
  <div className="grid two">
   <Card><div className="card-head"><div><h3><ClipboardCheck size={17}/> Structured screening</h3><p>Record consistent job-related evidence rather than free-form impressions.</p></div></div><form className="form-grid" onSubmit={recordAssessment}><label>Template<select value={assessment.template_id} onChange={e=>{setAssessment({...assessment,template_id:e.target.value});setAssessmentAnswers({})}}><option value="">No template</option>{templates.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Score<input type="number" min="0" max="100" value={assessment.score} onChange={e=>setAssessment({...assessment,score:e.target.value})}/></label>{(()=>{const template=templates.find((t:any)=>t.id===assessment.template_id),questions=Array.isArray(template?.questions)?template.questions:[];return questions.map((q:any)=><label className="full" key={q.key}>{q.label}{q.required?' *':''}<textarea rows={q.type==='text'?3:2} required={!!q.required} value={assessmentAnswers[q.key]||''} onChange={e=>setAssessmentAnswers(v=>({...v,[q.key]:e.target.value}))}/></label>)})()}<label className="full">Summary<textarea rows={3} value={assessment.summary} onChange={e=>setAssessment({...assessment,summary:e.target.value})}/></label><label className="full">Recommendation / next step<input value={assessment.recommendation} onChange={e=>setAssessment({...assessment,recommendation:e.target.value})}/></label><Button type="submit" disabled={!candidateId||busy==='assessment'}>Save assessment</Button></form>{results.slice(0,6).map((r:any)=><div className="list-row" key={r.id}><div><strong>{candidates.find((c:any)=>c.id===r.candidate_id)?.full_name||'Candidate'}</strong><span>{r.score!=null?'Score '+r.score+' · ':''}{r.summary||'Assessment completed'}</span></div></div>)}</Card>

   <Card><div className="card-head"><div><h3><CalendarDays size={17}/> Interview scheduling</h3><p>Schedule only after the client has approved or requested an interview for the submitted candidate.</p></div></div>{submission?<div className="notice">Client submission: <strong>{submission.client_decision||submission.status}</strong>{submission.client_feedback&&<> · {submission.client_feedback}</>}</div>:<div className="notice">No client submission is linked to the selected candidate + vacancy yet.</div>}<form className="form-grid" onSubmit={scheduleInterview}><label>When<input type="datetime-local" value={interview.scheduled_at} onChange={e=>setInterview({...interview,scheduled_at:e.target.value})}/></label><label>Minutes<input type="number" min="15" max="240" value={interview.duration} onChange={e=>setInterview({...interview,duration:e.target.value})}/></label><label className="full">Meeting URL<input value={interview.meeting_url} onChange={e=>setInterview({...interview,meeting_url:e.target.value})}/></label><label className="full">Notes<textarea rows={3} value={interview.notes} onChange={e=>setInterview({...interview,notes:e.target.value})}/></label><Button type="submit" disabled={!jobId||!candidateId||!interview.scheduled_at||busy==='interview'}>Schedule interview</Button></form>{interviews.slice(0,8).map((i:any)=><div className="list-row" key={i.id}><div><strong>{candidates.find((c:any)=>c.id===i.candidate_id)?.full_name||'Candidate'}</strong><span>{jobs.find((j:any)=>j.id===i.job_id)?.title||'Vacancy'} · {fmt(i.scheduled_at)}</span>{i.meeting_url&&<a href={i.meeting_url} target="_blank" rel="noreferrer">Open meeting</a>}</div><div className="button-row"><Badge tone={i.status==='completed'?'green':i.status==='cancelled'?'red':'amber'}>{i.status}</Badge>{i.status!=='cancelled'&&<Button variant="ghost" onClick={()=>downloadInterviewCalendar(i)}>Add to calendar</Button>}</div></div>)}</Card>
  </div>

  <div className="grid two">
   <Card><div className="card-head"><div><h3><Plug size={17}/> Sourcing integrations</h3><p>Provider capability is visible without pretending an unconfigured external API is connected.</p></div></div>{integrations.filter((i:any)=>['candidate_source','social'].includes(i.category)).map((i:any)=><div className="list-row" key={i.id}><div><strong>{i.display_name}</strong><span>{(i.capabilities||[]).join(' · ')}</span><small>{i.configuration_note}</small></div><Badge tone={i.status==='connected'?'green':'neutral'}>{i.status.replaceAll('_',' ')}</Badge></div>)}</Card>
   <Card><div className="card-head"><div><h3><Share2 size={17}/> Job distribution</h3><p>Request distribution for the selected assigned vacancy. External boards require their approved credentials; Vorlen Careers is native.</p></div></div>{integrations.filter((i:any)=>['job_board','social'].includes(i.category)).map((i:any)=><div className="list-row" key={'dist-'+i.id}><div><strong>{i.display_name}</strong><span>{i.status.replaceAll('_',' ')}</span></div><Button variant="ghost" disabled={!jobId||busy==='dist'} onClick={()=>requestDistribution(i.provider)}>Request</Button></div>)}{distributions.slice(0,8).map((d:any)=><div className="list-row" key={d.id}><div><strong>{d.provider}</strong><span>{jobs.find((j:any)=>j.id===d.job_id)?.title||'Vacancy'} · {d.status.replaceAll('_',' ')}</span>{d.external_url&&<a href={d.external_url} target="_blank" rel="noreferrer">Open listing</a>}{d.error_message&&<span>{d.error_message}</span>}</div></div>)}</Card>
  </div>
 </div>
}