import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {Card,Spinner} from '../components/Ui';
const stages=['new','screening','qualified','submitted','interview','offer','placed','rejected','withdrawn'];
export default function Pipeline(){
 const[rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[page,setPage]=useState(0),[count,setCount]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);supabase.from('applications').select('id,candidate_id,status,submitted_at,candidates(full_name),jobs(title)',{count:'exact'}).order('submitted_at',{ascending:false}).range(page*100,page*100+99).then(r=>{if(!active)return;setError(r.error?.message||'');setRows(r.data||[]);setCount(r.count||0);setLoading(false)});return()=>{active=false}},[page]);
 return <div className="page"><div className="page-actions"><div><h2>Application pipeline</h2><p>Each card follows one application. Open it to review evidence and record the next decision.</p></div></div>{error&&<div className="alert error">{error}</div>}{loading?<Spinner/>:<><p>{count} applications · Showing {rows.length? page*100+1:0}–{page*100+rows.length}</p><div className="kanban">{stages.map(stage=><div className="lane" key={stage}><div className="lane-head"><strong>{stage}</strong><span>{rows.filter(r=>(r.status||'new')===stage).length} on this page</span></div>{rows.filter(r=>(r.status||'new')===stage).map(r=><Card className="candidate-card" key={r.id}><strong>{r.candidates?.full_name||'Candidate unavailable'}</strong><span>{r.jobs?.title||'Opportunity unavailable'}</span><Link to={'/dashboard/candidates/'+r.candidate_id+'?application='+r.id}>Review application</Link></Card>)}</div>)}</div>{!count&&<Card>No applications yet. Publish an opportunity to start receiving interest.</Card>}<div className="button-row"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={(page+1)*100>=count} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}</div>
}
