import {Link} from 'react-router-dom';
const controller=import.meta.env.VITE_LEGAL_NAME||'[Configure VITE_LEGAL_NAME]';
const address=import.meta.env.VITE_LEGAL_ADDRESS||'[Configure VITE_LEGAL_ADDRESS]';
const privacyEmail=import.meta.env.VITE_PRIVACY_EMAIL||'[Configure VITE_PRIVACY_EMAIL]';
const retention=import.meta.env.VITE_CANDIDATE_RETENTION_MONTHS||'6';
export default function Privacy(){return <main className="public legal-page">
  <Link to="/careers">← Back to opportunities</Link><h1>Candidate privacy notice</h1><p className="muted">Last updated: 16 September 2026</p>
  <p><strong>{controller}</strong>, {address}, is the controller for the recruitment information described here. Contact: <a href={`mailto:${privacyEmail}`}>{privacyEmail}</a>.</p>
  <h2>Information we use</h2><p>We use identity and contact details, CV and employment history, application answers, interview and recruiter notes, communications, availability, right-to-work and suitability information, and technical security records. Please do not provide special-category information unless we specifically request it through an appropriate process.</p>
  <h2>Why and lawful bases</h2><p>We use this information to respond to your application, assess and present you for suitable opportunities with your knowledge, arrange interviews, protect the service, keep regulatory records, and establish or defend legal claims. Depending on the activity, our bases are steps at your request before a contract, legitimate interests in operating a fair recruitment service, and legal obligations. Where the law requires consent for a particular activity, we ask separately and you may withdraw it.</p>
  <h2>AI-assisted screening</h2><p>AI may organise job-relevant evidence and suggest a match score or interview questions. It must not infer protected characteristics or make the final decision. A recruiter reviews the source evidence and remains responsible for every progression, rejection and submission decision. You may ask for an explanation or human reconsideration by contacting us.</p>
  <h2>Who receives information</h2><p>Authorised recruitment staff, the client connected to the vacancy, and contracted technology providers may receive only what they need. We do not sell candidate information. We do not submit your identifiable profile to an unrelated client without informing you. Suppliers that process information for us must be covered by appropriate contracts.</p>
  <h2>International transfers</h2><p>Where a supplier processes information outside the UK, we use an approved transfer mechanism and assess the safeguards that apply. Contact us for details relevant to your application.</p>
  <h2>Retention</h2><p>Unsuccessful application records are normally reviewed for deletion or anonymisation after {retention} months, unless a longer period is necessary for a live opportunity, legal obligation, dispute, or you ask us to retain your profile for future roles. Placement and statutory recruitment records may be kept for the period required by law and our documented schedule.</p>
  <h2>Your rights</h2><p>You may ask for access, correction, deletion, restriction, portability, objection, or information about automated processing where applicable. You can complain to the UK Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer">ico.org.uk</a>. We would appreciate the opportunity to address your concern first.</p>
  <h2>Recruitment communications</h2><p>Messages about an application are service communications. We only send separate vacancy marketing where permitted, record your preference, and provide a simple opt-out. Opting out of marketing does not stop essential messages about an active application.</p>
  <h2>Security and required information</h2><p>We use access controls, audit records and private document storage. You do not have to provide information, but we may be unable to assess an application without the fields marked as required.</p>
</main>}
