import {useEffect} from 'react';import {Link} from 'react-router-dom';import {setSeo} from '../lib/seo';
export default function Privacy(){useEffect(()=>setSeo({title:'Privacy notice | Vorlen',description:'How personal information is handled when using Vorlen recruitment services and candidate application features.',path:'/privacy'}),[]);return <div className="legal-public"><header><Link to="/" className="marketing-brand"><span>V</span><strong>Vorlen</strong></Link><Link to="/careers">Careers</Link></header><main><div className="legal-kicker">PRIVACY</div><h1>Privacy notice</h1><p className="legal-lead">This notice explains how Vorlen processes personal information as a recruitment agency, including candidate sourcing, applications, client introductions, recruiter access and AI-assisted screening.</p>
<section><h2>Information processed</h2><p>Recruitment records can include identity and contact details, CV and employment history, application answers, interview information, communications, recruiter notes and information supplied during the recruitment process. Recruitment businesses should avoid collecting information that is not necessary for the role.</p></section>
<section><h2>How information is used</h2><p>Information is used to administer applications and talent pools, assess job-related experience, communicate about recruitment activity, arrange interviews, make authorised client submissions, maintain security and audit records, and meet applicable legal obligations. Vorlen must identify and document an appropriate lawful basis for each processing purpose and use candidate information only where the purpose is compatible with recruitment or another lawful obligation.</p></section>
<section><h2>Recruiters and international access</h2><p>Authorised recruiters and service providers may work from outside the UK. Where candidate information is made accessible to a separate organisation or contractor outside the UK and the UK international-transfer rules apply, access must not be enabled until the recruitment business has documented an applicable transfer mechanism and any required data protection test or transfer risk assessment. Overseas recruiter access is subject to account controls and can be revoked.</p></section>
<section><h2>CV security</h2><p>CV files are stored privately. Authorised staff receive time-limited links rather than permanent public file addresses. Access may be logged for security, compliance and investigation purposes. Users must not download, copy or disclose candidate information beyond the recruitment purpose for which access was granted.</p></section>
<section><h2>Recruitment technology and AI</h2><p>Vorlen includes tools that assist recruiters with organising and reviewing job-related evidence. AI screening is decision support only: it is not intended to make final hiring or rejection decisions. A human recruiter remains responsible for reviewing relevant evidence and making or approving recruitment decisions; Vorlen does not use an AI score alone to reject or introduce a candidate. Candidates may ask for an explanation, challenge an AI-assisted outcome and request human review. Vorlen should maintain a documented DPIA and regularly test recruitment AI for accuracy, bias and discriminatory effects before and during use.</p></section>
<section><h2>Sharing with prospective employers</h2><p>Candidate information may be shared with a prospective employer where there is an appropriate recruitment purpose and the recruitment business has the necessary authority and lawful basis. Candidate information must not be sold or used for unrelated purposes.</p></section>
<section><h2>Retention and deletion</h2><p>We keep recruitment records for the periods required by law and no longer than necessary for their purposes. Where Vorlen takes action to find work, Conduct Regulations records are retained for at least one year after the last work-finding service. A statutory retention hold can therefore limit an erasure request during that period; any refusal or partial refusal must be explained. After legal and other justified retention needs expire, records are reviewed for deletion or anonymisation.</p></section>
<section><h2>Your rights and contact</h2><p>For recruitment services operated by Vorlen, Vorlen is responsible for its controller obligations. The configured legal identity and privacy contact must be available before vacancies can be published. Use the privacy contact provided in the vacancy or recruitment communication to exercise applicable data-protection rights or raise a concern.</p></section>
<p className="legal-note">Vorlen maintains technical and operational controls to support its recruitment-law and data-protection obligations. Where a separate hirer receives candidate information, that hirer has its own responsibilities for the information it receives.</p></main></div>}
