import {useEffect,useState} from 'react';
import {useParams,useNavigate} from 'react-router-dom';
import {ArrowLeft,Brain,Send,PhoneCall,CheckCircle2,FileText} from 'lucide-react';
import {Badge,Button,Card,Spinner} from '../components/Ui';
import {supabase} from '../lib/supabase';
export default function RecruiterWorkspace(){
 const {id}=useParams();const nav=useNavigate();const [c,setC]=useState<any>();const [apps,setApps]=useState<any[]>([]),[app,setApp]=useState<any>();const [job,setJob]=useState<any>(),[client,setClient]=useState<any>(),[report,setReport]=useState<any>(),[submission,setSubmission]=useState<any>(),[resume,setResume]=useState('');const [notes,setNotes]=useState(''),[outcome,setOutcome]=useState('qualified'),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');const [recipient,setRecipient]=useState(''),[summary,setSummary]=useState(''),[includeContact,setIncludeContact]=useState(true),[reviewed,setReviewed]=useState(false);
 async function load(applicationId?:string){if(!id)return;const {data,error}=await supabase.functions.invoke('recruiter-workspace-data',{body:{candidate_id:id,application_id:applicationId}});if(error){setMsg(error.message||'Unable to load recruiter workspace.');return}setC(data?.candidate);setApps(data?.applications||[]);setApp(data?.application||null);setJob(data?.job||null);setClient(data?.client||data?.job?.client||null);setReport(data?.report||null);setSubmission(data?.submission||null);setResume(data?.resume_url||'');setRecipient(data?.client?.email||data?.job?.client?.email||'');setSummary(data?.submission?.recruiter_summary||data?.report?.summary||data?.application?.cover_note||'');setReviewed(false)}useEffect(()=>{void load()},[id]);
 async function screen(){if(!id||!app)return;setBusy('screen');const {data,error}=await supabase.functions.invoke('ai-screen-candidate',{body:{candidate_id:id,application_id:app.id}});setBusy('');if(error){setMsg(error.message||'AI screening failed.');return}setReport(data);setSummary(data?.summary||summary);setMsg('AI screening complete. Review the evidence before deciding.');await load(app.id)}
 async function saveCall(){if(!c||!app)return;setBusy('call');const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('call_notes').insert({company_id:c.company_id,candidate_id:c.id,application_id:app.id,recruiter_id:user?.id,outcome,notes});if(!error){await supabase.from('applications').update({status:outcome==='qualified'?'qualified':outcome==='not_suitable'?'rejected':'screening'}).eq('id',app.id);const stage=outcome==='qualified'?'qualified':outcome==='not_suitable'?'rejected':'screening';await supabase.from('candidates').update({stage,notes:notes||c.notes}).eq('id',c.id);setMsg('Screening call saved for this application.');setNotes('');await load(app.id)}else setMsg(error.message);setBusy('')}
 async function submit(){if(!app||!recipient||!summary.trim()||!reviewed)return setMsg('Review the submission, confirm the recipient and tick recruiter review before sending.');setBusy('submit');const {data,error}=await supabase.functions.invoke('submit-candidate-to-client',{body:{application_id:app.id,recipient_email:recipient,recruiter_summary:summary,key_strengths:report?.strengths||[],concerns:report?.gaps||[],include_contact_details:includeContact,review_confirmed:true}});setBusy('');if(error){setMsg(error.message||'Client submission failed.');return}setMsg(data?.already_processed?'This reviewed submission has already been processed.':'Reviewed submission sent and recorded.');await load(app.id)}
 if(!c)return <div className="page"><Spinner/>{msg&&<div className="notice">{msg}</div>}</div>;return <div className="page"><div className="page-actions"><div><button className="link-button" onClick={()=>nav('/candidates')}><ArrowLeft size={15}/> Candidates</button><h2>{c.full_name}</h2><p>Application-specific recruiter workspace</p></div><Badge tone={c.stage==='placed'?'green':'blue'}>{c.stage}</Badge></div>{msg&&<div className="notice">{msg}</div>}
 {apps.length>1&&<Card><label>Application<select value={app?.id||''} onChange={e=>void load(e.target.value)}>{apps.map(a=><option key={a.id} value={a.id}>{a.job?.title||'Role'} — {new Date(a.submitted_at).toLocaleDateString('en-GB')} — {a.status}</option>)}</select></label></Card>}
 <div className="workspace-grid"><Card><h3>Candidate evidence</h3><p><strong>Email</strong><br/>{c.email}</p><p><strong>Role</strong><br/>{job?.title||'—'}</p><p><strong>Application status</strong><br/>{app?.status||'—'}</p>{resume?<p><a className="text-link" href={resume} target="_blank" rel="noreferrer"><FileText size={15}/> Open CV (5-minute secure link)</a></p>:<p className="muted">No CV uploaded.</p>}<p><strong>Application answers</strong></p><pre className="answer-box">{JSON.stringify(app?.answers||{},null,2)}</pre></Card>
 <Card><div className="card-heading"><div><h3>AI screening</h3><p>Decision support only. Recruiter review is mandatory.</p></div><Button disabled={!app||busy==='screen'} onClick={screen}><Brain size={15}/>{busy==='screen'?'Screening…':'Run for this application'}</Button></div>{report?<><div className="score-ring">{report.score}<small>/100</small></div><p>{report.summary}</p><h4>Strengths</h4><ul>{(report.strengths||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul><h4>Gaps / verify</h4><ul>{(report.gaps||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></>:<p className="muted">No AI report for this application.</p>}</Card>
 <Card><h3><PhoneCall size={17}/> Recruiter screening call</h3><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="qualified">Qualified</option><option value="follow_up">Follow up</option><option value="not_suitable">Not suitable</option><option value="no_answer">No answer</option></select></label><label>Call notes<textarea rows={8} value={notes} onChange={e=>setNotes(e.target.value)}/></label><Button disabled={!app||busy==='call'} onClick={saveCall}><CheckCircle2 size={15}/> Save against this application</Button></Card>
 <Card><h3>Client submission review</h3><p><strong>Client:</strong> {client?.company_name||'—'}<br/><strong>Role:</strong> {job?.title||'—'}</p><label>Recipient email<input type="email" value={recipient} onChange={e=>{setRecipient(e.target.value);setReviewed(false)}}/></label><label>Submission summary<textarea rows={8} value={summary} onChange={e=>{setSummary(e.target.value);setReviewed(false)}} placeholder="Write exactly what the client should receive."/></label><label className="checkbox"><input type="checkbox" checked={includeContact} onChange={e=>setIncludeContact(e.target.checked)}/> Include candidate contact details</label><label className="checkbox"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I have reviewed this submission and recipient and approve sending it.</label><Button disabled={!app||!recipient||!summary.trim()||!reviewed||busy==='submit'||!!submission} onClick={submit}><Send size={15}/>{submission?'Already submitted':busy==='submit'?'Sending…':'Send reviewed submission'}</Button></Card></div></div>