import {useEffect,useMemo,useState} from 'react';
import {Archive,ArrowLeft,Forward,Inbox,Link2,Mail,MailOpen,Paperclip,RefreshCw,Reply,Search,Send,Star,StarOff,X} from 'lucide-react';
import {Button} from '../components/Ui';import {supabase} from '../lib/supabase';

type Thread={id:string;subject:string;last_message_at:string;last_message_preview?:string;message_count:number;unread_count:number;is_starred:boolean;is_archived:boolean;client_id?:string;candidate_id?:string;job_id?:string};
type Message={id:string;thread_id:string;direction:'inbound'|'outbound';sender:string;recipients:string[];cc:string[];bcc:string[];subject:string;text_body?:string;html_body?:string;sent_at:string;received_at?:string;is_read:boolean;has_attachments?:boolean};
type Attachment={id:string;message_id:string;filename:string;content_type?:string;size_bytes?:number;provider_attachment_id?:string};

const fmt=(v:string)=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const split=(v:string)=>v.split(/[;,]/).map(x=>x.trim()).filter(Boolean);
const emailDocument=(html:string)=>{const clean=String(html||'').replace(/<script[\s\S]*?<\/script\s*>/gi,'').replace(/<iframe[\s\S]*?<\/iframe\s*>/gi,'').replace(/<object[\s\S]*?<\/object\s*>/gi,'').replace(/<embed[^>]*>/gi,'').replace(/\son\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,'').replace(/javascript\s*:/gi,'');return '<!doctype html><html><head><meta charset="utf-8"><meta name="referrer" content="no-referrer"><base target="_blank"><style>html{color-scheme:light}body{margin:0;padding:2px 0;font:14px/1.55 Arial,Helvetica,sans-serif;color:#17201d;background:#fff;overflow-wrap:anywhere}img{max-width:100%;height:auto}table{max-width:100%}a{color:#0b6b55}</style></head><body>'+clean+'</body></html>'};

export default function StaffInbox(){
 const[threads,setThreads]=useState<Thread[]>([]),[selected,setSelected]=useState(''),[messages,setMessages]=useState<Message[]>([]),[attachments,setAttachments]=useState<Attachment[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState<'inbox'|'unread'|'starred'|'archive'>('inbox'),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState(''),[compose,setCompose]=useState(false),[replyMode,setReplyMode]=useState<'reply'|'forward'|null>(null);
 const[to,setTo]=useState(''),[cc,setCc]=useState(''),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[files,setFiles]=useState<File[]>([]),[linkOpen,setLinkOpen]=useState(false),[clients,setClients]=useState<any[]>([]),[candidates,setCandidates]=useState<any[]>([]),[jobs,setJobs]=useState<any[]>([]);
 async function loadThreads(){setLoading(true);setError('');let q=supabase.from('staff_email_threads').select('*').order('last_message_at',{ascending:false}).limit(250);if(filter==='archive')q=q.eq('is_archived',true);else q=q.eq('is_archived',false);if(filter==='unread')q=q.gt('unread_count',0);if(filter==='starred')q=q.eq('is_starred',true);const{data,error:e}=await q;if(e)setError(e.message);else setThreads((data||[]) as Thread[]);setLoading(false)}
 async function openThread(id:string){setSelected(id);const[{data:m,error:e},{data:a}]=await Promise.all([supabase.from('staff_email_messages').select('*').eq('thread_id',id).order('sent_at'),supabase.from('staff_email_attachments').select('*').in('message_id',(messages.filter(x=>x.thread_id===id).map(x=>x.id).length?messages.filter(x=>x.thread_id===id).map(x=>x.id):['00000000-0000-0000-0000-000000000000']))]);if(e)return setError(e.message);const rows=(m||[]) as Message[];setMessages(rows);const ids=rows.map(x=>x.id);if(ids.length){const{data:aa}=await supabase.from('staff_email_attachments').select('*').in('message_id',ids);setAttachments((aa||[]) as Attachment[])}else setAttachments([]);await supabase.rpc('staff_email_set_thread_state',{p_thread:id,p_read:true});window.dispatchEvent(new Event('staff-email-read'));void loadThreads()}
 useEffect(()=>{void loadThreads()},[filter]);useEffect(()=>{void sync();const timer=window.setInterval(()=>void sync(),60000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{supabase.from('clients').select('id,company_name').order('company_name').then(({data})=>setClients(data||[]));supabase.from('candidates').select('id,full_name').order('full_name').then(({data})=>setCandidates(data||[]));supabase.from('jobs').select('id,title').order('title').then(({data})=>setJobs(data||[]))},[]);
 const shown=useMemo(()=>{const q=query.trim().toLowerCase();return q?threads.filter(t=>(t.subject+' '+(t.last_message_preview||'')).toLowerCase().includes(q)):threads},[threads,query]);
 const thread=threads.find(t=>t.id===selected);
 function startReply(mode:'reply'|'forward'){const last=[...messages].reverse()[0];setReplyMode(mode);setCompose(true);setFiles([]);if(mode==='reply'){setTo(last?.direction==='inbound'?last.sender:(last?.recipients||[])[0]||'');setSubject(/^re:/i.test(thread?.subject||'')?thread?.subject||'':`Re: ${thread?.subject||''}`);setBody('')}else{setTo('');setSubject(/^fwd:/i.test(thread?.subject||'')?thread?.subject||'':`Fwd: ${thread?.subject||''}`);setBody(`\n\n---------- Forwarded conversation ----------\n${messages.map(m=>`From: ${m.sender}\nDate: ${new Date(m.sent_at).toLocaleString('en-GB')}\nSubject: ${m.subject}\n\n${m.text_body||''}`).join('\n\n')}`)}}
 function newMail(){setReplyMode(null);setCompose(true);setTo('');setCc('');setSubject('');setBody('');setFiles([])}
 async function send(){if(!to.trim()||!subject.trim())return setError('Recipient and subject are required.');const total=files.reduce((n,f)=>n+f.size,0);if(total>3*1024*1024)return setError('Attachments must total 3 MB or less for secure web sending.');setError('');const enc=await Promise.all(files.map(f=>new Promise<any>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:f.name,type:f.type||'application/octet-stream',data:String(r.result).split(',')[1]});r.onerror=reject;r.readAsDataURL(f)})));const{data:{session}}=await supabase.auth.getSession();const res=await fetch('/api/staff-mail',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({action:'send',to:split(to),cc:split(cc),subject,body,threadId:replyMode==='reply'?selected:null,inReplyTo:replyMode==='reply'?[...messages].reverse()[0]?.id:null,attachments:enc})});const data=await res.json().catch(()=>({}));if(!res.ok)return setError(data.error||'Email could not be sent.');setCompose(false);await loadThreads();if(data.threadId)await openThread(data.threadId)}
 async function downloadAttachment(a:Attachment){setError('');const{data:{session}}=await supabase.auth.getSession();const r=await fetch('/api/staff-mail',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({action:'attachment',id:a.id})});const d=await r.json().catch(()=>({}));if(!r.ok)return setError(d.error||'Attachment download failed.');const bytes=Uint8Array.from(atob(d.data||''),x=>x.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:d.contentType||a.content_type||'application/octet-stream'})),el=document.createElement('a');el.href=url;el.download=d.filename||a.filename;el.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function sync(){setSyncing(true);setError('');const{data:{session}}=await supabase.auth.getSession();try{const r=await fetch('/api/staff-mail',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({action:'sync'})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Mailbox sync failed (HTTP ${r.status})`);await loadThreads()}catch(e:any){setError(e.message)}finally{setSyncing(false)}}
 async function state(values:any){if(!thread)return;const{error:e}=await supabase.rpc('staff_email_set_thread_state',{p_thread:thread.id,p_read:null,p_starred:values.starred??null,p_archived:values.archived??null});if(e)return setError(e.message);await loadThreads()}
 async function link(kind:'client'|'candidate'|'job',id:string){if(!thread)return;const args:any={p_thread:thread.id,p_client:thread.client_id||null,p_candidate:thread.candidate_id||null,p_job:thread.job_id||null};args['p_'+kind]=id||null;const{error:e}=await supabase.rpc('staff_email_link_thread',args);if(e)return setError(e.message);setLinkOpen(false);await loadThreads()}
 return <div className="page staff-mail-page">
  <div className="mail-top"><div><div className="eyebrow">MANAGEMENT MAIL</div><h2>Inbox</h2><p>Shared Vorlen mailbox · CEO & managers only</p></div><div className="button-row"><Button variant="ghost" onClick={sync} disabled={syncing}><RefreshCw size={15} className={syncing?'spin':''}/> {syncing?'Syncing…':'Sync mail'}</Button><Button onClick={newMail}><Mail size={15}/> New email</Button></div></div>
  {error&&<div className="notice error">{error}</div>}
  <div className="mail-shell">
   <aside className="mail-folders"><button className={filter==='inbox'?'active':''} onClick={()=>setFilter('inbox')}><Inbox size={17}/>Inbox</button><button className={filter==='unread'?'active':''} onClick={()=>setFilter('unread')}><Mail size={17}/>Unread</button><button className={filter==='starred'?'active':''} onClick={()=>setFilter('starred')}><Star size={17}/>Starred</button><button className={filter==='archive'?'active':''} onClick={()=>setFilter('archive')}><Archive size={17}/>Archive</button></aside>
   <section className={'mail-list '+(selected?'mobile-hidden':'')}><div className="mail-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search mail"/></div>{loading?<p className="mail-empty">Loading mail…</p>:shown.map(t=><button key={t.id} className={'mail-list-row '+(t.id===selected?'active ':'')+(t.unread_count?'unread':'')} onClick={()=>void openThread(t.id)}><div className="mail-row-top"><strong>{t.subject||'(no subject)'}</strong><span>{fmt(t.last_message_at)}</span></div><p>{t.last_message_preview||'No preview available'}</p><div className="mail-row-meta">{t.unread_count>0&&<b>{t.unread_count} unread</b>}{t.is_starred&&<Star size={12}/>} {(t.client_id||t.candidate_id||t.job_id)&&<span><Link2 size={11}/> Linked</span>}</div></button>)}{!loading&&!shown.length&&<p className="mail-empty">No messages in this view.</p>}</section>
   <section className={'mail-thread '+(!selected?'mobile-hidden':'')}>{!thread?<div className="mail-welcome"><MailOpen size={34}/><h3>Select a conversation</h3><p>Open an email thread to read, reply, forward or link it to recruitment records.</p></div>:<><header className="mail-thread-head"><button className="mail-back" onClick={()=>setSelected('')}><ArrowLeft size={18}/></button><div><h3>{thread.subject||'(no subject)'}</h3><span>{thread.message_count} message{thread.message_count===1?'':'s'}</span></div><div className="mail-thread-actions"><button title="Star" onClick={()=>void state({starred:!thread.is_starred})}>{thread.is_starred?<StarOff size={17}/>:<Star size={17}/>}</button><button title="Link records" onClick={()=>setLinkOpen(v=>!v)}><Link2 size={17}/></button><button title="Archive" onClick={()=>void state({archived:!thread.is_archived})}><Archive size={17}/></button></div></header>{linkOpen&&<div className="mail-linker"><label>Client<select value={thread.client_id||''} onChange={e=>void link('client',e.target.value)}><option value="">None</option>{clients.map(x=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select></label><label>Candidate<select value={thread.candidate_id||''} onChange={e=>void link('candidate',e.target.value)}><option value="">None</option>{candidates.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label>Vacancy<select value={thread.job_id||''} onChange={e=>void link('job',e.target.value)}><option value="">None</option>{jobs.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label></div>}<div className="mail-messages">{messages.map(m=><article key={m.id} className={'mail-message '+m.direction}><header><div className="mail-avatar">{(m.sender||'?').slice(0,1).toUpperCase()}</div><div><strong>{m.sender}</strong><span>to {(m.recipients||[]).join(', ')}</span></div><time>{fmt(m.sent_at)}</time></header><div className="mail-body">{m.html_body?<iframe className="mail-html-body" title={`Email from ${m.sender}`} sandbox="allow-popups allow-popups-to-escape-sandbox" srcDoc={emailDocument(m.html_body)}/>:<div className="mail-text-body">{m.text_body||'No readable message body was supplied.'}</div>}</div>{attachments.filter(a=>a.message_id===m.id).map(a=><a className="mail-attachment" key={a.id} href={`/api/staff-mail?action=attachment&id=${encodeURIComponent(a.id)}`}><Paperclip size={14}/>{a.filename}<span>{a.size_bytes?Math.ceil(a.size_bytes/1024)+' KB':''}</span></a>)}</article>)}</div><footer className="mail-reply-bar"><Button variant="ghost" onClick={()=>startReply('reply')}><Reply size={15}/> Reply</Button><Button variant="ghost" onClick={()=>startReply('forward')}><Forward size={15}/> Forward</Button></footer></>}</section>
  </div>
  {compose&&<div className="mail-compose-backdrop"><section className="mail-compose"><header><strong>{replyMode==='reply'?'Reply':replyMode==='forward'?'Forward':'New message'}</strong><button onClick={()=>setCompose(false)}><X size={18}/></button></header><label>To<input autoFocus value={to} onChange={e=>setTo(e.target.value)} placeholder="name@example.com"/></label><label>Cc<input value={cc} onChange={e=>setCc(e.target.value)} placeholder="Optional"/></label><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Write your message…"/><div className="mail-file-row"><label className="mail-file-button"><Paperclip size={15}/> Attach<input type="file" multiple hidden onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{files.map(f=><span key={f.name}>{f.name}</span>)}</div><footer><Button onClick={()=>void send()}><Send size={15}/> Send</Button></footer></section></div>}
 </div>
}