import {createClient} from 'npm:@supabase/supabase-js@2.116.0';
import {PDFDocument,StandardFonts,rgb} from 'npm:pdf-lib@1.17.1';

const cors={'Access-Control-Allow-Origin':'https://www.vorlen.co.uk','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'};
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{...cors,'Cache-Control':'no-store'}});
const clean=(s:string)=>s.replace(/\r/g,'').replace(/[\t ]+/g,' ').replace(/\n{3,}/g,'\n\n').trim().slice(0,60000);
const hex=async(bytes:Uint8Array)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
const escRx=(s:string)=>s.replace(/[.*+?^$()|[\]\\{}]/g,'\\$&');
async function extractPdf(bytes:Uint8Array){const DOMMatrix=(await import('npm:@thednp/dommatrix@2.0.12')).default;globalThis.DOMMatrix=DOMMatrix as any;(globalThis as any).process=undefined;try{Object.defineProperty(globalThis.navigator,'platform',{value:'Linux',configurable:true})}catch{}const pdfjs=await import('npm:pdfjs-dist@5.4.149');pdfjs.GlobalWorkerOptions.workerSrc=import.meta.resolve('npm:pdfjs-dist@5.4.149/build/pdf.worker.mjs');const doc=await pdfjs.getDocument({data:bytes,useWorkerFetch:false,isEvalSupported:false}).promise;const parts:string[]=[];try{let chars=0;for(let i=1;i<=doc.numPages&&chars<60000;i++){const page=await doc.getPage(i),tc=await page.getTextContent(),text=tc.items.map((x:any)=>typeof x?.str==='string'?x.str:'').join(' ');parts.push(text);chars+=text.length;page.cleanup()}}finally{await doc.destroy()}return clean(parts.join('\n'))}
async function extractCv(file:Blob,path:string){const bytes=new Uint8Array(await file.arrayBuffer());if(path.toLowerCase().endsWith('.pdf'))return{bytes,text:await extractPdf(bytes)};if(path.toLowerCase().endsWith('.docx')){const mammoth=await import('npm:mammoth@1.8.0');const r=await mammoth.extractRawText({buffer:bytes});return{bytes,text:clean(String(r.value||''))}}throw new Error('Unsupported CV format. Upload a PDF or DOCX CV.')}
function redact(text:string,c:any){let out=text;for(const v of [c.email,c.phone,c.linkedin_url,c.postal_address]){const x=String(v||'').trim();if(x.length>=4)out=out.replace(new RegExp(escRx(x),'gi'),'[withheld by Vorlen]')}out=out.replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'[email withheld by Vorlen]');out=out.replace(/(?:https?:\/\/|www\.)\S+/gi,'[web/profile link withheld by Vorlen]');out=out.replace(/(?:\+?44\s?\(?(?:0\)?\s?)?|0)(?:7\d{3}|1\d{3}|2\d)\s?\d{3,4}\s?\d{3,4}/g,'[phone withheld by Vorlen]');const lines=out.split('\n').map(x=>x.trim()).filter(Boolean);const safe:string[]=[];for(let line of lines){if(/^(e-?mail|phone|mobile|tel(?:ephone)?|linkedin|website|web|address|contact)\s*[:|-]/i.test(line))line='Direct contact details withheld by Vorlen';if(safe[safe.length-1]===line)continue;safe.push(line)}return clean(safe.join('\n'))}
const latin=(s:string)=>s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/[–—]/g,'-').replace(/[•▪◦]/g,'-').replace(/[^\x20-\x7E\xA3\xA0-\xFF\n]/g,'?');
async function makePdf(name:string,text:string){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const W=595,H=842,M=52;let page=pdf.addPage([W,H]),y=H-M;const draw=(t:string,size=10,b=false)=>{const f=b?bold:font;const words=latin(t).split(/\s+/),lines:string[]=[];let line='';for(const w of words){const next=line?line+' '+w:w;if(f.widthOfTextAtSize(next,size)<=W-M*2)line=next;else{if(line)lines.push(line);line=w}}if(line)lines.push(line);for(const l of lines){if(y<58){page=pdf.addPage([W,H]);y=H-M}page.drawText(l,{x:M,y,size,font:f,color:rgb(0.08,0.1,0.14)});y-=size+5}};draw('VORLEN CLIENT-SAFE CV',14,true);draw(name||'Candidate',18,true);draw('Direct contact details and personal profile links are withheld by Vorlen. Please coordinate all contact through Vorlen.',9,false);y-=10;for(const block of text.split('\n')){if(!block.trim()){y-=5;continue}draw(block,10,false)}return await pdf.save()}
async function ensureSafeCv(db:any,s:any,c:any){if(!c.resume_path)throw new Error('No stored CV is available for this candidate.');const{data:file,error}=await db.storage.from('candidate-resumes').download(c.resume_path);if(error||!file)throw new Error('The candidate CV could not be loaded.');const ex=await extractCv(file,c.resume_path),sourceHash=await hex(ex.bytes);if(s.client_safe_cv_path&&s.client_safe_cv_source_hash===sourceHash)return s.client_safe_cv_path;const redacted=redact(ex.text,c);if(redacted.length<80)throw new Error('The candidate CV could not be safely converted for client review.');const pdf=await makePdf(c.full_name||'Candidate',redacted),path=s.company_id+'/'+s.client_id+'/'+s.id+'.pdf';const{error:up}=await db.storage.from('client-safe-cvs').upload(path,pdf,{contentType:'application/pdf',upsert:true,cacheControl:'0'});if(up)throw new Error('The client-safe CV could not be stored.');const now=new Date().toISOString();const{error:ue}=await db.from('candidate_submissions').update({client_safe_cv_path:path,client_safe_cv_generated_at:now,client_safe_cv_source_hash:sourceHash}).eq('id',s.id);if(ue)throw new Error('The client-safe CV record could not be saved.');return path}

Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
  if(req.method!=='POST')return json({error:'Method not allowed'},405);
  try{
    const auth=req.headers.get('Authorization')||'';
    if(!auth.startsWith('Bearer '))return json({error:'Authentication required'},401);
    const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const udb=createClient(url,anon,{global:{headers:{Authorization:auth}}}),db=createClient(url,service);
    const{data:{user}}=await udb.auth.getUser();if(!user)return json({error:'Authentication required'},401);
    const{data:p}=await db.from('profiles').select('company_id,role,client_id').eq('id',user.id).maybeSingle();
    if(!p?.company_id||p.role!=='viewer'||!p.client_id)return json({error:'Client access required'},403);
    const submissionId=String((await req.json())?.submission_id||'');if(!submissionId)return json({error:'Submission required'},400);
    const{data:s}=await db.from('candidate_submissions').select('id,company_id,client_id,candidate_id,status,candidate_authorisation,client_safe_cv_path,client_safe_cv_source_hash').eq('id',submissionId).eq('company_id',p.company_id).eq('client_id',p.client_id).maybeSingle();
    if(!s||['draft','withdrawn','approved_to_send'].includes(String(s.status)))return json({error:'Submission not available'},404);
    if(!String(s.candidate_authorisation||'').trim())return json({error:'Candidate sharing authorisation is not recorded.'},403);
    const{data:c}=await db.from('candidates').select('full_name,email,phone,linkedin_url,postal_address,resume_path').eq('id',s.candidate_id).eq('company_id',p.company_id).maybeSingle();if(!c)return json({error:'Candidate not found'},404);
    const path=await ensureSafeCv(db,s,c);
    const{data:signed,error}=await db.storage.from('client-safe-cvs').createSignedUrl(path,300,{download:(c.full_name||'Candidate')+' - CV.pdf'});if(error||!signed?.signedUrl)return json({error:'CV could not be opened.'},500);
    await db.from('compliance_audit_log').insert({company_id:p.company_id,event_type:'client_safe_cv_viewed',new_state:{viewer_user_id:user.id,client_id:p.client_id,submission_id:s.id,candidate_id:s.candidate_id,expires_in_seconds:300}});
    return json({url:signed.signedUrl,expires_in:300});
  }catch(e){console.error('client-candidate-cv',e);return json({error:e instanceof Error?e.message:'CV could not be opened.'},500)}
});