import {useEffect,useRef} from 'react';import type {ButtonHTMLAttributes,ReactNode} from 'react';
import { Search } from 'lucide-react';
export function Button({children,variant='primary',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{children:ReactNode;variant?:'primary'|'ghost'|'danger'}){return <button {...props} type={props.type||'button'} className={`btn ${variant} ${className} ${props.disabled?'disabled':''}`.trim()}>{children}</button>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'green'|'amber'|'red'|'blue'}){return <span className={`badge ${tone}`}>{children}</span>}
export function StatusBadge({status}:{status?:string|null}){const s=String(status||'unknown').toLowerCase(),tone:'neutral'|'green'|'amber'|'red'|'blue'=s.includes('placed')||s.includes('active')||s.includes('approved')||s.includes('qualified')?'green':s.includes('reject')||s.includes('cancel')||s.includes('void')?'red':s.includes('interview')||s.includes('screen')||s.includes('pending')?'amber':s.includes('submit')||s.includes('received')?'blue':'neutral';return <Badge tone={tone}>{String(status||'Unknown').replaceAll('_',' ')}</Badge>}
export function Card({children,className='' }:{children:ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const el=ref.current;el?.querySelector<HTMLElement>('input,select,textarea,button,a[href]')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'&&el){const items=[...el.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href],[tabindex]:not([tabindex="-1"])')].filter(x=>!x.hasAttribute('disabled'));if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[onClose]);return <div className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal-card" ref={ref} tabIndex={-1}><div className="card-head"><h3>{title}</h3><button type="button" className="close" aria-label="Close" onClick={onClose}>×</button></div>{children}</div></div>}
export function Empty({title,text}:{title:string;text:string}){return <div className="empty"><div className="empty-icon">○</div><h3>{title}</h3><p>{text}</p></div>}
export function Skeleton({width='100%',height=14,className=''}:{width?:string|number;height?:string|number;className?:string}){return <span className={`skeleton ${className}`} style={{width,height}} aria-hidden="true"/>}
export function SkeletonRows({rows=5,count}:{rows?:number;count?:number}){const n=count??rows;return <div className="skeleton-rows" aria-label="Loading">{Array.from({length:n},(_,i)=><div className="skeleton-row" key={i}><Skeleton width={i%2?'42%':'34%'} height={13}/><Skeleton width={i%3?'25%':'31%'} height={13}/><Skeleton width="14%" height={13}/><Skeleton width="18%" height={13}/></div>)}</div>}
export function SkeletonCards({count=4}:{count?:number}){return <div className="skeleton-cards" aria-label="Loading">{Array.from({length:count},(_,i)=><div className="card skeleton-card" key={i}><Skeleton width="45%" height={18}/><Skeleton width="70%" height={12}/><Skeleton width="92%" height={12}/><Skeleton width="64%" height={12}/></div>)}</div>}
export function Spinner(){return <div className="skeleton-loader" aria-label="Loading"><Skeleton width="38%" height={18}/><Skeleton width="72%" height={13}/><Skeleton width="58%" height={13}/><Skeleton width="84%" height={13}/></div>}
export function SearchBox({value,onChange,placeholder='Search…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="search"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
