import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const enc=new TextEncoder();const hex=(b:ArrayBuffer)=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const sha=async(s:string)=>hex(await crypto.subtle.digest('SHA-256',enc.encode(s)));
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const emailShell=(title:string,body:string)=>`<!doctype html><html><body style="margin:0;background:#f2f5f3;font-family:Arial,Helvetica,sans-serif;color:#10201d"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:34px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;margin:0 auto;background:#fff;border:1px solid #d9e2de"><tr><td style="padding:28px 34px;background:#10201d"><div style="font-size:19px;font-weight:800;letter-spacing:4px;color:#fff">VORLEN</div><div style="margin-top:5px;font-size:10px;letter-spacing:1.7px;color:#8fe3c2">CLIENT TERMS</div></td></tr><tr><td style="padding:36px 34px"><h1 style="margin:0 0 22px;font-size:27px;line-height:1.15;color:#10201d">${title}</h1>${body}</td></tr><tr><td style="padding:22px 34px;border-top:1px solid #e4ebe8;color:#6a7b75;font-size:11px;line-height:1.6">Vorlen · VORLEN T/A IVY AND PEARLS LTD · Company No. 17387520<br><a href="https://www.vorlen.co.uk" style="color:#0b6b55">www.vorlen.co.uk</a> · billing@vorlen.co.uk</td></tr></table></td></tr></table></body></html>`;
const terms=(c:any,company:any,v:string)=>`VORLEN TERMS OF BUSINESS — ${v}\n\nSupplier: ${company.name}\nLegal entity: ${company.legal_name}\nCompany number: ${company.company_registration_number}\nClient: ${c.company_name}\nNature of business: ${c.business_nature||'Not recorded'}\n\n1. Engagement. The Client instructs Vorlen to introduce candidates for permanent recruitment assignments agreed between the parties.\n2. Introduction fee. The recruitment fee is ${c.recruitment_fee_percent}% of the candidate's agreed first-year gross remuneration unless a separately signed schedule states otherwise.\n3. Payment. Invoices are due within ${c.payment_terms_days} days of invoice date.\n4. Rebate / replacement. ${c.rebate_terms||'No rebate or replacement terms have been agreed.'}\n5. Candidate information. Candidate information supplied by Vorlen is confidential and must be used only for the relevant recruitment purpose and handled in accordance with applicable data-protection law.\n6. Hiring following introduction. If the Client or an associated organisation engages a candidate introduced by Vorlen, the agreed introduction fee is payable, subject to any separately agreed written variation.\n7. Client responsibilities. The Client is responsible for the accuracy of vacancy information, the recruitment decision, right-to-work and other role-specific checks that are legally its responsibility, and for promptly informing Vorlen of an engagement.\n8. Entire commercial agreement. These Terms together with the recorded fee, payment and rebate/replacement terms form the commercial basis for the assignment. Any variation must be agreed in writing.\n9. Acceptance. By selecting “Accept Terms of Business”, the authorised client representative confirms authority to accept these terms for the Client and agrees to this exact version.\n\nPrivacy: ${company.privacy_email||'privacy@vorlen.co.uk'}\nBilling: ${company.billing_email||'billing@vorlen.co.uk'}`;
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,db=createClient(url,service);
 try{
  const u=new URL(req.url); const token=u.searchParams.get('token')||''; const action=u.searchParams.get('action')||'';
  if(req.method==='GET'&&token){const h=await sha(token);const{data:d}=await db.from('client_terms_documents').select('id,version,status,terms_text,recipient_name,recipient_email,token_expires_at,client_id,clients(company_name)').eq('public_token_hash',h).maybeSingle();if(!d||!d.token_expires_at||new Date(d.token_expires_at)<=new Date()||!['sent','viewed'].includes(d.status))return json({error:'This Terms of Business link is invalid or has expired.'},410);if(d.status==='sent')await db.from('client_terms_documents').update({status:'viewed',viewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',d.id);return json({document:{...d,public_token_hash:undefined}})}
  if(req.method==='POST'&&token&&action==='accept'){const h=await sha(token),body=await req.json();const{data:d}=await db.from('client_terms_documents').select('id,status,token_expires_at').eq('public_token_hash',h).maybeSingle();if(!d||!d.token_expires_at||new Date(d.token_expires_at)<=new Date()||!['sent','viewed'].includes(d.status))return json({error:'This Terms of Business link is invalid, expired or already completed.'},409);const name=String(body.name||'').trim();if(name.length<2||body.confirm!==true)return json({error:'Name and explicit acceptance are required.'},400);const ip=(req.headers.get('x-forwarded-for')||'').split(',')[0].trim()||null,ua=req.headers.get('user-agent');const{data:accepted,error}=await db.rpc('service_accept_client_terms',{p_document:d.id,p_name:name,p_ip:ip,p_user_agent:ua});if(error){const msg=error.message||'Terms acceptance could not be completed.';const conflict=/already been completed|expired/i.test(msg);return json({error:msg},conflict?409:500)}return json(accepted||{ok:true})}
  const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Unauthorized'},401);const userClient=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const{data:{user}}=await userClient.auth.getUser();if(!user)return json({error:'Unauthorized'},401);const{data:p}=await db.from('profiles').select('company_id,role').eq('id',user.id).maybeSingle();if(!p)return json({error:'Forbidden'},403);
  const body=await req.json();if(body.action!=='send')return json({error:'Unsupported action'},400);
  let partnerSend=false;
  if(p.role==='partner'){
    const[{data:pp},{data:o},{data:a}]=await Promise.all([
      db.from('partner_profiles').select('specialism,active').eq('user_id',user.id).eq('company_id',p.company_id).maybeSingle(),
      db.from('partner_onboarding').select('status').eq('partner_id',user.id).eq('company_id',p.company_id).maybeSingle(),
      db.from('partner_assignments').select('id').eq('partner_id',user.id).eq('company_id',p.company_id).eq('client_id',body.client_id).is('completed_at',null).limit(1).maybeSingle()
    ]);
    partnerSend=!!pp?.active&&o?.status==='active'&&['lead_closer','hybrid'].includes(pp?.specialism||'')&&!!a;
  }
  if(!['owner','manager'].includes(p.role)&&!partnerSend)return json({error:'Only an assigned Lead Closer or Hybrid Partner may send manager-authorised client terms.'},403);
  const{data:c}=await db.from('clients').select('*').eq('id',body.client_id).eq('company_id',p.company_id).maybeSingle();if(!c)return json({error:'Client not found'},404);if(c.terms_accepted_at)return json({error:'The client has already accepted the current Terms of Business. Clear/supersede the acceptance and prepare revised terms before sending another version.'},409);if(!c.email||!c.contact_name||!c.business_nature||!c.recruitment_fee_percent||!c.payment_terms_days||!c.rebate_terms)return json({error:'Complete the client contact, business nature, fee, payment and rebate/replacement terms before sending.'},400);const emailNorm=String(c.email||'').trim().toLowerCase(),phoneNorm=String(c.phone||'').replace(/[^0-9]/g,'');const[{data:clientSupp},{data:emailSupp},{data:phoneSupp},{data:dncActivity}]=await Promise.all([db.from('b2b_call_suppressions').select('id').eq('company_id',p.company_id).eq('client_id',c.id).limit(1).maybeSingle(),emailNorm?db.from('b2b_call_suppressions').select('id').eq('company_id',p.company_id).eq('email_normalized',emailNorm).limit(1).maybeSingle():Promise.resolve({data:null}),phoneNorm?db.from('b2b_call_suppressions').select('id').eq('company_id',p.company_id).eq('phone_normalized',phoneNorm).limit(1).maybeSingle():Promise.resolve({data:null}),db.from('partner_client_activity').select('id').eq('company_id',p.company_id).eq('client_id',c.id).eq('status','do_not_contact').limit(1).maybeSingle()]);if(clientSupp||emailSupp||phoneSupp||dncActivity)return json({error:'This client is marked do not contact. Terms were not sent.'},409);
  if(partnerSend){
    const{data:allowed,error:allowError}=await userClient.rpc('partner_terms_send_allowed',{p_client:c.id});
    if(allowError||allowed!==true)return json({error:'Vorlen management must authorise the current commercial terms before a partner can send them.'},403);
  }
  const{data:company}=await db.from('companies').select('name,legal_name,company_registration_number,privacy_email,billing_email,trading_name').eq('id',p.company_id).single();const version='client-tob-2026-09-21';const text=terms(c,company,version);const hash=await sha(text);const raw=crypto.randomUUID()+crypto.randomUUID().replaceAll('-','');const th=await sha(raw),expires=new Date(Date.now()+7*864e5).toISOString();
  await db.from('client_terms_documents').update({status:'superseded',updated_at:new Date().toISOString()}).eq('client_id',c.id).in('status',['draft','sent','viewed']);
  const{data:d,error}=await db.from('client_terms_documents').insert({company_id:p.company_id,client_id:c.id,version,status:'sent',terms_snapshot:{company_name:c.company_name,business_nature:c.business_nature,recruitment_fee_percent:c.recruitment_fee_percent,payment_terms_days:c.payment_terms_days,rebate_terms:c.rebate_terms},terms_text:text,content_hash:hash,recipient_name:c.contact_name,recipient_email:c.email,public_token_hash:th,token_expires_at:expires,sent_at:new Date().toISOString(),created_by:user.id}).select().single();if(error)return json({error:error.message},500);
  const app='https://www.vorlen.co.uk';const link=`${app}/terms/accept?token=${encodeURIComponent(raw)}`;const key=Deno.env.get('RESEND_API_KEY');if(!key){await db.from('client_terms_documents').update({status:'draft',updated_at:new Date().toISOString()}).eq('id',d.id);return json({error:'Transactional email is not configured.'},503)}
  const er=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({from:'Vorlen <contact@vorlen.co.uk>',to:[c.email],reply_to:company.billing_email||'billing@vorlen.co.uk',subject:`Vorlen Terms of Business — ${c.company_name}`,html:emailShell('Terms of Business for '+esc(c.company_name),`<p style="margin:0 0 18px;font-size:15px;line-height:1.7">Dear ${esc(c.contact_name)},</p><p style="margin:0 0 24px;font-size:15px;line-height:1.7">Please review the Vorlen Terms of Business and the commercial terms recorded for ${esc(c.company_name)}.</p><p style="margin:26px 0"><a href="${link}" style="display:inline-block;padding:13px 20px;background:#0b6b55;color:#fff;text-decoration:none;font-weight:700;border-radius:999px">Review and accept terms</a></p><p style="margin:0;color:#667972;font-size:13px;line-height:1.6">This secure link expires in 7 days. If anything needs changing, reply before accepting the terms.</p>`)})});const ej=await er.json();if(!er.ok){await db.from('client_terms_documents').update({status:'draft',updated_at:new Date().toISOString()}).eq('id',d.id);const detail=ej?.message||ej?.name||'Email provider rejected the request';return json({error:'Unable to send Terms of Business email.',detail},er.status>=400&&er.status<500?424:502)}await db.from('client_terms_documents').update({resend_message_id:ej.id,updated_at:new Date().toISOString()}).eq('id',d.id);return json({ok:true,document_id:d.id,expires_at:expires});
 }catch(e){return json({error:e instanceof Error?e.message:'Unexpected error'},500)}
});