import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const enc=new TextEncoder();const hex=(b:ArrayBuffer)=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const sha=async(s:string)=>hex(await crypto.subtle.digest('SHA-256',enc.encode(s)));
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const terms=(c:any,company:any,v:string)=>`VORLEN TERMS OF BUSINESS — ${v}\n\nSupplier: ${company.name}\nLegal entity: ${company.legal_name}\nCompany number: ${company.company_registration_number}\nClient: ${c.company_name}\nNature of business: ${c.business_nature||'Not recorded'}\n\n1. Engagement. The Client instructs Vorlen to introduce candidates for permanent recruitment assignments agreed between the parties.\n2. Introduction fee. The recruitment fee is ${c.recruitment_fee_percent}% of the candidate's agreed first-year gross remuneration unless a separately signed schedule states otherwise.\n3. Payment. Invoices are due within ${c.payment_terms_days} days of invoice date.\n4. Rebate / replacement. ${c.rebate_terms||'No rebate or replacement terms have been agreed.'}\n5. Candidate information. Candidate information supplied by Vorlen is confidential and must be used only for the relevant recruitment purpose and handled in accordance with applicable data-protection law.\n6. Hiring following introduction. If the Client or an associated organisation engages a candidate introduced by Vorlen, the agreed introduction fee is payable, subject to any separately agreed written variation.\n7. Client responsibilities. The Client is responsible for the accuracy of vacancy information, the recruitment decision, right-to-work and other role-specific checks that are legally its responsibility, and for promptly informing Vorlen of an engagement.\n8. Entire commercial agreement. These Terms together with the recorded fee, payment and rebate/replacement terms form the commercial basis for the assignment. Any variation must be agreed in writing.\n9. Acceptance. By selecting “Accept Terms of Business”, the authorised client representative confirms authority to accept these terms for the Client and agrees to this exact version.\n\nPrivacy: ${company.privacy_email||'privacy@vorlen.co.uk'}\nBilling: ${company.billing_email||'billing@vorlen.co.uk'}`;
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,db=createClient(url,service);
 try{
  const u=new URL(req.url); const token=u.searchParams.get('token')||''; const action=u.searchParams.get('action')||'';
  if(req.method==='GET'&&token){const h=await sha(token);const{data:d}=await db.from('client_terms_documents').select('id,version,status,terms_text,recipient_name,recipient_email,token_expires_at,client_id,clients(company_name)').eq('public_token_hash',h).maybeSingle();if(!d||!d.token_expires_at||new Date(d.token_expires_at)<=new Date()||!['sent','viewed'].includes(d.status))return json({error:'This Terms of Business link is invalid or has expired.'},410);if(d.status==='sent')await db.from('client_terms_documents').update({status:'viewed',viewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',d.id);return json({document:{...d,public_token_hash:undefined}})}
  if(req.method==='POST'&&token&&action==='accept'){const h=await sha(token),body=await req.json();const{data:d}=await db.from('client_terms_documents').select('*').eq('public_token_hash',h).maybeSingle();if(!d||!d.token_expires_at||new Date(d.token_expires_at)<=new Date()||!['sent','viewed'].includes(d.status))return json({error:'This Terms of Business link is invalid, expired or already completed.'},409);const name=String(body.name||'').trim();if(name.length<2||body.confirm!==true)return json({error:'Name and explicit acceptance are required.'},400);const now=new Date().toISOString(),ip=(req.headers.get('x-forwarded-for')||'').split(',')[0].trim()||null,ua=req.headers.get('user-agent');const{error}=await db.from('client_terms_documents').update({status:'accepted',accepted_at:now,accepted_name:name,accepted_email:d.recipient_email,acceptance_ip:ip,acceptance_user_agent:ua,acceptance_method:'secure_link',updated_at:now}).eq('id',d.id).in('status',['sent','viewed']);if(error)return json({error:error.message},500);await db.from('clients').update({terms_version:d.version,terms_accepted_at:now,terms_accepted_by:name,terms_acceptance_method:'secure_link',terms_evidence:'Accepted secure Terms of Business document '+d.id}).eq('id',d.client_id).eq('company_id',d.company_id);return json({ok:true,accepted_at:now,version:d.version})}
  const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Unauthorized'},401);const userClient=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const{data:{user}}=await userClient.auth.getUser();if(!user)return json({error:'Unauthorized'},401);const{data:p}=await db.from('profiles').select('company_id,role').eq('id',user.id).maybeSingle();if(!p||!['owner','manager'].includes(p.role))return json({error:'Forbidden'},403);
  const body=await req.json();if(body.action!=='send')return json({error:'Unsupported action'},400);const{data:c}=await db.from('clients').select('*').eq('id',body.client_id).eq('company_id',p.company_id).maybeSingle();if(!c)return json({error:'Client not found'},404);if(!c.email||!c.contact_name||!c.business_nature||!c.recruitment_fee_percent||!c.payment_terms_days||!c.rebate_terms)return json({error:'Complete the client contact, business nature, fee, payment and rebate/replacement terms before sending.'},400);
  const{data:company}=await db.from('companies').select('name,legal_name,company_registration_number,privacy_email,billing_email,trading_name').eq('id',p.company_id).single();const version='client-tob-2026-09-21';const text=terms(c,company,version);const hash=await sha(text);const raw=crypto.randomUUID()+crypto.randomUUID().replaceAll('-','');const th=await sha(raw),expires=new Date(Date.now()+7*864e5).toISOString();
  await db.from('client_terms_documents').update({status:'superseded',updated_at:new Date().toISOString()}).eq('client_id',c.id).in('status',['draft','sent','viewed']);
  const{data:d,error}=await db.from('client_terms_documents').insert({company_id:p.company_id,client_id:c.id,version,status:'sent',terms_snapshot:{company_name:c.company_name,business_nature:c.business_nature,recruitment_fee_percent:c.recruitment_fee_percent,payment_terms_days:c.payment_terms_days,rebate_terms:c.rebate_terms},terms_text:text,content_hash:hash,recipient_name:c.contact_name,recipient_email:c.email,public_token_hash:th,token_expires_at:expires,sent_at:new Date().toISOString(),created_by:user.id}).select().single();if(error)return json({error:error.message},500);
  const app='https://www.vorlen.co.uk';const link=`${app}/terms/accept?token=${encodeURIComponent(raw)}`;const key=Deno.env.get('RESEND_API_KEY');if(!key){await db.from('client_terms_documents').update({status:'draft',updated_at:new Date().toISOString()}).eq('id',d.id);return json({error:'Transactional email is not configured.'},503)}
  const er=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({from:'Vorlen <contact@vorlen.co.uk>',to:[c.email],reply_to:company.billing_email||'billing@vorlen.co.uk',subject:`Vorlen Terms of Business — ${c.company_name}`,html:`<p>Dear ${esc(c.contact_name)},</p><p>Please review the Vorlen Terms of Business and the commercial terms agreed for ${esc(c.company_name)}.</p><p><a href="${link}">Review and accept Terms of Business</a></p><p>This secure link expires in 7 days. If anything needs changing, please reply before accepting.</p><p>Kind regards,<br>Vorlen</p>`})});const ej=await er.json();if(!er.ok){await db.from('client_terms_documents').update({status:'draft',updated_at:new Date().toISOString()}).eq('id',d.id);const detail=ej?.message||ej?.name||'Email provider rejected the request';return json({error:'Unable to send Terms of Business email.',detail},er.status>=400&&er.status<500?424:502)}await db.from('client_terms_documents').update({resend_message_id:ej.id,updated_at:new Date().toISOString()}).eq('id',d.id);return json({ok:true,document_id:d.id,expires_at:expires});
 }catch(e){return json({error:e instanceof Error?e.message:'Unexpected error'},500)}
});