import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.0';
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{...cors,'Content-Type':'application/json'}});
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const ct=req.headers.get('content-type')||''; const body=ct.includes('multipart/form-data')?Object.fromEntries(await (await req.formData()).entries()):await req.json();
 if(body.website)return json({ok:true});
 const required=['job_id','full_name','email']; for(const k of required) if(!body[k])throw new Error(`Missing ${k}`);
 if(body.consent!=='true' && body.consent!==true)throw new Error('Privacy acknowledgement is required');\n if(body.terms_agreed!=='true' && body.terms_agreed!==true)throw new Error('Work-seeker terms must be agreed before recruitment services begin');
 const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
 const forwarded=req.headers.get('cf-connecting-ip')||req.headers.get('x-real-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';
 const rateKey=`application:${forwarded}:${body.job_id}`; const allowed=await supabase.rpc('check_application_rate_limit',{p_key:rateKey,p_limit:10,p_window_seconds:3600}); if(allowed.error||allowed.data!==true)throw new Error('Too many applications from this network. Please try again later.');
 const email=String(body.email).trim().toLowerCase(); const fullName=String(body.full_name).trim();
 if(fullName.length<2||fullName.length>160)throw new Error('Full name must be between 2 and 160 characters');
 if(email.length>254||!/^\S+@\S+\.\S+$/.test(email))throw new Error('Invalid email');
 for(const [label,value,max] of [['phone',body.phone,40],['location',body.location,160],['cover note',body.cover_note,10000]] as const){if(value&&String(value).length>max)throw new Error(`${label} is too long`)}
 if(body.linkedin_url){try{const u=new URL(String(body.linkedin_url));if(!['http:','https:'].includes(u.protocol))throw new Error()}catch{throw new Error('Invalid LinkedIn URL')}}
 const {data:job,error:je}=await supabase.from('jobs').select('id,company_id,status,application_questions').eq('id',body.job_id).eq('status','published').single(); if(je||!job)throw new Error('Opportunity is no longer available');
 let answers:any={}; try{answers=body.answers?JSON.parse(String(body.answers)):{}}catch{throw new Error('Invalid qualification answers');}
 const questions=Array.isArray(job.application_questions)?job.application_questions:[];
 for(const q of questions){if(q.required && !String(answers[q.id]??'').trim())throw new Error(`Please answer: ${q.label||q.question||'required question'}`);}
 const {data:existing,error:lookupError}=await supabase.from('candidates').select('id').eq('company_id',job.company_id).eq('email',email).maybeSingle();
 if(lookupError)throw new Error('Unable to process application');
 // An email address is not proof of identity. Never reveal an existing portal token,
 // overwrite an existing CV, or attach an application without verified ownership.
 if(existing)return json({error:'Please contact the recruitment team to apply using your existing record. Identity verification is required.'},409);
 let candidate:any=null;
 if(!candidate){const {data:created,error:ce}=await supabase.from('candidates').insert({company_id:job.company_id,full_name:fullName,email,phone:body.phone||null,location:body.location||null,linkedin_url:body.linkedin_url||null,source:body.source||body.utm_source||'careers',stage:'new',consent_at:new Date().toISOString(),marketing_opt_in_at:(body.marketing_opt_in==='true'||body.marketing_opt_in===true)?new Date().toISOString():null,lawful_basis:'contract_steps',retention_review_at:new Date(Date.now()+6*30.4375*86400000).toISOString(),work_seeker_terms_version:'agency-work-seeker-2026-09-20',work_seeker_terms_agreed_at:new Date().toISOString(),work_seeker_terms_evidence:'careers application checkbox'}).select('id').single();if(ce)throw ce;candidate=created;}
 let resumePath:string|null=null; const resume=body.resume_file as File|undefined;
 if(resume && resume.size){if(resume.size>5*1024*1024)throw new Error('CV must be 5MB or smaller'); const allowedTypes=['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword'];if(resume.type&&!allowedTypes.includes(resume.type))throw new Error('CV must be PDF or Word document'); const ext=(resume.name.split('.').pop()||'pdf').toLowerCase().replace(/[^a-z0-9]/g,'');resumePath=`${job.company_id}/${candidate.id}/${crypto.randomUUID()}.${ext}`;const {error:up}=await supabase.storage.from('candidate-resumes').upload(resumePath,resume,{contentType:resume.type||'application/octet-stream',upsert:false});if(up)throw new Error('CV upload failed'); await supabase.from('candidates').update({resume_path:resumePath}).eq('id',candidate.id);}
 const {data:applicationRow,error:ae}=await supabase.from('applications').insert({company_id:job.company_id,job_id:job.id,candidate_id:candidate.id,cover_note:body.cover_note||null,answers,source:body.source||body.utm_source||'careers',consent_version:'privacy-acknowledgement',privacy_notice_version:'2026-09-16',consent_at:new Date().toISOString(),human_review_required:true,work_seeker_terms_version:'agency-work-seeker-2026-09-20',work_seeker_terms_agreed_at:new Date().toISOString(),source_details:{utm_source:body.utm_source||null,utm_medium:body.utm_medium||null,utm_campaign:body.utm_campaign||null,utm_content:body.utm_content||null,landing_path:body.landing_path||null,referrer:body.referrer||null}}).select('id').single();if(ae)throw ae;
 await supabase.from('application_events').insert({company_id:job.company_id,application_id:applicationRow.id,event_type:'application_submitted',source:body.utm_source||body.source||'careers',medium:body.utm_medium||null,campaign:body.utm_campaign||null,content:body.utm_content||null,landing_path:body.landing_path||null,campaign_id:body.campaign_id||null,metadata:{referrer:body.referrer||null,has_resume:!!resumePath}});
 const {data:seqs}=await supabase.from('automation_sequences').select('id,steps').eq('company_id',job.company_id).eq('trigger_event','application_received').eq('active',true);for(const seq of seqs||[]){const steps=Array.isArray(seq.steps)?seq.steps:[];if(steps.length){const delay=Math.max(0,Number(steps[0]?.delay_hours||0));await supabase.from('automation_enrollments').upsert({company_id:job.company_id,sequence_id:seq.id,candidate_id:candidate.id,application_id:applicationRow.id,current_step:0,status:'queued',next_run_at:new Date(Date.now()+delay*3600000).toISOString()},{onConflict:'sequence_id,candidate_id,application_id'});}}
 const {data:existingToken}=await supabase.from('candidate_portal_tokens').select('token').eq('candidate_id',candidate.id).is('revoked_at',null).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle();let portalToken=existingToken?.token;if(!portalToken){portalToken=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-');await supabase.from('candidate_portal_tokens').insert({token:portalToken,candidate_id:candidate.id,expires_at:new Date(Date.now()+30*86400000).toISOString()});}
 const appUrl=Deno.env.get('PUBLIC_APP_URL')||Deno.env.get('VITE_APP_URL')||''; return json({ok:true,application_id:applicationRow.id,portal_url:appUrl?`${appUrl.replace(/\/$/,'')}/candidate?token=${portalToken}`:null});
}catch(e){return json({error:e instanceof Error?e.message:'Application failed'},400)}});
