import fs from 'node:fs/promises';import path from 'node:path';import {loadEnv} from 'vite';
const env={...loadEnv('production',process.cwd(),''),...process.env};const dist=path.resolve('dist'),base=String(env.VITE_APP_URL||'https://talentflow-nu-neon.vercel.app').replace(/\/$/,'');const sb=env.VITE_SUPABASE_URL,key=env.VITE_SUPABASE_ANON_KEY;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const xml=s=>esc(s);const strip=s=>String(s??'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
async function jobs(){if(!sb||!key)return[];const fields='slug,title,description,location,employment_type,pay_text,application_mode,created_at,updated_at';const r=await fetch(`${sb}/rest/v1/jobs?select=${encodeURIComponent(fields)}&status=eq.published&order=updated_at.desc`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!r.ok){console.warn('SEO build: public jobs unavailable',r.status);return[]}return r.json()}
function inject(html,{title,description,canonical,jsonLd}){const tags=`<meta name="description" content="${esc(description)}"/><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"/><link rel="canonical" href="${esc(canonical)}"/><meta property="og:type" content="website"/><meta property="og:site_name" content="TalentFlow"/><meta property="og:title" content="${esc(title)}"/><meta property="og:description" content="${esc(description)}"/><meta property="og:url" content="${esc(canonical)}"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:title" content="${esc(title)}"/><meta name="twitter:description" content="${esc(description)}"/>${jsonLd?`<script type="application/ld+json">${JSON.stringify(jsonLd).replace(/</g,'\\u003c')}</script>`:''}`;return html.replace(/<title>.*?<\/title>/s,`<title>${esc(title)}</title>`).replace(/<meta name="description"[^>]*>/g,'').replace(/<link rel="canonical"[^>]*>/g,'').replace('</head>',`${tags}</head>`)}
async function writeRoute(route,html){const dir=path.join(dist,...route.split('/').filter(Boolean));await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'index.html'),html)}
const template=await fs.readFile(path.join(dist,'index.html'),'utf8');const rows=await jobs();await writeRoute('/careers',inject(template,{title:'Open recruitment opportunities | TalentFlow Careers',description:'Browse current recruitment opportunities and apply securely online through TalentFlow Careers.',canonical:`${base}/careers`}));
for(const j of rows){const description=strip(j.description||`Apply for ${j.title}${j.location?` in ${j.location}`:''}.`).slice(0,155);const canonical=`${base}/careers/${encodeURIComponent(j.slug)}`;const schema={'@context':'https://schema.org','@type':'JobPosting',title:j.title,description:strip(j.description||j.title),datePosted:j.created_at,dateModified:j.updated_at||j.created_at,employmentType:j.employment_type,url:canonical,directApply:true,jobLocation:j.location?{'@type':'Place',address:{'@type':'PostalAddress',addressLocality:j.location,addressCountry:'GB'}}:undefined};await writeRoute(`/careers/${j.slug}`,inject(template,{title:`${j.title} | TalentFlow Careers`,description,canonical,jsonLd:schema}))}
const urls=[['/',new Date().toISOString()],['/careers',new Date().toISOString()],['/privacy',''],['/candidate-terms',''],['/accessibility',''],...rows.map(j=>[`/careers/${j.slug}`,j.updated_at||j.created_at||''])];const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(([u,d])=>`  <url><loc>${xml(base+u)}</loc>${d?`<lastmod>${xml(new Date(d).toISOString())}</lastmod>`:''}</url>`).join('\n')}\n</urlset>\n`;await fs.writeFile(path.join(dist,'sitemap.xml'),sitemap);await fs.writeFile(path.join(dist,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /dashboard/\nDisallow: /login\nDisallow: /signup\nDisallow: /onboarding\nDisallow: /client\nDisallow: /candidate\nSitemap: ${base}/sitemap.xml\n`);console.log(`SEO build: generated ${rows.length} job pages and ${urls.length} sitemap URLs`);
