-- Second-pass FWA/Conduct Regulations compliance hardening.
-- Mirrors the production schema changes applied on 2026-09-20.
alter table public.candidates add column if not exists postal_address text, add column if not exists under_22 boolean, add column if not exists date_of_birth date, add column if not exists experience_summary text, add column if not exists training_qualifications text, add column if not exists authorisations text, add column if not exists last_work_finding_service_at timestamptz, add column if not exists statutory_retain_until timestamptz;
alter table public.applications add column if not exists vacancy_particulars_provided_at timestamptz, add column if not exists willingness_confirmed_at timestamptz, add column if not exists willingness_evidence text, add column if not exists suitability_checked_at timestamptz, add column if not exists suitability_evidence text, add column if not exists qualification_verified_at timestamptz, add column if not exists qualification_verification_evidence text, add column if not exists reference_1_verified_at timestamptz, add column if not exists reference_2_verified_at timestamptz, add column if not exists vulnerable_checks_evidence text;
alter table public.jobs add column if not exists works_with_vulnerable_people boolean not null default false, add column if not exists qualification_verification_required boolean not null default false, add column if not exists agency_service_type text not null default 'permanent_employment', add column if not exists agency_legal_name_snapshot text, add column if not exists hirer_name_snapshot text;
alter table public.clients add column if not exists last_service_at timestamptz, add column if not exists statutory_retain_until timestamptz;
alter table public.candidate_submissions add column if not exists regulation21_confirmed_at timestamptz, add column if not exists willingness_statement text;
alter table public.companies alter column candidate_retention_months set default 12;
update public.companies set candidate_retention_months=12 where candidate_retention_months<12;

create or replace function public.mark_application_record_retention() returns trigger language plpgsql set search_path=public as $$ begin update public.candidates set last_work_finding_service_at=now(),statutory_retain_until=greatest(coalesce(statutory_retain_until,'epoch'::timestamptz),now()+interval '1 year') where id=new.candidate_id;return new;end $$;
drop trigger if exists trg_application_record_retention on public.applications;
create trigger trg_application_record_retention after insert on public.applications for each row execute function public.mark_application_record_retention();

create or replace function public.record_introduction_compliance(p_application uuid,p_willingness_evidence text,p_suitability_evidence text,p_qualification_evidence text default null,p_reference_1 boolean default false,p_reference_2 boolean default false,p_vulnerable_evidence text default null) returns void language plpgsql security definer set search_path='' as $$ declare a public.applications%rowtype;j public.jobs%rowtype;begin if auth.uid() is null or not public.is_manager() then raise exception 'Staff access required';end if;select * into a from public.applications where id=p_application and company_id=public.current_company_id() for update;if not found then raise exception 'Application unavailable';end if;select * into j from public.jobs where id=a.job_id and company_id=a.company_id;if coalesce(trim(p_willingness_evidence),'')='' or coalesce(trim(p_suitability_evidence),'')='' then raise exception 'Willingness and suitability evidence are required';end if;if j.qualification_verification_required and coalesce(trim(p_qualification_evidence),'')='' then raise exception 'Qualification verification evidence is required';end if;if j.works_with_vulnerable_people and (not p_reference_1 or not p_reference_2 or coalesce(trim(p_vulnerable_evidence),'')='') then raise exception 'Two references and vulnerable-person checks are required';end if;update public.applications set vacancy_particulars_provided_at=now(),willingness_confirmed_at=now(),willingness_evidence=p_willingness_evidence,suitability_checked_at=now(),suitability_evidence=p_suitability_evidence,qualification_verified_at=case when coalesce(trim(p_qualification_evidence),'')<>'' then now() else qualification_verified_at end,qualification_verification_evidence=nullif(trim(p_qualification_evidence),''),reference_1_verified_at=case when p_reference_1 then now() else reference_1_verified_at end,reference_2_verified_at=case when p_reference_2 then now() else reference_2_verified_at end,vulnerable_checks_evidence=nullif(trim(p_vulnerable_evidence),'') where id=a.id;end $$;
revoke all on function public.record_introduction_compliance(uuid,text,text,text,boolean,boolean,text) from public,anon;
grant execute on function public.record_introduction_compliance(uuid,text,text,text,boolean,boolean,text) to authenticated;

-- The full publish and reserve functions are intentionally maintained by their dedicated
-- migrations/functions; production versions enforce permanent-only publication, complete
-- Regulation 18 particulars, client terms, statutory candidate records, suitability,
-- willingness, qualification checks and vulnerable-person checks before introduction.
