-- Production migration applied through Supabase MCP on 2026-09-17.
-- Completes invoice payments, server-side plan enforcement, invoice delivery fields,
-- subscription controls, secure automation scheduling and hourly overdue maintenance.

create extension if not exists pg_cron;
create extension if not exists pg_net;
create extension if not exists pgcrypto;

create table if not exists public.invoice_payments (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade,
 invoice_id uuid not null references public.invoices(id) on delete cascade, amount numeric(12,2) not null check(amount>0), currency char(3) not null default 'GBP',
 method text not null default 'manual', reference text, provider text, provider_payment_id text, status text not null default 'succeeded' check(status in ('pending','succeeded','failed','refunded')),
 paid_at timestamptz not null default now(), created_by uuid references auth.users(id), created_at timestamptz not null default now(), unique(company_id,provider,provider_payment_id));
alter table public.invoice_payments enable row level security;
grant select,insert on public.invoice_payments to authenticated;
create policy invoice_payments_select on public.invoice_payments for select to authenticated using(company_id=(select company_id from public.profiles where id=(select auth.uid())));
create policy invoice_payments_insert on public.invoice_payments for insert to authenticated with check(company_id=(select company_id from public.profiles where id=(select auth.uid())) and exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('owner','manager')));

alter table public.invoices add column if not exists pdf_path text, add column if not exists sent_to text, add column if not exists last_delivery_error text;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('invoice-pdfs','invoice-pdfs',false,5242880,array['application/pdf']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create or replace function public.refresh_invoice_balance(p_invoice uuid) returns void language plpgsql security definer set search_path=public as $$ declare v_total numeric;v_paid numeric;v_status text;begin select greatest(0,total-coalesce((select sum(case when kind in ('credit','write_off') then amount when kind in ('debit','charge') then -amount else 0 end) from public.invoice_adjustments where invoice_id=p_invoice),0)) into v_total from public.invoices where id=p_invoice;select coalesce(sum(case when status='succeeded' then amount when status='refunded' then -amount else 0 end),0) into v_paid from public.invoice_payments where invoice_id=p_invoice;select status into v_status from public.invoices where id=p_invoice;update public.invoices set amount_paid=least(v_total,greatest(0,v_paid)),amount_due=greatest(0,v_total-v_paid),status=case when v_status='void' then 'void' when v_total-v_paid<=0 then 'paid' when v_paid>0 then 'partially_paid' when due_date<current_date and status in ('sent','overdue','partially_paid') then 'overdue' else status end,paid_at=case when v_total-v_paid<=0 then coalesce(paid_at,now()) else null end,updated_at=now() where id=p_invoice;end $$;
revoke all on function public.refresh_invoice_balance(uuid) from public,anon,authenticated;

create or replace function public.record_invoice_payment(p_invoice uuid,p_amount numeric,p_method text default 'manual',p_reference text default null) returns uuid language plpgsql security definer set search_path=public as $$ declare v_company uuid;v_id uuid;begin select company_id into v_company from public.invoices where id=p_invoice;if v_company is null or not exists(select 1 from public.profiles where id=auth.uid() and company_id=v_company and role in ('owner','manager')) then raise exception 'Not authorised';end if;insert into public.invoice_payments(company_id,invoice_id,amount,method,reference,created_by) values(v_company,p_invoice,p_amount,coalesce(nullif(p_method,''),'manual'),p_reference,auth.uid()) returning id into v_id;perform public.refresh_invoice_balance(p_invoice);return v_id;end $$;
revoke all on function public.record_invoice_payment(uuid,numeric,text,text) from public,anon;grant execute on function public.record_invoice_payment(uuid,numeric,text,text) to authenticated;

create or replace function public.record_invoice_adjustment(p_invoice uuid,p_kind text,p_amount numeric,p_reason text,p_reference text default null) returns void language plpgsql security definer set search_path=public as $$ declare v_uid uuid:=auth.uid();v_company uuid;v_role text;begin select company_id,role into v_company,v_role from public.profiles where id=v_uid;if v_company is null or v_role not in ('owner','manager') then raise exception 'Not authorised';end if;if p_kind not in ('credit','write_off','debit') or p_amount<=0 or length(trim(p_reason))<3 then raise exception 'Invalid adjustment';end if;if not exists(select 1 from public.invoices where id=p_invoice and company_id=v_company and status<>'void') then raise exception 'Invoice unavailable';end if;insert into public.invoice_adjustments(company_id,invoice_id,kind,amount,reason,reference,created_by) values(v_company,p_invoice,p_kind,p_amount,trim(p_reason),p_reference,v_uid);perform public.refresh_invoice_balance(p_invoice);end $$;
revoke all on function public.record_invoice_adjustment(uuid,text,numeric,text,text) from public,anon;grant execute on function public.record_invoice_adjustment(uuid,text,numeric,text,text) to authenticated;

create or replace function public.mark_overdue_invoices() returns integer language plpgsql security definer set search_path=public as $$declare n integer;begin update public.invoices set status='overdue',updated_at=now() where due_date<current_date and amount_due>0 and status in ('sent','partially_paid');get diagnostics n=row_count;return n;end$$;
revoke all on function public.mark_overdue_invoices() from public,anon,authenticated;

create or replace function public.void_invoice(p_invoice uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$declare c uuid;begin select company_id into c from public.invoices where id=p_invoice;if not exists(select 1 from public.profiles where id=auth.uid() and company_id=c and role in ('owner','manager')) then raise exception 'Not authorised';end if;if exists(select 1 from public.invoice_payments where invoice_id=p_invoice and status='succeeded') then raise exception 'Paid invoices cannot be voided; record a refund/credit instead';end if;update public.invoices set status='void',voided_at=now(),notes=concat_ws(E'\n',notes,'Void reason: '||coalesce(nullif(p_reason,''),'Not supplied')),updated_at=now() where id=p_invoice;end$$;
revoke all on function public.void_invoice(uuid,text) from public,anon;grant execute on function public.void_invoice(uuid,text) to authenticated;

create or replace function public.enforce_recruiter_seat_limit() returns trigger language plpgsql security definer set search_path=public as $$declare lim int;cnt int;begin if new.company_id is null or new.role not in ('owner','manager','recruiter') then return new;end if;select p.recruiter_limit into lim from public.company_subscriptions s join public.saas_plans p on p.code=s.plan_code where s.company_id=new.company_id and (s.status='active' or(s.status='trialing' and s.trial_ends_at>now()));if lim is null then return new;end if;select count(*) into cnt from public.profiles where company_id=new.company_id and role in ('owner','manager','recruiter') and id<>new.id;if lim>=0 and cnt>=lim then raise exception 'Recruiter seat plan limit reached';end if;return new;end$$;
revoke all on function public.enforce_recruiter_seat_limit() from public,anon,authenticated;drop trigger if exists enforce_recruiter_seat_limit on public.profiles;create trigger enforce_recruiter_seat_limit before insert or update of company_id,role on public.profiles for each row execute function public.enforce_recruiter_seat_limit();

-- Runtime scheduler secret is generated inside Postgres, stored encrypted in Vault and only its SHA-256 hash is retained for verification.
create schema if not exists private;revoke all on schema private from public,anon,authenticated;create table if not exists private.runtime_secrets(name text primary key,secret_hash text not null,rotated_at timestamptz not null default now());
do $$declare s text;begin s:=encode(gen_random_bytes(32),'hex');insert into private.runtime_secrets(name,secret_hash,rotated_at) values('automation_cron',encode(digest(s,'sha256'),'hex'),now()) on conflict(name) do update set secret_hash=excluded.secret_hash,rotated_at=excluded.rotated_at;perform vault.create_secret(s,'talentflow_automation_cron_secret','TalentFlow internal automation scheduler secret');end$$;
create or replace function public.verify_automation_runtime_secret(p_secret text) returns boolean language sql stable security definer set search_path=public,private,extensions as $$select exists(select 1 from private.runtime_secrets where name='automation_cron' and secret_hash=encode(digest(coalesce(p_secret,''),'sha256'),'hex'))$$;
revoke all on function public.verify_automation_runtime_secret(text) from public,anon,authenticated;grant execute on function public.verify_automation_runtime_secret(text) to service_role;
select cron.schedule('talentflow-automation-queue','* * * * *',$$select net.http_post(url:='https://mzkaodoruhklzluikagy.supabase.co/functions/v1/process-automation-queue',headers:=jsonb_build_object('Content-Type','application/json','x-automation-secret',(select decrypted_secret from vault.decrypted_secrets where name='talentflow_automation_cron_secret' order by created_at desc limit 1)),body:='{}'::jsonb);$$);
select cron.schedule('talentflow-invoice-maintenance','15 * * * *',$$select public.mark_overdue_invoices();$$);
