-- Partner production onboarding, agreement, attribution and commission controls.
-- Applied to production on 2026-09-21. See live schema for RLS policies and trigger definitions.
create table if not exists public.partner_agreements(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,partner_id uuid not null references auth.users(id) on delete cascade,version text not null,status text not null default 'pending' check(status in('pending','accepted','superseded','terminated')),commission_percent numeric(5,2) not null default 30 check(commission_percent between 0 and 100),terms_text text not null,accepted_at timestamptz,accepted_name text,created_at timestamptz not null default now(),unique(partner_id,version));
create table if not exists public.partner_onboarding(partner_id uuid primary key references auth.users(id) on delete cascade,company_id uuid not null references public.companies(id) on delete cascade,status text not null default 'terms_pending' check(status in('invited','terms_pending','details_pending','review_pending','active','suspended','terminated')),legal_name text,trading_name text,country text,address text,phone text,tax_reference text,payment_method text,payment_details_reference text,agreement_id uuid references public.partner_agreements(id),reviewed_by uuid references auth.users(id),reviewed_at timestamptz,activated_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.partner_attributions(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,partner_id uuid not null references auth.users(id),client_id uuid references public.clients(id),job_id uuid references public.jobs(id),candidate_id uuid references public.candidates(id),placement_id uuid references public.placements(id),attribution_type text not null check(attribution_type in('client_originator','vacancy_originator','candidate_originator','placement_owner')),status text not null default 'active' check(status in('active','disputed','superseded')),evidence text,attributed_at timestamptz not null default now(),attributed_by uuid references auth.users(id));
alter table public.partner_agreements enable row level security;alter table public.partner_onboarding enable row level security;alter table public.partner_attributions enable row level security;
alter table public.partner_commissions add column if not exists agreement_id uuid references public.partner_agreements(id),add column if not exists invoice_id uuid references public.invoices(id),add column if not exists eligible_fee_received numeric(12,2) not null default 0,add column if not exists approved_at timestamptz,add column if not exists approved_by uuid references auth.users(id),add column if not exists payment_reference text,add column if not exists notes text;
-- Production policies restrict partner rows to self and managers to the current workspace.
-- Production partner_is_active() fails closed unless onboarding is active and current terms are accepted.
-- Production invoice trigger accrues commission only from qualifying fees actually received by Vorlen.

-- Follow-up hardening applied in production:
-- partner_is_active is evaluated at the database boundary for partner access policies.
-- accept_partner_agreement atomically captures acceptance evidence and SHA-256 terms hash.
-- activate_partner validates completed details and accepted terms before manager activation.
-- clients/candidates/jobs/activity/notes/tasks partner policies require active onboarding.
